import com.ofss.digx.cz.bea.app.hosttohost.util.HthApiPasswordCrypto;
import java.util.Base64;

/** Standalone compatibility test; uses synthetic bytes 0..31, never an environment key. */
public final class HthApiPasswordCryptoTest {
  private static int checks;
  private static void check(boolean value, String name) {
    if (!value) { throw new AssertionError(name); }
    checks++;
  }
  private static void rejects(Runnable operation, String name) {
    boolean rejected = false;
    try { operation.run(); } catch (IllegalStateException expected) { rejected = true; }
    check(rejected, name);
  }
  public static void main(String[] args) {
    byte[] bytes = new byte[32];
    for (int i = 0; i < bytes.length; i++) { bytes[i] = (byte) i; }
    String key = Base64.getEncoder().encodeToString(bytes);
    // Fixture generated by the supplied, unmodified 787 encrypt implementation.
    String legacy = "129m1Vx6wSbTHYTM2JV91DuBz6pfOhcTcA4SMwo8ltfEIw==";
    check("001234".equals(HthApiPasswordCrypto.decrypt(legacy, key)), "decrypt 787 envelope");
    check(HthApiPasswordCrypto.constantTimeEquals("001234", "001234"), "equal code");
    check(!HthApiPasswordCrypto.constantTimeEquals("001234", "1234"), "leading zeros significant");
    check(!HthApiPasswordCrypto.constantTimeEquals("001234", ""), "empty submitted value");
    check(!HthApiPasswordCrypto.constantTimeEquals("", "001234"), "empty stored value");
    check(!HthApiPasswordCrypto.constantTimeEquals(null, "001234"), "null value");
    for (int i = 0; i < 100; i++) {
      String code = HthApiPasswordCrypto.randomDigits(6);
      check(code.matches("[0-9]{6}"), "six digits");
      String encrypted = HthApiPasswordCrypto.encrypt(code, key);
      check(code.equals(HthApiPasswordCrypto.decrypt(encrypted, key)), "round trip");
      check(Base64.getDecoder().decode(encrypted).length == 34, "12 IV + 6 code + 16 tag");
    }
    byte[] damaged = Base64.getDecoder().decode(legacy);
    damaged[damaged.length - 1] ^= 1;
    rejects(() -> HthApiPasswordCrypto.decrypt(Base64.getEncoder().encodeToString(damaged), key), "tampered tag");
    rejects(() -> HthApiPasswordCrypto.decrypt(legacy, Base64.getEncoder().encodeToString(new byte[32])), "wrong key");
    rejects(() -> HthApiPasswordCrypto.decrypt("", key), "truncated envelope");
    rejects(() -> HthApiPasswordCrypto.decrypt("not base64", key), "malformed envelope");
    rejects(() -> HthApiPasswordCrypto.encrypt("001234", ""), "missing key");
    rejects(() -> HthApiPasswordCrypto.encrypt("001234", Base64.getEncoder().encodeToString(new byte[16])), "short key");
    System.out.println("PASS: " + checks + " crypto compatibility and rejection checks");
  }
}
