-- BCOH2H-851. Execute this entire block as one statement, then COMMIT.

-- Rerunnable: only 851 events/templates are replaced; existing BCO activity metadata is retained.

-- Flag defaults OFF. Re-running preserves its existing value. See README before enabling.

-- Template copy is a working EN/TC/SC implementation of matrix #7/#8/#9, pending BA wording sign-off.

BEGIN

  SAVEPOINT HTH_CONTACT_CONFIG;

INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS, SUMMARY_TEXT,
  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
SELECT 'HTH_PROFILE_CONTACT_NOTIFICATION_ENABLED', 'HthProfileContactNotification', 'false', 'N', 'BCOH2H-851 contact notification',
 'HTH Profile Contact Notification', USER, SYSDATE, USER, SYSDATE, 'A', 1, 'N', NULL FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_FW_CONFIG_ALL_B WHERE CATEGORY_ID = 'HthProfileContactNotification' AND PROP_ID = 'HTH_PROFILE_CONTACT_NOTIFICATION_ENABLED');

INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS, SUMMARY_TEXT,
  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
SELECT 'dispatchDataSource', 'HthProfileContactNotification', 'NONXA', 'N', 'BCOH2H-851 contact notification',
 'HTH Profile Contact Notification', USER, SYSDATE, USER, SYSDATE, 'A', 1, 'N', NULL FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_FW_CONFIG_ALL_B WHERE CATEGORY_ID = 'HthProfileContactNotification' AND PROP_ID = 'dispatchDataSource');

INSERT INTO DIGX_EP_ACT_B
 (COD_ACT_ID, TXT_ACT_NAME, TXT_ACT_DESC, MODULE_TYPE, FLG_IP_REQD, FLG_OP_REQD,
  FLG_LOG_REQD, TXT_LOG_CLASS, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY,
  LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
SELECT 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'UserExtensionData.update', 'Update CM User Profile', 'PC', NULL, NULL, NULL, NULL,
 USER, SYSDATE, USER, SYSDATE, 1, 'A', 'CZ' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_EP_ACT_B WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update');

UPDATE DIGX_MD_GEN_ATTR_LEGACY_B SET TXT_CONSTRAINT_ATTR_NAME='hthContactUserName', DATA_TYPE='java.lang.String', OBJECT_STATUS='A'
WHERE COD_CONSTRAINT_ATTR_ID='hthContactUserName';
INSERT INTO DIGX_MD_GEN_ATTR_LEGACY_B
 (COD_CONSTRAINT_ATTR_ID, TXT_CONSTRAINT_ATTR_NAME, DATA_TYPE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS)
SELECT 'hthContactUserName', 'hthContactUserName', 'java.lang.String', USER, SYSDATE, USER, SYSDATE, 1, 'A' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_MD_GEN_ATTR_LEGACY_B WHERE COD_CONSTRAINT_ATTR_ID='hthContactUserName');
UPDATE DIGX_MD_SERVICE_ATTR SET TYP_DATA_AVAIL='INDIRECT', TYP_DATA_SRC='DTO', COD_ATTR_ID='hthContactUserName', COD_SERVICE_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update',
 PARAMETER_NAME=NULL, REF_ENT_DEFN_ID=NULL, KEY_SERVICE_ATTR_ID=NULL, REF_FIELD_DEFN_ID = 'com.ofss.digx.cz.bea.app.sms.dto.user.HthProfileContactUpdateActivityLogDTO.HthContactUserName', OBJECT_STATUS='A'
WHERE COD_SERVICE_ATTR_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO';
INSERT INTO DIGX_MD_SERVICE_ATTR
 (COD_SERVICE_ATTR_ID, TYP_DATA_AVAIL, TYP_DATA_SRC, COD_ATTR_ID, COD_SERVICE_ID, PARAMETER_NAME, REF_ENT_DEFN_ID,
 KEY_SERVICE_ATTR_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, REF_FIELD_DEFN_ID)
SELECT 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'INDIRECT', 'DTO', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', NULL, NULL, NULL, USER, SYSDATE, USER, SYSDATE, 1, 'A', 'com.ofss.digx.cz.bea.app.sms.dto.user.HthProfileContactUpdateActivityLogDTO.HthContactUserName' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_MD_SERVICE_ATTR WHERE COD_SERVICE_ATTR_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO');

UPDATE DIGX_MD_GEN_ATTR_LEGACY_B SET TXT_CONSTRAINT_ATTR_NAME='hthContactApprovedAt', DATA_TYPE='java.lang.String', OBJECT_STATUS='A'
WHERE COD_CONSTRAINT_ATTR_ID='hthContactApprovedAt';
INSERT INTO DIGX_MD_GEN_ATTR_LEGACY_B
 (COD_CONSTRAINT_ATTR_ID, TXT_CONSTRAINT_ATTR_NAME, DATA_TYPE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS)
SELECT 'hthContactApprovedAt', 'hthContactApprovedAt', 'java.lang.String', USER, SYSDATE, USER, SYSDATE, 1, 'A' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_MD_GEN_ATTR_LEGACY_B WHERE COD_CONSTRAINT_ATTR_ID='hthContactApprovedAt');
UPDATE DIGX_MD_SERVICE_ATTR SET TYP_DATA_AVAIL='INDIRECT', TYP_DATA_SRC='DTO', COD_ATTR_ID='hthContactApprovedAt', COD_SERVICE_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update',
 PARAMETER_NAME=NULL, REF_ENT_DEFN_ID=NULL, KEY_SERVICE_ATTR_ID=NULL, REF_FIELD_DEFN_ID = 'com.ofss.digx.cz.bea.app.sms.dto.user.HthProfileContactUpdateActivityLogDTO.HthContactApprovedAt', OBJECT_STATUS='A'
WHERE COD_SERVICE_ATTR_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO';
INSERT INTO DIGX_MD_SERVICE_ATTR
 (COD_SERVICE_ATTR_ID, TYP_DATA_AVAIL, TYP_DATA_SRC, COD_ATTR_ID, COD_SERVICE_ID, PARAMETER_NAME, REF_ENT_DEFN_ID,
 KEY_SERVICE_ATTR_ID, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, REF_FIELD_DEFN_ID)
SELECT 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'INDIRECT', 'DTO', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', NULL, NULL, NULL, USER, SYSDATE, USER, SYSDATE, 1, 'A', 'com.ofss.digx.cz.bea.app.sms.dto.user.HthProfileContactUpdateActivityLogDTO.HthContactApprovedAt' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_MD_SERVICE_ATTR WHERE COD_SERVICE_ATTR_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO');

-- HTH_PROFILE_CONTACT_UPDATED_API
DELETE FROM DIGX_EP_MSG_SRC_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_CONTACT_API_EMAIL_en', 'HTH_851_CONTACT_API_EMAIL_zh-Hant', 'HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'HTH_851_CONTACT_API_SMS_en', 'HTH_851_CONTACT_API_SMS_zh-Hant', 'HTH_851_CONTACT_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_MSG_ATTR_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_CONTACT_API_EMAIL_en', 'HTH_851_CONTACT_API_EMAIL_zh-Hant', 'HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'HTH_851_CONTACT_API_SMS_en', 'HTH_851_CONTACT_API_SMS_zh-Hant', 'HTH_851_CONTACT_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_EVT_REC_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_CONTACT_UPDATED_API';
DELETE FROM DIGX_EP_ACT_EVT_ACN_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_CONTACT_UPDATED_API';
DELETE FROM DIGX_EP_ACT_EVT_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_CONTACT_UPDATED_API';
DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN ('HTH_851_CONTACT_API_EMAIL_en', 'HTH_851_CONTACT_API_EMAIL_zh-Hant', 'HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'HTH_851_CONTACT_API_SMS_en', 'HTH_851_CONTACT_API_SMS_zh-Hant', 'HTH_851_CONTACT_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_PM_EVENT_ALL_B WHERE EVENT_CODE='HTH_PROFILE_CONTACT_UPDATED_API';
INSERT INTO DIGX_PM_EVENT_ALL_B
 (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE, FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY,
 ACCT_DOMAIN_CATEGORY, ALERTS_FLAG, FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
 REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE, DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES ('HTH_PROFILE_CONTACT_UPDATED_API', 'HTH Profile CONTACT Update API', NULL, NULL, NULL, NULL, NULL, NULL, 'Y','N','N','N','N',NULL,'N','N',NULL,NULL,'N','N','N');
INSERT INTO DIGX_EP_ACT_EVT_B (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'HTH Profile CONTACT Update API', 'OTHER', 'ONLINE', 'CZ');
INSERT INTO DIGX_EP_ACT_EVT_ACN_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE, COD_DEC_ID, FLG_CONDITIONAL,
 COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
 NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE, ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'N', NULL, '0', 'N', '1', 'HTH Profile CONTACT Update API', USER, SYSDATE,
 USER, SYSDATE, 1, 0, 'N', DATE '2099-12-31', 'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_en', 'EMAIL', 'HTH 851 CONTACT API EMAIL en', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her email address and mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的 HTH API 用戶 #hthContactUserName# 已確認更新其電郵地址及流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Email Address And Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'HTH_851_CONTACT_API_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_en', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_en', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_en', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_en', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hant', 'EMAIL', 'HTH 851 CONTACT API EMAIL zh-Hant', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her email address and mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的 HTH API 用戶 #hthContactUserName# 已確認更新其電郵地址及流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Email Address And Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'HTH_851_CONTACT_API_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hant', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hant', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hant', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hant', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH 851 CONTACT API EMAIL zh-Hans-CN', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her email address and mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊贵的客户：</p><p>贵公司的 HTH API 用户 #hthContactUserName# 已确认更新其电邮地址及流动电话号码。</p><p>系统日期／时间：#hthContactApprovedAt#（香港时间）。</p><p>如有查询，请致电本行热线 (852) 2211 1321。</p><p>东亚银行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Email Address And Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_SMS_en', 'SMS', 'HTH 851 CONTACT API SMS en', 'BCOH2H-851', 'Your company has confirmed the update of email address and mobile number of H2H API Profile. For details, please log into your account or call (852) 2211 1321.', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'HTH_851_CONTACT_API_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_SMS_zh-Hant', 'SMS', 'HTH 851 CONTACT API SMS zh-Hant', 'BCOH2H-851', '貴公司已確認更新 H2H API 用戶的電郵地址及流動電話號碼。詳情請登入您的賬戶或致電 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'HTH_851_CONTACT_API_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_API_SMS_zh-Hans-CN', 'SMS', 'HTH 851 CONTACT API SMS zh-Hans-CN', 'BCOH2H-851', '贵公司已确认更新 H2H API 用户的电邮地址及流动电话号码。详情请登入您的账户或致电 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_API', 'A', 'HTH_851_CONTACT_API_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

-- HTH_PROFILE_CONTACT_UPDATED_AP
DELETE FROM DIGX_EP_MSG_SRC_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_CONTACT_AP_EMAIL_en', 'HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'HTH_851_CONTACT_AP_SMS_en', 'HTH_851_CONTACT_AP_SMS_zh-Hant', 'HTH_851_CONTACT_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_MSG_ATTR_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_CONTACT_AP_EMAIL_en', 'HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'HTH_851_CONTACT_AP_SMS_en', 'HTH_851_CONTACT_AP_SMS_zh-Hant', 'HTH_851_CONTACT_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_EVT_REC_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_CONTACT_UPDATED_AP';
DELETE FROM DIGX_EP_ACT_EVT_ACN_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_CONTACT_UPDATED_AP';
DELETE FROM DIGX_EP_ACT_EVT_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_CONTACT_UPDATED_AP';
DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN ('HTH_851_CONTACT_AP_EMAIL_en', 'HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'HTH_851_CONTACT_AP_SMS_en', 'HTH_851_CONTACT_AP_SMS_zh-Hant', 'HTH_851_CONTACT_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_PM_EVENT_ALL_B WHERE EVENT_CODE='HTH_PROFILE_CONTACT_UPDATED_AP';
INSERT INTO DIGX_PM_EVENT_ALL_B
 (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE, FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY,
 ACCT_DOMAIN_CATEGORY, ALERTS_FLAG, FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
 REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE, DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES ('HTH_PROFILE_CONTACT_UPDATED_AP', 'HTH Profile CONTACT Update AP', NULL, NULL, NULL, NULL, NULL, NULL, 'Y','N','N','N','N',NULL,'N','N',NULL,NULL,'N','N','N');
INSERT INTO DIGX_EP_ACT_EVT_B (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'HTH Profile CONTACT Update AP', 'OTHER', 'ONLINE', 'CZ');
INSERT INTO DIGX_EP_ACT_EVT_ACN_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE, COD_DEC_ID, FLG_CONDITIONAL,
 COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
 NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE, ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'N', NULL, '0', 'N', '1', 'HTH Profile CONTACT Update AP', USER, SYSDATE,
 USER, SYSDATE, 1, 0, 'N', DATE '2099-12-31', 'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_en', 'EMAIL', 'HTH 851 CONTACT AP EMAIL en', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her email address and mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的用戶 #hthContactUserName# 已確認更新其電郵地址及流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Email Address And Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'HTH_851_CONTACT_AP_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_en', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_en', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_en', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_en', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'EMAIL', 'HTH 851 CONTACT AP EMAIL zh-Hant', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her email address and mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的用戶 #hthContactUserName# 已確認更新其電郵地址及流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Email Address And Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hant', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH 851 CONTACT AP EMAIL zh-Hans-CN', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her email address and mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊贵的客户：</p><p>贵公司的用户 #hthContactUserName# 已确认更新其电邮地址及流动电话号码。</p><p>系统日期／时间：#hthContactApprovedAt#（香港时间）。</p><p>如有查询，请致电本行热线 (852) 2211 1321。</p><p>东亚银行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Email Address And Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_SMS_en', 'SMS', 'HTH 851 CONTACT AP SMS en', 'BCOH2H-851', 'Your company has confirmed the update of email address and mobile number of H2H API Profile. For details, please log into your account or call (852) 2211 1321.', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'HTH_851_CONTACT_AP_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_SMS_zh-Hant', 'SMS', 'HTH 851 CONTACT AP SMS zh-Hant', 'BCOH2H-851', '貴公司已確認更新 H2H API 用戶的電郵地址及流動電話號碼。詳情請登入您的賬戶或致電 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'HTH_851_CONTACT_AP_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_CONTACT_AP_SMS_zh-Hans-CN', 'SMS', 'HTH 851 CONTACT AP SMS zh-Hans-CN', 'BCOH2H-851', '贵公司已确认更新 H2H API 用户的电邮地址及流动电话号码。详情请登入您的账户或致电 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_CONTACT_UPDATED_AP', 'A', 'HTH_851_CONTACT_AP_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

-- HTH_PROFILE_EMAIL_UPDATED_API
DELETE FROM DIGX_EP_MSG_SRC_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_EMAIL_API_EMAIL_en', 'HTH_851_EMAIL_API_EMAIL_zh-Hant', 'HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'HTH_851_EMAIL_API_SMS_en', 'HTH_851_EMAIL_API_SMS_zh-Hant', 'HTH_851_EMAIL_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_MSG_ATTR_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_EMAIL_API_EMAIL_en', 'HTH_851_EMAIL_API_EMAIL_zh-Hant', 'HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'HTH_851_EMAIL_API_SMS_en', 'HTH_851_EMAIL_API_SMS_zh-Hant', 'HTH_851_EMAIL_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_EVT_REC_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_EMAIL_UPDATED_API';
DELETE FROM DIGX_EP_ACT_EVT_ACN_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_EMAIL_UPDATED_API';
DELETE FROM DIGX_EP_ACT_EVT_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_EMAIL_UPDATED_API';
DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN ('HTH_851_EMAIL_API_EMAIL_en', 'HTH_851_EMAIL_API_EMAIL_zh-Hant', 'HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'HTH_851_EMAIL_API_SMS_en', 'HTH_851_EMAIL_API_SMS_zh-Hant', 'HTH_851_EMAIL_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_PM_EVENT_ALL_B WHERE EVENT_CODE='HTH_PROFILE_EMAIL_UPDATED_API';
INSERT INTO DIGX_PM_EVENT_ALL_B
 (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE, FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY,
 ACCT_DOMAIN_CATEGORY, ALERTS_FLAG, FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
 REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE, DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES ('HTH_PROFILE_EMAIL_UPDATED_API', 'HTH Profile EMAIL Update API', NULL, NULL, NULL, NULL, NULL, NULL, 'Y','N','N','N','N',NULL,'N','N',NULL,NULL,'N','N','N');
INSERT INTO DIGX_EP_ACT_EVT_B (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'HTH Profile EMAIL Update API', 'OTHER', 'ONLINE', 'CZ');
INSERT INTO DIGX_EP_ACT_EVT_ACN_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE, COD_DEC_ID, FLG_CONDITIONAL,
 COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
 NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE, ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'N', NULL, '0', 'N', '1', 'HTH Profile EMAIL Update API', USER, SYSDATE,
 USER, SYSDATE, 1, 0, 'N', DATE '2099-12-31', 'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_en', 'EMAIL', 'HTH 851 EMAIL API EMAIL en', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her email address.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的 HTH API 用戶 #hthContactUserName# 已確認更新其電郵地址。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Email Address Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'HTH_851_EMAIL_API_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_en', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_en', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_en', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_en', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hant', 'EMAIL', 'HTH 851 EMAIL API EMAIL zh-Hant', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her email address.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的 HTH API 用戶 #hthContactUserName# 已確認更新其電郵地址。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Email Address Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'HTH_851_EMAIL_API_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hant', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hant', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hant', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hant', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH 851 EMAIL API EMAIL zh-Hans-CN', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her email address.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊贵的客户：</p><p>贵公司的 HTH API 用户 #hthContactUserName# 已确认更新其电邮地址。</p><p>系统日期／时间：#hthContactApprovedAt#（香港时间）。</p><p>如有查询，请致电本行热线 (852) 2211 1321。</p><p>东亚银行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Email Address Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_SMS_en', 'SMS', 'HTH 851 EMAIL API SMS en', 'BCOH2H-851', 'Your company has confirmed the update of email address of H2H API Profile. For details, please log into your account or call (852) 2211 1321.', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'HTH_851_EMAIL_API_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_SMS_zh-Hant', 'SMS', 'HTH 851 EMAIL API SMS zh-Hant', 'BCOH2H-851', '貴公司已確認更新 H2H API 用戶的電郵地址。詳情請登入您的賬戶或致電 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'HTH_851_EMAIL_API_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_API_SMS_zh-Hans-CN', 'SMS', 'HTH 851 EMAIL API SMS zh-Hans-CN', 'BCOH2H-851', '贵公司已确认更新 H2H API 用户的电邮地址。详情请登入您的账户或致电 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_API', 'A', 'HTH_851_EMAIL_API_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

-- HTH_PROFILE_EMAIL_UPDATED_AP
DELETE FROM DIGX_EP_MSG_SRC_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_EMAIL_AP_EMAIL_en', 'HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'HTH_851_EMAIL_AP_SMS_en', 'HTH_851_EMAIL_AP_SMS_zh-Hant', 'HTH_851_EMAIL_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_MSG_ATTR_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_EMAIL_AP_EMAIL_en', 'HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'HTH_851_EMAIL_AP_SMS_en', 'HTH_851_EMAIL_AP_SMS_zh-Hant', 'HTH_851_EMAIL_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_EVT_REC_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_EMAIL_UPDATED_AP';
DELETE FROM DIGX_EP_ACT_EVT_ACN_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_EMAIL_UPDATED_AP';
DELETE FROM DIGX_EP_ACT_EVT_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_EMAIL_UPDATED_AP';
DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN ('HTH_851_EMAIL_AP_EMAIL_en', 'HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'HTH_851_EMAIL_AP_SMS_en', 'HTH_851_EMAIL_AP_SMS_zh-Hant', 'HTH_851_EMAIL_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_PM_EVENT_ALL_B WHERE EVENT_CODE='HTH_PROFILE_EMAIL_UPDATED_AP';
INSERT INTO DIGX_PM_EVENT_ALL_B
 (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE, FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY,
 ACCT_DOMAIN_CATEGORY, ALERTS_FLAG, FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
 REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE, DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES ('HTH_PROFILE_EMAIL_UPDATED_AP', 'HTH Profile EMAIL Update AP', NULL, NULL, NULL, NULL, NULL, NULL, 'Y','N','N','N','N',NULL,'N','N',NULL,NULL,'N','N','N');
INSERT INTO DIGX_EP_ACT_EVT_B (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'HTH Profile EMAIL Update AP', 'OTHER', 'ONLINE', 'CZ');
INSERT INTO DIGX_EP_ACT_EVT_ACN_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE, COD_DEC_ID, FLG_CONDITIONAL,
 COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
 NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE, ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'N', NULL, '0', 'N', '1', 'HTH Profile EMAIL Update AP', USER, SYSDATE,
 USER, SYSDATE, 1, 0, 'N', DATE '2099-12-31', 'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_en', 'EMAIL', 'HTH 851 EMAIL AP EMAIL en', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her email address.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的用戶 #hthContactUserName# 已確認更新其電郵地址。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Email Address Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'HTH_851_EMAIL_AP_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_en', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_en', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_en', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_en', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'EMAIL', 'HTH 851 EMAIL AP EMAIL zh-Hant', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her email address.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的用戶 #hthContactUserName# 已確認更新其電郵地址。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Email Address Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hant', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH 851 EMAIL AP EMAIL zh-Hans-CN', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her email address.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊贵的客户：</p><p>贵公司的用户 #hthContactUserName# 已确认更新其电邮地址。</p><p>系统日期／时间：#hthContactApprovedAt#（香港时间）。</p><p>如有查询，请致电本行热线 (852) 2211 1321。</p><p>东亚银行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Email Address Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_SMS_en', 'SMS', 'HTH 851 EMAIL AP SMS en', 'BCOH2H-851', 'Your company has confirmed the update of email address of H2H API Profile. For details, please log into your account or call (852) 2211 1321.', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'HTH_851_EMAIL_AP_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_SMS_zh-Hant', 'SMS', 'HTH 851 EMAIL AP SMS zh-Hant', 'BCOH2H-851', '貴公司已確認更新 H2H API 用戶的電郵地址。詳情請登入您的賬戶或致電 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'HTH_851_EMAIL_AP_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_EMAIL_AP_SMS_zh-Hans-CN', 'SMS', 'HTH 851 EMAIL AP SMS zh-Hans-CN', 'BCOH2H-851', '贵公司已确认更新 H2H API 用户的电邮地址。详情请登入您的账户或致电 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_EMAIL_UPDATED_AP', 'A', 'HTH_851_EMAIL_AP_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

-- HTH_PROFILE_MOBILE_UPDATED_API
DELETE FROM DIGX_EP_MSG_SRC_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_MOBILE_API_EMAIL_en', 'HTH_851_MOBILE_API_EMAIL_zh-Hant', 'HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'HTH_851_MOBILE_API_SMS_en', 'HTH_851_MOBILE_API_SMS_zh-Hant', 'HTH_851_MOBILE_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_MSG_ATTR_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_MOBILE_API_EMAIL_en', 'HTH_851_MOBILE_API_EMAIL_zh-Hant', 'HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'HTH_851_MOBILE_API_SMS_en', 'HTH_851_MOBILE_API_SMS_zh-Hant', 'HTH_851_MOBILE_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_EVT_REC_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_MOBILE_UPDATED_API';
DELETE FROM DIGX_EP_ACT_EVT_ACN_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_MOBILE_UPDATED_API';
DELETE FROM DIGX_EP_ACT_EVT_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_MOBILE_UPDATED_API';
DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN ('HTH_851_MOBILE_API_EMAIL_en', 'HTH_851_MOBILE_API_EMAIL_zh-Hant', 'HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'HTH_851_MOBILE_API_SMS_en', 'HTH_851_MOBILE_API_SMS_zh-Hant', 'HTH_851_MOBILE_API_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_PM_EVENT_ALL_B WHERE EVENT_CODE='HTH_PROFILE_MOBILE_UPDATED_API';
INSERT INTO DIGX_PM_EVENT_ALL_B
 (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE, FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY,
 ACCT_DOMAIN_CATEGORY, ALERTS_FLAG, FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
 REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE, DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES ('HTH_PROFILE_MOBILE_UPDATED_API', 'HTH Profile MOBILE Update API', NULL, NULL, NULL, NULL, NULL, NULL, 'Y','N','N','N','N',NULL,'N','N',NULL,NULL,'N','N','N');
INSERT INTO DIGX_EP_ACT_EVT_B (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'HTH Profile MOBILE Update API', 'OTHER', 'ONLINE', 'CZ');
INSERT INTO DIGX_EP_ACT_EVT_ACN_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE, COD_DEC_ID, FLG_CONDITIONAL,
 COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
 NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE, ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'N', NULL, '0', 'N', '1', 'HTH Profile MOBILE Update API', USER, SYSDATE,
 USER, SYSDATE, 1, 0, 'N', DATE '2099-12-31', 'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_en', 'EMAIL', 'HTH 851 MOBILE API EMAIL en', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的 HTH API 用戶 #hthContactUserName# 已確認更新其流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'HTH_851_MOBILE_API_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_en', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_en', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_en', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_en', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hant', 'EMAIL', 'HTH 851 MOBILE API EMAIL zh-Hant', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的 HTH API 用戶 #hthContactUserName# 已確認更新其流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'HTH_851_MOBILE_API_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hant', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hant', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hant', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hant', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH 851 MOBILE API EMAIL zh-Hans-CN', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s HTH API user #hthContactUserName# has confirmed the update of his/her mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊贵的客户：</p><p>贵公司的 HTH API 用户 #hthContactUserName# 已确认更新其流动电话号码。</p><p>系统日期／时间：#hthContactApprovedAt#（香港时间）。</p><p>如有查询，请致电本行热线 (852) 2211 1321。</p><p>东亚银行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online (Host-to-host API): Confirmation of #hthContactUserName#''s Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_SMS_en', 'SMS', 'HTH 851 MOBILE API SMS en', 'BCOH2H-851', 'Your company has confirmed the update of mobile number of H2H API Profile. For details, please log into your account or call (852) 2211 1321.', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'HTH_851_MOBILE_API_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_SMS_zh-Hant', 'SMS', 'HTH 851 MOBILE API SMS zh-Hant', 'BCOH2H-851', '貴公司已確認更新 H2H API 用戶的流動電話號碼。詳情請登入您的賬戶或致電 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'HTH_851_MOBILE_API_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_API_SMS_zh-Hans-CN', 'SMS', 'HTH 851 MOBILE API SMS zh-Hans-CN', 'BCOH2H-851', '贵公司已确认更新 H2H API 用户的流动电话号码。详情请登入您的账户或致电 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_API', 'A', 'HTH_851_MOBILE_API_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

-- HTH_PROFILE_MOBILE_UPDATED_AP
DELETE FROM DIGX_EP_MSG_SRC_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_MOBILE_AP_EMAIL_en', 'HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'HTH_851_MOBILE_AP_SMS_en', 'HTH_851_MOBILE_AP_SMS_zh-Hant', 'HTH_851_MOBILE_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_MSG_ATTR_B WHERE COD_MESS_TMPL_ID IN ('HTH_851_MOBILE_AP_EMAIL_en', 'HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'HTH_851_MOBILE_AP_SMS_en', 'HTH_851_MOBILE_AP_SMS_zh-Hant', 'HTH_851_MOBILE_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_EP_EVT_REC_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_MOBILE_UPDATED_AP';
DELETE FROM DIGX_EP_ACT_EVT_ACN_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_MOBILE_UPDATED_AP';
DELETE FROM DIGX_EP_ACT_EVT_B WHERE COD_ACT_ID='com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update' AND COD_EVENT_ID='HTH_PROFILE_MOBILE_UPDATED_AP';
DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN ('HTH_851_MOBILE_AP_EMAIL_en', 'HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'HTH_851_MOBILE_AP_SMS_en', 'HTH_851_MOBILE_AP_SMS_zh-Hant', 'HTH_851_MOBILE_AP_SMS_zh-Hans-CN') AND DETERMINANT_VALUE='OBDX_BU';
DELETE FROM DIGX_PM_EVENT_ALL_B WHERE EVENT_CODE='HTH_PROFILE_MOBILE_UPDATED_AP';
INSERT INTO DIGX_PM_EVENT_ALL_B
 (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE, FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY,
 ACCT_DOMAIN_CATEGORY, ALERTS_FLAG, FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
 REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE, DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES ('HTH_PROFILE_MOBILE_UPDATED_AP', 'HTH Profile MOBILE Update AP', NULL, NULL, NULL, NULL, NULL, NULL, 'Y','N','N','N','N',NULL,'N','N',NULL,NULL,'N','N','N');
INSERT INTO DIGX_EP_ACT_EVT_B (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'HTH Profile MOBILE Update AP', 'OTHER', 'ONLINE', 'CZ');
INSERT INTO DIGX_EP_ACT_EVT_ACN_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE, COD_DEC_ID, FLG_CONDITIONAL,
 COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
 NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE, ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'N', NULL, '0', 'N', '1', 'HTH Profile MOBILE Update AP', USER, SYSDATE,
 USER, SYSDATE, 1, 0, 'N', DATE '2099-12-31', 'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_en', 'EMAIL', 'HTH 851 MOBILE AP EMAIL en', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的用戶 #hthContactUserName# 已確認更新其流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'HTH_851_MOBILE_AP_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_en', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_en', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_en', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_en', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'EMAIL', 'HTH 851 MOBILE AP EMAIL zh-Hant', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊貴的客戶：</p><p>貴公司的用戶 #hthContactUserName# 已確認更新其流動電話號碼。</p><p>系統日期／時間：#hthContactApprovedAt#（香港時間）。</p><p>如有查詢，請致電本行熱線 (852) 2211 1321。</p><p>東亞銀行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hant', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH 851 MOBILE AP EMAIL zh-Hans-CN', 'BCOH2H-851', '<p>Dear Customer,</p><p>Please note that your company''s user #hthContactUserName# has confirmed the update of his/her mobile phone number.</p><p>System Date/Time: #hthContactApprovedAt# HKT.</p><p>If you have any enquiries, please call our hotline on (852) 2211 1321.</p><p>Regards,<br>The Bank of East Asia, Limited</p><p>If there are any discrepancies between the English and Chinese versions of this email, the English version shall apply and prevail. This is a system-generated email. Please do not reply.</p><p>尊贵的客户：</p><p>贵公司的用户 #hthContactUserName# 已确认更新其流动电话号码。</p><p>系统日期／时间：#hthContactApprovedAt#（香港时间）。</p><p>如有查询，请致电本行热线 (852) 2211 1321。</p><p>东亚银行有限公司</p>', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', 'BEA Corporate Online: Confirmation of #hthContactUserName#''s Mobile Phone Number Update', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'hthContactUserName', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'hthContactUserName', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactUserName.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_ATTR_B (COD_MESS_TMPL_ID, COD_ATTR_ID, ATTR_MASK, DATA_ATTR_ORDER, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'D', NULL, 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_MSG_SRC_B (COD_MESS_TMPL_ID, COD_ATTR_ID, COD_ACT_ID, COD_SERVICE_ATTR_ID, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_EMAIL_zh-Hans-CN', 'hthContactApprovedAt', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update.hthContactApprovedAt.DTO', 'OBDX_BU');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_SMS_en', 'SMS', 'HTH 851 MOBILE AP SMS en', 'BCOH2H-851', 'Your company has confirmed the update of mobile number of H2H API Profile. For details, please log into your account or call (852) 2211 1321.', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'HTH_851_MOBILE_AP_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_SMS_zh-Hant', 'SMS', 'HTH 851 MOBILE AP SMS zh-Hant', 'BCOH2H-851', '貴公司已確認更新 H2H API 用戶的流動電話號碼。詳情請登入您的賬戶或致電 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'HTH_851_MOBILE_AP_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B
 (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE,
 LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_851_MOBILE_AP_SMS_zh-Hans-CN', 'SMS', 'HTH 851 MOBILE AP SMS zh-Hans-CN', 'BCOH2H-851', '贵公司已确认更新 H2H API 用户的流动电话号码。详情请登入您的账户或致电 (852) 2211 1321。', USER, SYSDATE,
 USER, SYSDATE, 1, 'A', '', 'CZ', 'OBDX_BU');
INSERT INTO DIGX_EP_EVT_REC_B
 (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL,
 SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.update', 'HTH_PROFILE_MOBILE_UPDATED_AP', 'A', 'HTH_851_MOBILE_AP_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

EXCEPTION

  WHEN OTHERS THEN

    ROLLBACK TO HTH_CONTACT_CONFIG;

    RAISE;

END;
