-- BCOH2H-849. Run using an account authorized to create HTH_BEA objects and maintain application config.
-- DDL auto-commits. This script never drops/truncates a table or overwrites BCO configuration.
SET DEFINE OFF;
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS';
  IF n=0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE HTH_BEA.HTH_MTB_EVENT_DETAILS (
      EVENT_ID VARCHAR2(36 CHAR) NOT NULL,
      EVENT_DTE VARCHAR2(8 CHAR) NOT NULL,
      EVENT_TIME VARCHAR2(6 CHAR) NOT NULL,
      SOURCE_SYSTEM VARCHAR2(16 CHAR) NOT NULL,
      CHANNEL_TYPE VARCHAR2(16 CHAR) NOT NULL,
      TARGET_USER_CHANNEL VARCHAR2(16 CHAR),
      ACTIVITY_KEY VARCHAR2(64 CHAR) NOT NULL,
      EVENT_ACTV_TYPE_CODE VARCHAR2(64 CHAR),
      EVENT_STATUS_CODE VARCHAR2(16 CHAR) NOT NULL,
      PHASE VARCHAR2(32 CHAR) NOT NULL,
      FIN_IND VARCHAR2(1 CHAR) NOT NULL,
      USER_ID VARCHAR2(256 CHAR),
      TARGET_USER_ID VARCHAR2(256 CHAR),
      ACCT_NBR VARCHAR2(64 CHAR),
      RELATIONSHIP_TYPE VARCHAR2(32 CHAR),
      SERVICE_ID VARCHAR2(256 CHAR) NOT NULL,
      TASK_CODE VARCHAR2(100 CHAR),
      SOURCE_TRX_REF_NBR VARCHAR2(128 CHAR),
      SOURCE_ACTION_ID VARCHAR2(128 CHAR),
      REQUEST_ID VARCHAR2(128 CHAR),
      IP_ADDRESS VARCHAR2(64 CHAR),
      ERROR_CODE VARCHAR2(100 CHAR),
      DEDUP_KEY VARCHAR2(64 CHAR),
      CREATED_AT TIMESTAMP(6) NOT NULL,
      CONSTRAINT PK_HTH_MTB_EVENT PRIMARY KEY (EVENT_ID)
    )~';
  END IF;
END;
/
-- Verify existing structure before proceeding; never silently accept a different schema.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='EVENT_ID' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=36 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column EVENT_ID'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='EVENT_DTE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=8 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column EVENT_DTE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='EVENT_TIME' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=6 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column EVENT_TIME'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='SOURCE_SYSTEM' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=16 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column SOURCE_SYSTEM'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='CHANNEL_TYPE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=16 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column CHANNEL_TYPE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='TARGET_USER_CHANNEL' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=16 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column TARGET_USER_CHANNEL'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='ACTIVITY_KEY' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=64 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column ACTIVITY_KEY'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='EVENT_ACTV_TYPE_CODE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=64 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column EVENT_ACTV_TYPE_CODE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='EVENT_STATUS_CODE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=16 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column EVENT_STATUS_CODE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='PHASE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=32 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column PHASE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='FIN_IND' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=1 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column FIN_IND'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='USER_ID' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=256 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column USER_ID'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='TARGET_USER_ID' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=256 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column TARGET_USER_ID'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='ACCT_NBR' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=64 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column ACCT_NBR'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='RELATIONSHIP_TYPE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=32 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column RELATIONSHIP_TYPE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='SERVICE_ID' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=256 AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column SERVICE_ID'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='TASK_CODE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=100 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column TASK_CODE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='SOURCE_TRX_REF_NBR' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=128 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column SOURCE_TRX_REF_NBR'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='SOURCE_ACTION_ID' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=128 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column SOURCE_ACTION_ID'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='REQUEST_ID' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=128 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column REQUEST_ID'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='IP_ADDRESS' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=64 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column IP_ADDRESS'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='ERROR_CODE' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=100 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column ERROR_CODE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='DEDUP_KEY' AND DATA_TYPE='VARCHAR2' AND CHAR_USED='C' AND CHAR_LENGTH=64 AND NULLABLE='Y';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible column DEDUP_KEY'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND COLUMN_NAME='CREATED_AT' AND DATA_TYPE='TIMESTAMP(6)' AND NULLABLE='N';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible CREATED_AT'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_CONSTRAINTS c JOIN ALL_CONS_COLUMNS x ON x.OWNER=c.OWNER AND x.CONSTRAINT_NAME=c.CONSTRAINT_NAME
    WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND c.CONSTRAINT_TYPE='P' AND c.STATUS='ENABLED' AND x.COLUMN_NAME='EVENT_ID'
    AND 1=(SELECT COUNT(*) FROM ALL_CONS_COLUMNS z WHERE z.OWNER=c.OWNER AND z.CONSTRAINT_NAME=c.CONSTRAINT_NAME);
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible primary key'); END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER='HTH_BEA' AND INDEX_NAME='UX_HTH_MTB_DEDUP';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX HTH_BEA.UX_HTH_MTB_DEDUP ON HTH_BEA.HTH_MTB_EVENT_DETAILS (DEDUP_KEY)'; END IF;
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER='HTH_BEA' AND INDEX_NAME='UX_HTH_MTB_DEDUP' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND UNIQUENESS='UNIQUE' AND STATUS='VALID';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index UX_HTH_MTB_DEDUP'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='UX_HTH_MTB_DEDUP';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index columns UX_HTH_MTB_DEDUP'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='UX_HTH_MTB_DEDUP' AND COLUMN_POSITION=1 AND COLUMN_NAME='DEDUP_KEY';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index order UX_HTH_MTB_DEDUP'); END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_DATE_ACT';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX HTH_BEA.IX_HTH_MTB_DATE_ACT ON HTH_BEA.HTH_MTB_EVENT_DETAILS (EVENT_DTE,ACTIVITY_KEY)'; END IF;
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_DATE_ACT' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND UNIQUENESS='NONUNIQUE' AND STATUS='VALID';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index IX_HTH_MTB_DATE_ACT'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_DATE_ACT';
  IF n<>2 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index columns IX_HTH_MTB_DATE_ACT'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_DATE_ACT' AND COLUMN_POSITION=1 AND COLUMN_NAME='EVENT_DTE';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index order IX_HTH_MTB_DATE_ACT'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_DATE_ACT' AND COLUMN_POSITION=2 AND COLUMN_NAME='ACTIVITY_KEY';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index order IX_HTH_MTB_DATE_ACT'); END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_SOURCE';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX HTH_BEA.IX_HTH_MTB_SOURCE ON HTH_BEA.HTH_MTB_EVENT_DETAILS (SOURCE_TRX_REF_NBR)'; END IF;
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_SOURCE' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' AND UNIQUENESS='NONUNIQUE' AND STATUS='VALID';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index IX_HTH_MTB_SOURCE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_SOURCE';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index columns IX_HTH_MTB_SOURCE'); END IF;
  SELECT COUNT(*) INTO n FROM ALL_IND_COLUMNS WHERE INDEX_OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_MTB_SOURCE' AND COLUMN_POSITION=1 AND COLUMN_NAME='SOURCE_TRX_REF_NBR';
  IF n<>1 THEN RAISE_APPLICATION_ERROR(-20849,'849 incompatible index order IX_HTH_MTB_SOURCE'); END IF;
END;
/
-- Cross-module Adapter; only this HTH factory key is inserted/updated.
MERGE INTO DIGX_FW_CONFIG_ALL_O t
USING (SELECT 'AdapterFactories' preference_name, 'HTH_MTB_ADAPTER_FACTORY' prop_id,
 'com.ofss.digx.cz.bea.app.hosttohost.crm.HthCRMAdapterFactory' prop_value, 'N' determinant_value FROM dual) s
ON (t.PREFERENCE_NAME=s.preference_name AND t.PROP_ID=s.prop_id AND t.DETERMINANT_VALUE=s.determinant_value)
WHEN MATCHED THEN UPDATE SET t.PROP_VALUE=s.prop_value, t.LAST_UPDATED_BY='ofssuser', t.LAST_UPDATED_DATE=SYSDATE
 WHERE t.PROP_VALUE<>s.prop_value OR t.PROP_VALUE IS NULL
WHEN NOT MATCHED THEN INSERT (PREFERENCE_NAME,PROP_ID,PROP_VALUE,DETERMINANT_VALUE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE)
VALUES (s.preference_name,s.prop_id,s.prop_value,s.determinant_value,'ofssuser',SYSDATE,'ofssuser',SYSDATE);
-- Preserve existing enabled flag and all operator mappings on re-run. No invented external codes.
MERGE INTO DIGX_FW_CONFIG_ALL_O t
USING (SELECT 'HTHMtbConfiguration' preference_name, 'ENABLED' prop_id, 'N' prop_value, 'N' determinant_value FROM dual) s
ON (t.PREFERENCE_NAME=s.preference_name AND t.PROP_ID=s.prop_id AND t.DETERMINANT_VALUE=s.determinant_value)
WHEN NOT MATCHED THEN INSERT (PREFERENCE_NAME,PROP_ID,PROP_VALUE,DETERMINANT_VALUE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE)
VALUES (s.preference_name,s.prop_id,s.prop_value,s.determinant_value,'ofssuser',SYSDATE,'ofssuser',SYSDATE);
COMMIT;
-- Enable explicitly only after runtime transaction and permission tests:
-- UPDATE DIGX_FW_CONFIG_ALL_O SET PROP_VALUE='Y' WHERE PREFERENCE_NAME='HTHMtbConfiguration' AND PROP_ID='ENABLED' AND DETERMINANT_VALUE='N';
-- Grant SELECT/INSERT on HTH_BEA.HTH_MTB_EVENT_DETAILS to the actual application NONXA datasource user if different.
-- Do not grant to PUBLIC; resolve the real datasource account with the environment owner.
