-- Read-only, no BCO changes.
SELECT PROP_ID, PROP_VALUE, DETERMINANT_VALUE FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='HTHMtbConfiguration' ORDER BY PROP_ID;
SELECT COLUMN_NAME, DATA_TYPE, CHAR_LENGTH, NULLABLE FROM ALL_TAB_COLUMNS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' ORDER BY COLUMN_ID;
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_TRX_REF_NBR, CREATED_AT FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE CREATED_AT >= TO_TIMESTAMP(:from_time,'YYYY-MM-DD HH24:MI:SS')
  AND CREATED_AT < TO_TIMESTAMP(:to_time,'YYYY-MM-DD HH24:MI:SS')
ORDER BY CREATED_AT DESC, EVENT_ID DESC;
SELECT DEDUP_KEY, COUNT(*) FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE DEDUP_KEY IS NOT NULL GROUP BY DEDUP_KEY HAVING COUNT(*)>1;
-- Existing BCO reference configuration, do not update:
SELECT PROP_ID, PROP_VALUE FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='CRMConfiguration'
AND (PROP_ID LIKE '%UAT_N_RA%' OR PROP_ID LIKE '%LAT_N_CA%' OR PROP_ID LIKE '%LAT_N_UA%' OR PROP_ID LIKE '%LAT_N_DA%')
ORDER BY PROP_ID;
