-- Read-only. Execute each complete SELECT separately; no required bind parameters.
-- Defaults to the last 24 hours in Hong Kong time, matching CREATED_AT storage.
-- For another interval replace the two WHERE expressions with TIMESTAMP literals.
-- No BCO changes.
SELECT PROP_ID, PROP_VALUE, DETERMINANT_VALUE FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='HTHMtbConfiguration' ORDER BY PROP_ID;
SELECT COLUMN_NAME, DATA_TYPE, CHAR_LENGTH, NULLABLE FROM ALL_TAB_COLUMNS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' ORDER BY COLUMN_ID;
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_TRX_REF_NBR, CREATED_AT FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE CREATED_AT >= CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP) - INTERVAL '1' DAY
  AND CREATED_AT < CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP)
ORDER BY CREATED_AT DESC, EVENT_ID DESC;
SELECT DEDUP_KEY, COUNT(*) FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE DEDUP_KEY IS NOT NULL GROUP BY DEDUP_KEY HAVING COUNT(*)>1;
-- Existing BCO reference configuration, do not update:
SELECT PROP_ID, PROP_VALUE FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='CRMConfiguration'
AND (PROP_ID LIKE '%UAT_N_RA%' OR PROP_ID LIKE '%LAT_N_CA%' OR PROP_ID LIKE '%LAT_N_UA%' OR PROP_ID LIKE '%LAT_N_DA%')
ORDER BY PROP_ID;

-- HTH cross-module factory; no BCO factory keys changed.
SELECT PREFERENCE_NAME, PROP_ID, PROP_VALUE, DETERMINANT_VALUE
FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='AdapterFactories' AND PROP_ID='HTH_MTB_ADAPTER_FACTORY';
