-- Run on the HTH_BEA connection. Read-only; execute each SELECT separately.
-- Default data interval: last 24 hours in Hong Kong time.
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, CHAR_LENGTH, CHAR_USED, NULLABLE FROM ALL_TAB_COLUMNS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' ORDER BY COLUMN_ID;
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_TRX_REF_NBR, CREATED_AT FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE CREATED_AT >= CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP) - INTERVAL '1' DAY
  AND CREATED_AT < CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP)
ORDER BY CREATED_AT DESC, EVENT_ID DESC;
SELECT DEDUP_KEY, COUNT(*) FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE DEDUP_KEY IS NOT NULL GROUP BY DEDUP_KEY HAVING COUNT(*)>1;

-- Existing historical rows may have no values for metadata introduced by 849.
-- Do not backfill ACTIVITY_KEY/PHASE/CREATED_AT with invented business values.
SELECT COUNT(*) AS TOTAL_ROWS,
       COUNT(CREATED_AT) AS ROWS_WITH_CREATED_AT,
       COUNT(ACTIVITY_KEY) AS ROWS_WITH_ACTIVITY_KEY
FROM HTH_BEA.HTH_MTB_EVENT_DETAILS;
