-- BCOH2H-849: run on HTH_BEA. Read-only; execute SELECTs separately or as a script.
-- This verifies only HTH_CRM_EVENT_DETAILS. Old MTB tables are not dependencies.
-- PASS metadata is not proof of runtime delivery; correlate new events with HTH_CRM WRITE logs.
-- If TABLE_CHECK is FAIL, run script 1 first. Subsequent data SELECTs require the new table.
SELECT SYS_CONTEXT('USERENV','DB_NAME') AS DATABASE_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','SESSION_USER') AS LOGIN_USER
FROM DUAL;

SELECT 'HTH_BEA.HTH_CRM_EVENT_DETAILS' AS TARGET_TABLE,
       CASE WHEN COUNT(*)=1 THEN 'PASS' ELSE 'FAIL: table missing or inaccessible' END AS TABLE_CHECK
FROM ALL_TABLES WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS';

-- Always return all 113 expected columns, including missing ones.
-- Matches installer capacity/nullability checks; actual definitions remain visible for review.
WITH expected_columns AS (
  SELECT 'EVENT_ID' column_name, 'VARCHAR2' column_type, 36 column_length, 'N' column_nullable, 'Unique event identifier generated by the HTH CRM collector.' expected_comment FROM DUAL
  UNION ALL SELECT 'RECORD_TYPE', 'VARCHAR2', 16, 'Y', 'CRM record type from the existing BCO CRM configuration; null when not configured.' FROM DUAL
  UNION ALL SELECT 'FILLER_01', 'VARCHAR2', 64, 'Y', 'CRM filler value from the existing BCO CRM configuration; null when not configured.' FROM DUAL
  UNION ALL SELECT 'EVENT_DTE', 'VARCHAR2', 8, 'N', 'Event date in Asia/Hong_Kong time, formatted as yyyyMMdd.' FROM DUAL
  UNION ALL SELECT 'EVENT_TIME', 'VARCHAR2', 6, 'N', 'Event time in Asia/Hong_Kong time, formatted as HHmmss.' FROM DUAL
  UNION ALL SELECT 'CHNL_ID', 'VARCHAR2', 64, 'Y', 'BCO CRM channel identifier from Login-Channel and CRM configuration; distinct from the CM/BM portal.' FROM DUAL
  UNION ALL SELECT 'CHNL_TYPE_CODE', 'VARCHAR2', 32, 'Y', 'BCO CRM channel type code from the existing CRM configuration; null when not configured.' FROM DUAL
  UNION ALL SELECT 'EVENT_STATUS_CODE', 'VARCHAR2', 16, 'N', 'Operation-stage result: A for success or submission accepted for approval; R for failure or business rollback.' FROM DUAL
  UNION ALL SELECT 'CR_DR_IND', 'VARCHAR2', 1, 'Y', 'Credit or debit indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FEE_CHRG_CODE', 'VARCHAR2', 32, 'Y', 'Fee charge classification from the existing BCO CRM configuration; no fee is generated by this record.' FROM DUAL
  UNION ALL SELECT 'EVENT_ACTV_TYPE_CODE', 'VARCHAR2', 64, 'Y', 'External CRM activity code from ACTIVITY_<ACTIVITY_KEY> configuration; null when not configured.' FROM DUAL
  UNION ALL SELECT 'FIN_IND', 'VARCHAR2', 1, 'N', 'Financial indicator; N for the non-financial CM/BM onboarding operations in this release.' FROM DUAL
  UNION ALL SELECT 'SELF_SRV_IND', 'VARCHAR2', 1, 'Y', 'BCO self-service indicator derived from the platform isAdmin context; null when unknown.' FROM DUAL
  UNION ALL SELECT 'USER_ID', 'VARCHAR2', 256, 'Y', 'User who performed this operation or approval action.' FROM DUAL
  UNION ALL SELECT 'EVENT_COUNTRY_CODE', 'VARCHAR2', 8, 'Y', 'CRM event country code from the existing BCO CRM configuration; null when not configured.' FROM DUAL
  UNION ALL SELECT 'ACCT_NBR', 'VARCHAR2', 64, 'Y', 'Corporate party identifier for the maintenance operation; not an individual bank account number.' FROM DUAL
  UNION ALL SELECT 'PHONE_NBR', 'VARCHAR2', 20, 'Y', 'Phone proxy number from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PHONE_NBR_ACCT_NBR', 'VARCHAR2', 20, 'Y', 'Account linked to the phone proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PHONE_NBR_REQ_RESULT', 'VARCHAR2', 16, 'Y', 'Phone proxy request result from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PHONE_DEFAULT_IND', 'VARCHAR2', 1, 'Y', 'Default phone proxy indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD', 'VARCHAR2', 50, 'Y', 'Electronic-address proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD_ACCT_NBR', 'VARCHAR2', 20, 'Y', 'Account linked to the electronic-address proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD_REQ_RESULT', 'VARCHAR2', 16, 'Y', 'Electronic-address proxy request result from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD_DEFAULT_IND', 'VARCHAR2', 1, 'Y', 'Default electronic-address proxy indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FPS_ID', 'VARCHAR2', 20, 'Y', 'FPS proxy identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FPS_ACCT_NBR', 'VARCHAR2', 20, 'Y', 'Account linked to the FPS proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FPS_REQ_RESULT', 'VARCHAR2', 16, 'Y', 'FPS proxy request result from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DEBIT_ACCT_NBR', 'VARCHAR2', 20, 'Y', 'Debit account number from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'EVENT_CCY_CODE', 'VARCHAR2', 3, 'Y', 'Event currency code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'EVENT_AMT', 'NUMBER', NULL, 'Y', 'Event amount from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FEE_CHRG_AMT', 'NUMBER', NULL, 'Y', 'Fee charged amount from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FEE_CCY_CODE', 'VARCHAR2', 3, 'Y', 'Fee currency code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'TRF_DTE', 'VARCHAR2', 8, 'Y', 'Transfer date from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'TRF_FREQ', 'VARCHAR2', 32, 'Y', 'Transfer frequency from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PROXY_ID_TYPE', 'VARCHAR2', 32, 'Y', 'Payment proxy identifier type from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PROXY_ID', 'VARCHAR2', 34, 'Y', 'Payment proxy identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PAYEE_NAME', 'VARCHAR2', 50, 'Y', 'Payee name from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PAYEE_BANK_CODE', 'VARCHAR2', 3, 'Y', 'Payee bank code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'EVENT_REM', 'VARCHAR2', 40, 'Y', 'BCO-style event reference remark, limited to 40 characters; the full HTH reference remains in SOURCE_TRX_REF_NBR.' FROM DUAL
  UNION ALL SELECT 'REF_NBR', 'VARCHAR2', 9, 'Y', 'BCO numeric-format reference number from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FROM_DTE', 'VARCHAR2', 8, 'Y', 'Period start date from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'TO_DTE', 'VARCHAR2', 8, 'Y', 'Period end date from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'MANDATE_ID', 'VARCHAR2', 128, 'Y', 'Direct-debit mandate identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'EDDA_MAINT_ACTION', 'VARCHAR2', 32, 'Y', 'Electronic direct-debit maintenance action from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'SOURCE_TRX_REF_NBR', 'VARCHAR2', 128, 'Y', 'Approval transaction reference or business response reference used to correlate the event.' FROM DUAL
  UNION ALL SELECT 'PAY_CAT_PURP_CODE', 'VARCHAR2', 6, 'Y', 'Payment category purpose code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'PAY_PURP_CODE', 'VARCHAR2', 6, 'Y', 'Payment purpose code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DEVICE_ID', 'VARCHAR2', 256, 'Y', 'Device identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'MOBILE_BRAND', 'VARCHAR2', 128, 'Y', 'Operating-system label parsed from the user agent, following the BCO field convention; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'PLATFORM_CODE', 'VARCHAR2', 64, 'Y', 'Client platform code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DEVICE_MODEL', 'VARCHAR2', 128, 'Y', 'Browser brand parsed from the user agent, following the BCO field convention; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'DEVICE_OS_VERSION', 'VARCHAR2', 128, 'Y', 'Browser version parsed from the user agent, following the BCO field convention; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'IP_ADDRESS', 'VARCHAR2', 64, 'Y', 'Client IP address supplied by the platform operation context, when available.' FROM DUAL
  UNION ALL SELECT 'FILLER_02', 'VARCHAR2', 3, 'Y', 'Secondary CRM filler from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'EVENT_AMT_HKE', 'NUMBER', NULL, 'Y', 'Event amount in Hong Kong dollar equivalent from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'EVENT_EX_RATE', 'NUMBER', NULL, 'Y', 'Event exchange rate from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'MRCH_ID', 'VARCHAR2', 128, 'Y', 'Merchant identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ACCT_CCY_CODE', 'VARCHAR2', 3, 'Y', 'Account currency code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ACCT_AMT', 'NUMBER', NULL, 'Y', 'Account-currency amount from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'SCREEN_ID', 'VARCHAR2', 64, 'Y', 'BCO screen identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'OMB_FLAG', 'VARCHAR2', 1, 'Y', 'One-Man-Bank approval indicator: Y for affirmative CM user/access context; null when unknown or not applicable.' FROM DUAL
  UNION ALL SELECT 'MULTI_APP_REJ_TXN_CNT', 'VARCHAR2', 32, 'Y', 'Count of transactions in a multiple-approval or rejection action from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'COUPON_CODE', 'VARCHAR2', 64, 'Y', 'Coupon code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ACTL_INT_RATE', 'VARCHAR2', 64, 'Y', 'Actual interest rate from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'TT_AUTO_ROUTE', 'VARCHAR2', 1, 'Y', 'BCO CRM automatic-routing default N for these non-financial HTH maintenance events.' FROM DUAL
  UNION ALL SELECT 'SUSPICIOUS_ACTIVITY', 'VARCHAR2', 128, 'Y', 'Suspicious activity classification from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'SUSPICIOUS_IND', 'VARCHAR2', 1, 'Y', 'Suspicious activity indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'WITH_MRCH', 'VARCHAR2', 1, 'Y', 'Merchant-presence indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'CMPY_NAME', 'VARCHAR2', 256, 'Y', 'Merchant company name from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DOC_ID', 'VARCHAR2', 128, 'Y', 'Document identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DOC_TYPE', 'VARCHAR2', 32, 'Y', 'Document type from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DOC_COUNTRY_CODE', 'VARCHAR2', 8, 'Y', 'Document issuing country code from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'MRCH_USER_ID', 'VARCHAR2', 256, 'Y', 'Merchant user identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'MRCH_USER_NAME', 'VARCHAR2', 256, 'Y', 'Merchant user name from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DOC_CMPY_NAME', 'VARCHAR2', 256, 'Y', 'Company name on a document from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'DOC_ACCT_NBR', 'VARCHAR2', 64, 'Y', 'Account number on a document from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'SLE_MRCH_NAME', 'VARCHAR2', 256, 'Y', 'SLE merchant name from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'FORMAT', 'VARCHAR2', 32, 'Y', 'Advice or document format from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'TXN_COUNT', 'VARCHAR2', 32, 'Y', 'Transaction count from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ADV_FREQ_TYPE', 'VARCHAR2', 32, 'Y', 'Advice frequency type from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'ADV_TYPE', 'VARCHAR2', 32, 'Y', 'Advice type from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'SLE_MRCH_ID', 'VARCHAR2', 128, 'Y', 'SLE merchant identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'AR_TOKEN', 'VARCHAR2', 256, 'Y', 'AR token from the BCO model; reserved and always null in HTH because token values are not collected.' FROM DUAL
  UNION ALL SELECT 'TREASURY_REF', 'VARCHAR2', 128, 'Y', 'Treasury reference from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_SWEEP_INSTRUCTION_TYPE', 'VARCHAR2', 64, 'Y', 'Liquidity-management sweep instruction type from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_FREQUENCY_EXECUTIONDAY', 'VARCHAR2', 64, 'Y', 'Liquidity-management frequency or execution day from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_EFFECTIVEDATE', 'VARCHAR2', 32, 'Y', 'Liquidity-management effective date from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_RULE_SETUPDATE', 'VARCHAR2', 32, 'Y', 'Liquidity-management rule setup date from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_SWEEPING_AMOUNT_THRESHOLD', 'VARCHAR2', 128, 'Y', 'Liquidity-management sweep amount or threshold from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_FPXTXN_NBR', 'VARCHAR2', 128, 'Y', 'Liquidity-management FPX transaction number from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'LM_INSTRUCTION_NBR', 'VARCHAR2', 128, 'Y', 'Liquidity-management instruction number from the BCO model; reserved and null for current HTH CM/BM onboarding events.' FROM DUAL
  UNION ALL SELECT 'USER_ROLE', 'VARCHAR2', 32, 'Y', 'Platform user role from the approved request metadata field; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'TOKEN_ID', 'VARCHAR2', 256, 'Y', 'Authentication token identifier from the BCO model; reserved and always null in HTH because token values are not collected.' FROM DUAL
  UNION ALL SELECT 'ERR_CODE', 'VARCHAR2', 20, 'Y', 'BCO-model error code: first approval-processing code or TFA context code, keeping the last 20 characters; distinct from HTH ERROR_CODE.' FROM DUAL
  UNION ALL SELECT 'BIO_TYPE', 'VARCHAR2', 32, 'Y', 'Biometric authentication type from the approved platform metadata field; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'REG_METHOD', 'VARCHAR2', 64, 'Y', 'Registration method from the approved platform metadata field; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'AUTH_METHOD', 'VARCHAR2', 64, 'Y', 'Authentication method from the approved platform metadata field; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'LANG', 'VARCHAR2', 2, 'Y', 'BCO CRM language code: en, sc or tc, derived from the active locale.' FROM DUAL
  UNION ALL SELECT 'APP_VERSION', 'VARCHAR2', 64, 'Y', 'Client application version from the approved platform metadata field; null when unavailable.' FROM DUAL
  UNION ALL SELECT 'SOURCE_SYSTEM', 'VARCHAR2', 16, 'N', 'Source system identifier; current HTH collector writes HTH.' FROM DUAL
  UNION ALL SELECT 'CHANNEL_TYPE', 'VARCHAR2', 16, 'N', 'Originating portal: CM for customer management, BM for bank management.' FROM DUAL
  UNION ALL SELECT 'TARGET_USER_CHANNEL', 'VARCHAR2', 16, 'Y', 'Target user channel HTH; null for company-level operations.' FROM DUAL
  UNION ALL SELECT 'ACTIVITY_KEY', 'VARCHAR2', 64, 'N', 'Internal HTH operation, such as ACCESS_CREATE, ACCESS_EDIT or PASSWORD_SETUP.' FROM DUAL
  UNION ALL SELECT 'PHASE', 'VARCHAR2', 32, 'N', 'Recorded stage: SUBMIT, APPLY, GENERATE, EXECUTE, APPROVAL_APPROVE, APPROVAL_REJECT or APPROVAL_ACTION.' FROM DUAL
  UNION ALL SELECT 'TARGET_USER_ID', 'VARCHAR2', 256, 'Y', 'User affected by the operation; null for company-level operations.' FROM DUAL
  UNION ALL SELECT 'RELATIONSHIP_TYPE', 'VARCHAR2', 32, 'Y', 'Account/service access relationship type supplied by the operation, such as Related or Associated.' FROM DUAL
  UNION ALL SELECT 'SERVICE_ID', 'VARCHAR2', 256, 'N', 'Application service identifier that produced the HTH CRM event.' FROM DUAL
  UNION ALL SELECT 'TASK_CODE', 'VARCHAR2', 100, 'Y', 'Platform task identifier captured from the operation context when available.' FROM DUAL
  UNION ALL SELECT 'SOURCE_ACTION_ID', 'VARCHAR2', 128, 'Y', 'Stable identifier for a specific action, when supplied; distinct from the transaction reference.' FROM DUAL
  UNION ALL SELECT 'REQUEST_ID', 'VARCHAR2', 128, 'Y', 'Request identifier supplied by the operation, when available.' FROM DUAL
  UNION ALL SELECT 'ERROR_CODE', 'VARCHAR2', 100, 'Y', 'Sanitized application error code; BUSINESS_ROLLBACK denotes a rolled-back business transaction.' FROM DUAL
  UNION ALL SELECT 'DEDUP_KEY', 'VARCHAR2', 64, 'Y', 'SHA-256 event deduplication key when a reliable action identifier is available; otherwise null.' FROM DUAL
  UNION ALL SELECT 'CREATED_AT', 'TIMESTAMP', NULL, 'N', 'Record write time in Asia/Hong_Kong time; null for legacy rows without this metadata.' FROM DUAL
)
SELECT s.column_name, c.DATA_TYPE, c.CHAR_LENGTH, c.CHAR_USED, c.DATA_PRECISION, c.DATA_SCALE, c.NULLABLE,
       CASE WHEN c.COLUMN_NAME IS NULL THEN 'FAIL: missing column'
            WHEN c.VIRTUAL_COLUMN='YES' OR c.IDENTITY_COLUMN='YES' THEN 'FAIL: generated column'
            WHEN s.column_type='TIMESTAMP' AND
                 (c.DATA_TYPE NOT LIKE 'TIMESTAMP(%)' OR NVL(c.DATA_SCALE,0)<6) THEN 'FAIL: expected TIMESTAMP(6)'
            WHEN s.column_type='NUMBER' AND
                 (c.DATA_TYPE<>'NUMBER' OR c.DATA_PRECISION IS NOT NULL OR c.DATA_SCALE IS NOT NULL)
              THEN 'FAIL: expected unrestricted NUMBER'
            WHEN s.column_type='VARCHAR2' AND
                 (c.DATA_TYPE<>'VARCHAR2' OR NVL(c.CHAR_USED,'?')<>'C' OR c.CHAR_LENGTH<s.column_length)
              THEN 'FAIL: expected sufficient VARCHAR2 CHAR capacity'
            WHEN s.column_nullable='Y' AND c.NULLABLE='N' THEN 'FAIL: must allow NULL'
            ELSE 'PASS' END AS DEFINITION_CHECK,
       CASE WHEN d.COMMENTS=s.expected_comment THEN 'PASS'
            WHEN TRIM(d.COMMENTS) IS NULL THEN 'FAIL: missing comment'
            ELSE 'FAIL: comment differs from release definition' END AS COMMENT_CHECK,
       d.COMMENTS
FROM expected_columns s LEFT JOIN ALL_TAB_COLS c
  ON c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_CRM_EVENT_DETAILS' AND c.COLUMN_NAME=s.column_name
LEFT JOIN ALL_COL_COMMENTS d
  ON d.OWNER=c.OWNER AND d.TABLE_NAME=c.TABLE_NAME AND d.COLUMN_NAME=c.COLUMN_NAME
ORDER BY s.column_name;

-- An extra required column can reject application INSERTs even when the 113 columns pass.
WITH expected_columns AS (
  SELECT 'EVENT_ID' column_name FROM DUAL
  UNION ALL SELECT 'RECORD_TYPE' FROM DUAL
  UNION ALL SELECT 'FILLER_01' FROM DUAL
  UNION ALL SELECT 'EVENT_DTE' FROM DUAL
  UNION ALL SELECT 'EVENT_TIME' FROM DUAL
  UNION ALL SELECT 'CHNL_ID' FROM DUAL
  UNION ALL SELECT 'CHNL_TYPE_CODE' FROM DUAL
  UNION ALL SELECT 'EVENT_STATUS_CODE' FROM DUAL
  UNION ALL SELECT 'CR_DR_IND' FROM DUAL
  UNION ALL SELECT 'FEE_CHRG_CODE' FROM DUAL
  UNION ALL SELECT 'EVENT_ACTV_TYPE_CODE' FROM DUAL
  UNION ALL SELECT 'FIN_IND' FROM DUAL
  UNION ALL SELECT 'SELF_SRV_IND' FROM DUAL
  UNION ALL SELECT 'USER_ID' FROM DUAL
  UNION ALL SELECT 'EVENT_COUNTRY_CODE' FROM DUAL
  UNION ALL SELECT 'ACCT_NBR' FROM DUAL
  UNION ALL SELECT 'PHONE_NBR' FROM DUAL
  UNION ALL SELECT 'PHONE_NBR_ACCT_NBR' FROM DUAL
  UNION ALL SELECT 'PHONE_NBR_REQ_RESULT' FROM DUAL
  UNION ALL SELECT 'PHONE_DEFAULT_IND' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD_ACCT_NBR' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD_REQ_RESULT' FROM DUAL
  UNION ALL SELECT 'ELECT_ADD_DEFAULT_IND' FROM DUAL
  UNION ALL SELECT 'FPS_ID' FROM DUAL
  UNION ALL SELECT 'FPS_ACCT_NBR' FROM DUAL
  UNION ALL SELECT 'FPS_REQ_RESULT' FROM DUAL
  UNION ALL SELECT 'DEBIT_ACCT_NBR' FROM DUAL
  UNION ALL SELECT 'EVENT_CCY_CODE' FROM DUAL
  UNION ALL SELECT 'EVENT_AMT' FROM DUAL
  UNION ALL SELECT 'FEE_CHRG_AMT' FROM DUAL
  UNION ALL SELECT 'FEE_CCY_CODE' FROM DUAL
  UNION ALL SELECT 'TRF_DTE' FROM DUAL
  UNION ALL SELECT 'TRF_FREQ' FROM DUAL
  UNION ALL SELECT 'PROXY_ID_TYPE' FROM DUAL
  UNION ALL SELECT 'PROXY_ID' FROM DUAL
  UNION ALL SELECT 'PAYEE_NAME' FROM DUAL
  UNION ALL SELECT 'PAYEE_BANK_CODE' FROM DUAL
  UNION ALL SELECT 'EVENT_REM' FROM DUAL
  UNION ALL SELECT 'REF_NBR' FROM DUAL
  UNION ALL SELECT 'FROM_DTE' FROM DUAL
  UNION ALL SELECT 'TO_DTE' FROM DUAL
  UNION ALL SELECT 'MANDATE_ID' FROM DUAL
  UNION ALL SELECT 'EDDA_MAINT_ACTION' FROM DUAL
  UNION ALL SELECT 'SOURCE_TRX_REF_NBR' FROM DUAL
  UNION ALL SELECT 'PAY_CAT_PURP_CODE' FROM DUAL
  UNION ALL SELECT 'PAY_PURP_CODE' FROM DUAL
  UNION ALL SELECT 'DEVICE_ID' FROM DUAL
  UNION ALL SELECT 'MOBILE_BRAND' FROM DUAL
  UNION ALL SELECT 'PLATFORM_CODE' FROM DUAL
  UNION ALL SELECT 'DEVICE_MODEL' FROM DUAL
  UNION ALL SELECT 'DEVICE_OS_VERSION' FROM DUAL
  UNION ALL SELECT 'IP_ADDRESS' FROM DUAL
  UNION ALL SELECT 'FILLER_02' FROM DUAL
  UNION ALL SELECT 'EVENT_AMT_HKE' FROM DUAL
  UNION ALL SELECT 'EVENT_EX_RATE' FROM DUAL
  UNION ALL SELECT 'MRCH_ID' FROM DUAL
  UNION ALL SELECT 'ACCT_CCY_CODE' FROM DUAL
  UNION ALL SELECT 'ACCT_AMT' FROM DUAL
  UNION ALL SELECT 'SCREEN_ID' FROM DUAL
  UNION ALL SELECT 'OMB_FLAG' FROM DUAL
  UNION ALL SELECT 'MULTI_APP_REJ_TXN_CNT' FROM DUAL
  UNION ALL SELECT 'COUPON_CODE' FROM DUAL
  UNION ALL SELECT 'ACTL_INT_RATE' FROM DUAL
  UNION ALL SELECT 'TT_AUTO_ROUTE' FROM DUAL
  UNION ALL SELECT 'SUSPICIOUS_ACTIVITY' FROM DUAL
  UNION ALL SELECT 'SUSPICIOUS_IND' FROM DUAL
  UNION ALL SELECT 'WITH_MRCH' FROM DUAL
  UNION ALL SELECT 'CMPY_NAME' FROM DUAL
  UNION ALL SELECT 'DOC_ID' FROM DUAL
  UNION ALL SELECT 'DOC_TYPE' FROM DUAL
  UNION ALL SELECT 'DOC_COUNTRY_CODE' FROM DUAL
  UNION ALL SELECT 'MRCH_USER_ID' FROM DUAL
  UNION ALL SELECT 'MRCH_USER_NAME' FROM DUAL
  UNION ALL SELECT 'DOC_CMPY_NAME' FROM DUAL
  UNION ALL SELECT 'DOC_ACCT_NBR' FROM DUAL
  UNION ALL SELECT 'SLE_MRCH_NAME' FROM DUAL
  UNION ALL SELECT 'FORMAT' FROM DUAL
  UNION ALL SELECT 'TXN_COUNT' FROM DUAL
  UNION ALL SELECT 'ADV_FREQ_TYPE' FROM DUAL
  UNION ALL SELECT 'ADV_TYPE' FROM DUAL
  UNION ALL SELECT 'SLE_MRCH_ID' FROM DUAL
  UNION ALL SELECT 'AR_TOKEN' FROM DUAL
  UNION ALL SELECT 'TREASURY_REF' FROM DUAL
  UNION ALL SELECT 'LM_SWEEP_INSTRUCTION_TYPE' FROM DUAL
  UNION ALL SELECT 'LM_FREQUENCY_EXECUTIONDAY' FROM DUAL
  UNION ALL SELECT 'LM_EFFECTIVEDATE' FROM DUAL
  UNION ALL SELECT 'LM_RULE_SETUPDATE' FROM DUAL
  UNION ALL SELECT 'LM_SWEEPING_AMOUNT_THRESHOLD' FROM DUAL
  UNION ALL SELECT 'LM_FPXTXN_NBR' FROM DUAL
  UNION ALL SELECT 'LM_INSTRUCTION_NBR' FROM DUAL
  UNION ALL SELECT 'USER_ROLE' FROM DUAL
  UNION ALL SELECT 'TOKEN_ID' FROM DUAL
  UNION ALL SELECT 'ERR_CODE' FROM DUAL
  UNION ALL SELECT 'BIO_TYPE' FROM DUAL
  UNION ALL SELECT 'REG_METHOD' FROM DUAL
  UNION ALL SELECT 'AUTH_METHOD' FROM DUAL
  UNION ALL SELECT 'LANG' FROM DUAL
  UNION ALL SELECT 'APP_VERSION' FROM DUAL
  UNION ALL SELECT 'SOURCE_SYSTEM' FROM DUAL
  UNION ALL SELECT 'CHANNEL_TYPE' FROM DUAL
  UNION ALL SELECT 'TARGET_USER_CHANNEL' FROM DUAL
  UNION ALL SELECT 'ACTIVITY_KEY' FROM DUAL
  UNION ALL SELECT 'PHASE' FROM DUAL
  UNION ALL SELECT 'TARGET_USER_ID' FROM DUAL
  UNION ALL SELECT 'RELATIONSHIP_TYPE' FROM DUAL
  UNION ALL SELECT 'SERVICE_ID' FROM DUAL
  UNION ALL SELECT 'TASK_CODE' FROM DUAL
  UNION ALL SELECT 'SOURCE_ACTION_ID' FROM DUAL
  UNION ALL SELECT 'REQUEST_ID' FROM DUAL
  UNION ALL SELECT 'ERROR_CODE' FROM DUAL
  UNION ALL SELECT 'DEDUP_KEY' FROM DUAL
  UNION ALL SELECT 'CREATED_AT' FROM DUAL
)
SELECT c.COLUMN_NAME, c.DATA_TYPE, c.NULLABLE,
       CASE WHEN c.NULLABLE='N' AND c.VIRTUAL_COLUMN='NO' AND c.IDENTITY_COLUMN='NO'
              THEN 'FAIL: extra required column not supplied by application'
            ELSE 'REVIEW: extra column preserved by installer' END AS EXTRA_COLUMN_CHECK
FROM ALL_TAB_COLS c
WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_CRM_EVENT_DETAILS' AND c.USER_GENERATED='YES'
  AND NOT EXISTS (SELECT 1 FROM expected_columns s WHERE s.column_name=c.COLUMN_NAME)
ORDER BY c.COLUMN_ID;

SELECT CASE WHEN COUNT(*)=1 AND MAX(COMMENTS)='HTH CM/BM onboarding operation records for CRM/MTB; populated by application events, with no deployment seed data.'
              THEN 'PASS' ELSE 'FAIL: table comment missing or differs from release definition' END AS TABLE_COMMENT_CHECK,
       MAX(COMMENTS) AS COMMENTS
FROM ALL_TAB_COMMENTS WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS';

SELECT CASE WHEN COUNT(*)=1 THEN 'PASS' ELSE 'FAIL: enabled validated EVENT_ID primary key required' END AS PRIMARY_KEY_CHECK
FROM ALL_CONSTRAINTS c
WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_CRM_EVENT_DETAILS'
  AND c.CONSTRAINT_TYPE='P' AND c.STATUS='ENABLED' AND c.VALIDATED='VALIDATED'
  AND 1=(SELECT COUNT(*) FROM ALL_CONS_COLUMNS x WHERE x.OWNER=c.OWNER AND x.CONSTRAINT_NAME=c.CONSTRAINT_NAME)
  AND EXISTS (SELECT 1 FROM ALL_CONS_COLUMNS x WHERE x.OWNER=c.OWNER
              AND x.CONSTRAINT_NAME=c.CONSTRAINT_NAME AND x.COLUMN_NAME='EVENT_ID');

-- Accept equivalent valid indexes, as script 1 does. Names below are used on new installs.
WITH expected_indexes AS (
  SELECT 'UX_HTH_CRM_DEDUP' index_name, 'DEDUP_KEY' column_names, 'UNIQUE' index_uniqueness FROM DUAL
  UNION ALL SELECT 'IX_HTH_CRM_DATE_ACT','EVENT_DTE,ACTIVITY_KEY','NONUNIQUE' FROM DUAL
  UNION ALL SELECT 'IX_HTH_CRM_SOURCE','SOURCE_TRX_REF_NBR','NONUNIQUE' FROM DUAL
), actual_indexes AS (
  SELECT i.INDEX_NAME, i.TABLE_OWNER, i.TABLE_NAME, i.UNIQUENESS, i.STATUS, i.INDEX_TYPE,
         (SELECT LISTAGG(c.COLUMN_NAME,',') WITHIN GROUP (ORDER BY c.COLUMN_POSITION)
          FROM ALL_IND_COLUMNS c WHERE c.INDEX_OWNER=i.OWNER AND c.INDEX_NAME=i.INDEX_NAME) AS column_names
  FROM ALL_INDEXES i WHERE i.OWNER='HTH_BEA'
    AND ((i.TABLE_OWNER='HTH_BEA' AND i.TABLE_NAME='HTH_CRM_EVENT_DETAILS')
         OR i.INDEX_NAME IN (SELECT index_name FROM expected_indexes))
)
SELECT s.index_name AS DEFAULT_INDEX_NAME, s.column_names AS EXPECTED_COLUMNS,
       CASE WHEN EXISTS (SELECT 1 FROM ALL_OBJECTS o WHERE o.OWNER='HTH_BEA'
                         AND o.OBJECT_NAME=s.index_name AND o.OBJECT_TYPE<>'INDEX')
              THEN 'FAIL: reserved index name belongs to another object'
            WHEN EXISTS (SELECT 1 FROM actual_indexes bad
                         WHERE (bad.INDEX_NAME=s.index_name
                           OR (bad.TABLE_OWNER='HTH_BEA' AND bad.TABLE_NAME='HTH_CRM_EVENT_DETAILS'
                               AND bad.column_names=s.column_names))
                           AND (bad.TABLE_OWNER<>'HTH_BEA' OR bad.TABLE_NAME<>'HTH_CRM_EVENT_DETAILS'
                             OR NVL(bad.column_names,'?')<>s.column_names OR bad.UNIQUENESS<>s.index_uniqueness
                             OR NVL(bad.STATUS,'?')<>'VALID' OR bad.INDEX_TYPE<>'NORMAL'))
              THEN 'FAIL: conflicting index definition'
            WHEN COUNT(i.INDEX_NAME)>0 THEN 'PASS'
            ELSE 'FAIL: valid index missing or incompatible' END AS INDEX_CHECK,
       LISTAGG(i.INDEX_NAME,',') WITHIN GROUP (ORDER BY i.INDEX_NAME) AS MATCHING_INDEXES
FROM expected_indexes s LEFT JOIN actual_indexes i
  ON i.TABLE_OWNER='HTH_BEA' AND i.TABLE_NAME='HTH_CRM_EVENT_DETAILS'
     AND i.column_names=s.column_names AND i.UNIQUENESS=s.index_uniqueness
     AND i.STATUS='VALID' AND i.INDEX_TYPE='NORMAL'
GROUP BY s.index_name,s.column_names,s.index_uniqueness ORDER BY s.index_name;

-- New table grants only. Table owners need no object grants; other datasource users do.
-- Compare GRANTEE with the actual NONXA datasource account, not just the deployment account.
SELECT GRANTEE, PRIVILEGE, GRANTABLE FROM ALL_TAB_PRIVS
WHERE TABLE_SCHEMA='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS'
ORDER BY GRANTEE, PRIVILEGE;

-- Data checks: a newly installed table is empty until the updated application writes events.
-- Default interval is the last 24 hours in Hong Kong time.
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_TRX_REF_NBR, CREATED_AT FROM HTH_BEA.HTH_CRM_EVENT_DETAILS
WHERE CREATED_AT >= CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP) - INTERVAL '1' DAY
  AND CREATED_AT < CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP)
ORDER BY CREATED_AT DESC, EVENT_ID DESC;
SELECT DEDUP_KEY, COUNT(*) FROM HTH_BEA.HTH_CRM_EVENT_DETAILS
WHERE DEDUP_KEY IS NOT NULL GROUP BY DEDUP_KEY HAVING COUNT(*)>1;

-- Existing historical rows may have no values for metadata introduced by 849.
-- Do not backfill ACTIVITY_KEY/PHASE/CREATED_AT with invented business values.
SELECT COUNT(*) AS TOTAL_ROWS,
       COUNT(CREATED_AT) AS ROWS_WITH_CREATED_AT,
       COUNT(ACTIVITY_KEY) AS ROWS_WITH_ACTIVITY_KEY
FROM HTH_BEA.HTH_CRM_EVENT_DETAILS;

-- Recent User Access operation stages. A submit and an approval are separate records.
-- Add a SOURCE_TRX_REF_NBR filter for the tested transaction if available.
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_SYSTEM, CHANNEL_TYPE, TARGET_USER_CHANNEL, SERVICE_ID,
       RECORD_TYPE, CHNL_ID, CHNL_TYPE_CODE, SELF_SRV_IND, EVENT_COUNTRY_CODE,
       USER_ROLE, LANG, DEVICE_MODEL, EVENT_REM,
       SOURCE_TRX_REF_NBR, ERROR_CODE, ERR_CODE, CREATED_AT
FROM HTH_BEA.HTH_CRM_EVENT_DETAILS
WHERE ACTIVITY_KEY IN ('ACCESS_CREATE','ACCESS_EDIT','ACCESS_DELETE')
  AND CREATED_AT >= CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP) - INTERVAL '1' DAY
ORDER BY CREATED_AT DESC, EVENT_ID DESC;

-- Include legacy rows excluded by a CREATED_AT filter. This does not classify data as synthetic.
SELECT * FROM (
  SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, SOURCE_SYSTEM, ACTIVITY_KEY, PHASE,
         SERVICE_ID, SOURCE_TRX_REF_NBR, CREATED_AT
  FROM HTH_BEA.HTH_CRM_EVENT_DETAILS
  ORDER BY CREATED_AT DESC NULLS LAST, EVENT_DTE DESC, EVENT_TIME DESC, EVENT_ID DESC
) WHERE ROWNUM<=50;
