-- Run on the HTH_BEA connection. Read-only; execute each SELECT separately.
-- Default data interval: last 24 hours in Hong Kong time.
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, CHAR_LENGTH, CHAR_USED, NULLABLE FROM ALL_TAB_COLUMNS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS' ORDER BY COLUMN_ID;
SELECT COMMENTS FROM ALL_TAB_COMMENTS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_MTB_EVENT_DETAILS';
SELECT c.COLUMN_ID, c.COLUMN_NAME, d.COMMENTS
FROM ALL_TAB_COLUMNS c LEFT JOIN ALL_COL_COMMENTS d
  ON d.OWNER=c.OWNER AND d.TABLE_NAME=c.TABLE_NAME AND d.COLUMN_NAME=c.COLUMN_NAME
WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_MTB_EVENT_DETAILS'
ORDER BY c.COLUMN_ID;
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_TRX_REF_NBR, CREATED_AT FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE CREATED_AT >= CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP) - INTERVAL '1' DAY
  AND CREATED_AT < CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP)
ORDER BY CREATED_AT DESC, EVENT_ID DESC;
SELECT DEDUP_KEY, COUNT(*) FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE DEDUP_KEY IS NOT NULL GROUP BY DEDUP_KEY HAVING COUNT(*)>1;

-- Existing historical rows may have no values for metadata introduced by 849.
-- Do not backfill ACTIVITY_KEY/PHASE/CREATED_AT with invented business values.
SELECT COUNT(*) AS TOTAL_ROWS,
       COUNT(CREATED_AT) AS ROWS_WITH_CREATED_AT,
       COUNT(ACTIVITY_KEY) AS ROWS_WITH_ACTIVITY_KEY
FROM HTH_BEA.HTH_MTB_EVENT_DETAILS;

-- Recent User Access operation stages. A submit and an approval are separate records.
-- Add a SOURCE_TRX_REF_NBR filter for the tested transaction if available.
SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, ACTIVITY_KEY, PHASE, EVENT_STATUS_CODE,
       SOURCE_SYSTEM, CHANNEL_TYPE, TARGET_USER_CHANNEL, SERVICE_ID,
       SOURCE_TRX_REF_NBR, ERROR_CODE, CREATED_AT
FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
WHERE ACTIVITY_KEY IN ('ACCESS_CREATE','ACCESS_EDIT','ACCESS_DELETE')
  AND CREATED_AT >= CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Hong_Kong' AS TIMESTAMP) - INTERVAL '1' DAY
ORDER BY CREATED_AT DESC, EVENT_ID DESC;

-- Include legacy rows excluded by a CREATED_AT filter. This does not classify data as synthetic.
SELECT * FROM (
  SELECT EVENT_ID, EVENT_DTE, EVENT_TIME, SOURCE_SYSTEM, ACTIVITY_KEY, PHASE,
         SERVICE_ID, SOURCE_TRX_REF_NBR, CREATED_AT
  FROM HTH_BEA.HTH_MTB_EVENT_DETAILS
  ORDER BY CREATED_AT DESC NULLS LAST, EVENT_DTE DESC, EVENT_TIME DESC, EVENT_ID DESC
) WHERE ROWNUM<=50;

-- Inventory the additional UAT table without assuming its columns or purpose.
-- HTH_MTB_API_CONFIG is not created or read by the current 849 implementation.
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, CREATED, LAST_DDL_TIME, STATUS
FROM ALL_OBJECTS WHERE OWNER='HTH_BEA'
  AND OBJECT_NAME IN ('HTH_MTB_EVENT_DETAILS','HTH_MTB_API_CONFIG')
ORDER BY OBJECT_NAME, OBJECT_TYPE;
SELECT c.TABLE_NAME, c.COLUMN_ID, c.COLUMN_NAME, c.DATA_TYPE, c.DATA_LENGTH, d.COMMENTS
FROM ALL_TAB_COLUMNS c LEFT JOIN ALL_COL_COMMENTS d
  ON d.OWNER=c.OWNER AND d.TABLE_NAME=c.TABLE_NAME AND d.COLUMN_NAME=c.COLUMN_NAME
WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_MTB_API_CONFIG'
ORDER BY c.COLUMN_ID;
SELECT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME
FROM ALL_DEPENDENCIES
WHERE REFERENCED_OWNER='HTH_BEA' AND REFERENCED_NAME='HTH_MTB_API_CONFIG'
ORDER BY OWNER, NAME, TYPE;
SELECT OWNER, TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGERING_EVENT
FROM ALL_TRIGGERS
WHERE TABLE_OWNER='HTH_BEA' AND TABLE_NAME IN ('HTH_MTB_API_CONFIG','HTH_MTB_EVENT_DETAILS')
ORDER BY TABLE_NAME, TRIGGER_NAME;
-- If the inventory confirms HTH_MTB_API_CONFIG exists and is accessible, inspect a sample:
-- SELECT * FROM HTH_BEA.HTH_MTB_API_CONFIG WHERE ROWNUM<=20;
-- Object creation time/dependencies do not prove who inserted existing rows.
