-- Run on the DIGX configuration connection. Read-only; execute each SELECT separately.
SELECT PROP_ID, PROP_VALUE, DETERMINANT_VALUE FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='HTHMtbConfiguration' ORDER BY PROP_ID;
-- Existing BCO reference configuration, do not update:
SELECT PROP_ID, PROP_VALUE FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='CRMConfiguration'
AND (PROP_ID LIKE '%UAT_N_RA%' OR PROP_ID LIKE '%LAT_N_CA%' OR PROP_ID LIKE '%LAT_N_UA%' OR PROP_ID LIKE '%LAT_N_DA%')
ORDER BY PROP_ID;

-- HTH cross-module factory; no BCO factory keys changed.
SELECT PREFERENCE_NAME, PROP_ID, PROP_VALUE, DETERMINANT_VALUE
FROM DIGX_FW_CONFIG_ALL_O
WHERE PREFERENCE_NAME='AdapterFactories' AND PROP_ID='HTH_MTB_ADAPTER_FACTORY';
