-- BCOH2H-849: standalone English database comments; run on the HTH_BEA connection.
-- DBeaver: open this entire file and Execute SQL Script (Alt+X).
-- Requires HTH_BEA.HTH_CRM_EVENT_DETAILS and the 24 columns installed by script 1.
-- No table/column/index definition or business data is changed. Repeat execution is safe.
-- Oracle COMMENT statements commit implicitly; use a dedicated deployment session.
-- Stop on errors. ORA-00904 indicates a missing column: finish script 1 before retrying.
-- Extra legacy columns and HTH_MTB_API_CONFIG are outside this script's scope.
-- Successful execution sets one table comment and 24 column comments; no restart is required.

COMMENT ON TABLE HTH_BEA.HTH_CRM_EVENT_DETAILS IS 'HTH CM/BM onboarding operation records for CRM/MTB; populated by application events, with no deployment seed data.';

COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_ID IS 'Unique event identifier generated by the HTH CRM collector.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_DTE IS 'Event date in Asia/Hong_Kong time, formatted as yyyyMMdd.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_TIME IS 'Event time in Asia/Hong_Kong time, formatted as HHmmss.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SOURCE_SYSTEM IS 'Source system identifier; current HTH collector writes HTH.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CHANNEL_TYPE IS 'Originating portal: CM for customer management, BM for bank management.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TARGET_USER_CHANNEL IS 'Target user channel HTH; null for company-level operations.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACTIVITY_KEY IS 'Internal HTH operation, such as ACCESS_CREATE, ACCESS_EDIT or PASSWORD_SETUP.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_ACTV_TYPE_CODE IS 'External CRM activity code from ACTIVITY_<ACTIVITY_KEY> configuration; null when not configured.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_STATUS_CODE IS 'Operation-stage result: A for success or submission accepted for approval; R for failure or business rollback.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PHASE IS 'Recorded stage: SUBMIT, APPLY, GENERATE, EXECUTE, APPROVAL_APPROVE, APPROVAL_REJECT or APPROVAL_ACTION.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FIN_IND IS 'Financial indicator; N for the non-financial CM/BM onboarding operations in this release.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.USER_ID IS 'User who performed this operation or approval action.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TARGET_USER_ID IS 'User affected by the operation; null for company-level operations.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACCT_NBR IS 'Corporate party identifier for the maintenance operation; not an individual bank account number.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.RELATIONSHIP_TYPE IS 'Account/service access relationship type supplied by the operation, such as Related or Associated.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SERVICE_ID IS 'Application service identifier that produced the HTH CRM event.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TASK_CODE IS 'Platform task identifier captured from the operation context when available.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SOURCE_TRX_REF_NBR IS 'Approval transaction reference or business response reference used to correlate the event.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SOURCE_ACTION_ID IS 'Stable identifier for a specific action, when supplied; distinct from the transaction reference.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.REQUEST_ID IS 'Request identifier supplied by the operation, when available.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.IP_ADDRESS IS 'Client IP address supplied by the platform operation context, when available.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ERROR_CODE IS 'Sanitized application error code; BUSINESS_ROLLBACK denotes a rolled-back business transaction.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DEDUP_KEY IS 'SHA-256 event deduplication key when a reliable action identifier is available; otherwise null.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CREATED_AT IS 'Database insert time in Asia/Hong_Kong time; null for legacy rows without this metadata.';

-- Confirm the database and login used for this execution.
SELECT SYS_CONTEXT('USERENV','DB_NAME') AS DATABASE_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','SESSION_USER') AS LOGIN_USER
FROM DUAL;

-- Check stored comments directly; do not rely on cached client metadata.
SELECT OWNER, TABLE_NAME, COMMENTS FROM ALL_TAB_COMMENTS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS';
SELECT c.COLUMN_ID, c.COLUMN_NAME, d.COMMENTS
FROM ALL_TAB_COLUMNS c LEFT JOIN ALL_COL_COMMENTS d
  ON d.OWNER=c.OWNER AND d.TABLE_NAME=c.TABLE_NAME AND d.COLUMN_NAME=c.COLUMN_NAME
WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_CRM_EVENT_DETAILS'
ORDER BY c.COLUMN_ID;
