-- BCOH2H-849: standalone English database comments; run on the HTH_BEA connection.
-- DBeaver: open this entire file and Execute SQL Script (Alt+X).
-- Requires HTH_BEA.HTH_CRM_EVENT_DETAILS and the 113 columns installed by script 1.
-- No table/column/index definition or business data is changed. Repeat execution is safe.
-- Oracle COMMENT statements commit implicitly; use a dedicated deployment session.
-- Stop on errors. ORA-00904 indicates a missing column: finish script 1 before retrying.
-- Extra legacy columns and HTH_MTB_API_CONFIG are outside this script's scope.
-- Successful execution sets one table comment and 113 column comments; no restart is required.

COMMENT ON TABLE HTH_BEA.HTH_CRM_EVENT_DETAILS IS 'HTH CM/BM onboarding operation records for CRM/MTB; populated by application events, with no deployment seed data.';

COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_ID IS 'Unique event identifier generated by the HTH CRM collector.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.RECORD_TYPE IS 'CRM record type from the existing BCO CRM configuration; null when not configured.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FILLER_01 IS 'CRM filler value from the existing BCO CRM configuration; null when not configured.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_DTE IS 'Event date in Asia/Hong_Kong time, formatted as yyyyMMdd.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_TIME IS 'Event time in Asia/Hong_Kong time, formatted as HHmmss.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CHNL_ID IS 'BCO CRM channel identifier from Login-Channel and CRM configuration; distinct from the CM/BM portal.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CHNL_TYPE_CODE IS 'BCO CRM channel type code from the existing CRM configuration; null when not configured.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_STATUS_CODE IS 'Operation-stage result: A for success or submission accepted for approval; R for failure or business rollback.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CR_DR_IND IS 'Credit or debit indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FEE_CHRG_CODE IS 'Fee charge classification from the existing BCO CRM configuration; no fee is generated by this record.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_ACTV_TYPE_CODE IS 'External CRM activity code from ACTIVITY_<ACTIVITY_KEY> configuration; null when not configured.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FIN_IND IS 'Financial indicator; N for the non-financial CM/BM onboarding operations in this release.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SELF_SRV_IND IS 'BCO self-service indicator derived from the platform isAdmin context; null when unknown.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.USER_ID IS 'User who performed this operation or approval action.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_COUNTRY_CODE IS 'CRM event country code from the existing BCO CRM configuration; null when not configured.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACCT_NBR IS 'Corporate party identifier for the maintenance operation; not an individual bank account number.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PHONE_NBR IS 'Phone proxy number from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PHONE_NBR_ACCT_NBR IS 'Account linked to the phone proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PHONE_NBR_REQ_RESULT IS 'Phone proxy request result from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PHONE_DEFAULT_IND IS 'Default phone proxy indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ELECT_ADD IS 'Electronic-address proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ELECT_ADD_ACCT_NBR IS 'Account linked to the electronic-address proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ELECT_ADD_REQ_RESULT IS 'Electronic-address proxy request result from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ELECT_ADD_DEFAULT_IND IS 'Default electronic-address proxy indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FPS_ID IS 'FPS proxy identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FPS_ACCT_NBR IS 'Account linked to the FPS proxy from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FPS_REQ_RESULT IS 'FPS proxy request result from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DEBIT_ACCT_NBR IS 'Debit account number from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_CCY_CODE IS 'Event currency code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_AMT IS 'Event amount from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FEE_CHRG_AMT IS 'Fee charged amount from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FEE_CCY_CODE IS 'Fee currency code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TRF_DTE IS 'Transfer date from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TRF_FREQ IS 'Transfer frequency from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PROXY_ID_TYPE IS 'Payment proxy identifier type from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PROXY_ID IS 'Payment proxy identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PAYEE_NAME IS 'Payee name from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PAYEE_BANK_CODE IS 'Payee bank code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_REM IS 'BCO-style event reference remark, limited to 40 characters; the full HTH reference remains in SOURCE_TRX_REF_NBR.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.REF_NBR IS 'BCO numeric-format reference number from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FROM_DTE IS 'Period start date from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TO_DTE IS 'Period end date from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.MANDATE_ID IS 'Direct-debit mandate identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EDDA_MAINT_ACTION IS 'Electronic direct-debit maintenance action from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SOURCE_TRX_REF_NBR IS 'Approval transaction reference or business response reference used to correlate the event.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PAY_CAT_PURP_CODE IS 'Payment category purpose code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PAY_PURP_CODE IS 'Payment purpose code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DEVICE_ID IS 'Device identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.MOBILE_BRAND IS 'Operating-system label parsed from the user agent, following the BCO field convention; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PLATFORM_CODE IS 'Client platform code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DEVICE_MODEL IS 'Browser brand parsed from the user agent, following the BCO field convention; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DEVICE_OS_VERSION IS 'Browser version parsed from the user agent, following the BCO field convention; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.IP_ADDRESS IS 'Client IP address supplied by the platform operation context, when available.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FILLER_02 IS 'Secondary CRM filler from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_AMT_HKE IS 'Event amount in Hong Kong dollar equivalent from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.EVENT_EX_RATE IS 'Event exchange rate from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.MRCH_ID IS 'Merchant identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACCT_CCY_CODE IS 'Account currency code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACCT_AMT IS 'Account-currency amount from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SCREEN_ID IS 'BCO screen identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.OMB_FLAG IS 'One-Man-Bank approval indicator: Y for affirmative CM user/access context; null when unknown or not applicable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.MULTI_APP_REJ_TXN_CNT IS 'Count of transactions in a multiple-approval or rejection action from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.COUPON_CODE IS 'Coupon code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACTL_INT_RATE IS 'Actual interest rate from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TT_AUTO_ROUTE IS 'BCO CRM automatic-routing default N for these non-financial HTH maintenance events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SUSPICIOUS_ACTIVITY IS 'Suspicious activity classification from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SUSPICIOUS_IND IS 'Suspicious activity indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.WITH_MRCH IS 'Merchant-presence indicator from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CMPY_NAME IS 'Merchant company name from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DOC_ID IS 'Document identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DOC_TYPE IS 'Document type from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DOC_COUNTRY_CODE IS 'Document issuing country code from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.MRCH_USER_ID IS 'Merchant user identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.MRCH_USER_NAME IS 'Merchant user name from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DOC_CMPY_NAME IS 'Company name on a document from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DOC_ACCT_NBR IS 'Account number on a document from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SLE_MRCH_NAME IS 'SLE merchant name from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.FORMAT IS 'Advice or document format from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TXN_COUNT IS 'Transaction count from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ADV_FREQ_TYPE IS 'Advice frequency type from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ADV_TYPE IS 'Advice type from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SLE_MRCH_ID IS 'SLE merchant identifier from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.AR_TOKEN IS 'AR token from the BCO model; reserved and always null in HTH because token values are not collected.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TREASURY_REF IS 'Treasury reference from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_SWEEP_INSTRUCTION_TYPE IS 'Liquidity-management sweep instruction type from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_FREQUENCY_EXECUTIONDAY IS 'Liquidity-management frequency or execution day from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_EFFECTIVEDATE IS 'Liquidity-management effective date from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_RULE_SETUPDATE IS 'Liquidity-management rule setup date from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_SWEEPING_AMOUNT_THRESHOLD IS 'Liquidity-management sweep amount or threshold from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_FPXTXN_NBR IS 'Liquidity-management FPX transaction number from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LM_INSTRUCTION_NBR IS 'Liquidity-management instruction number from the BCO model; reserved and null for current HTH CM/BM onboarding events.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.USER_ROLE IS 'Platform user role from the approved request metadata field; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TOKEN_ID IS 'Authentication token identifier from the BCO model; reserved and always null in HTH because token values are not collected.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ERR_CODE IS 'BCO-model error code: first approval-processing code or TFA context code, keeping the last 20 characters; distinct from HTH ERROR_CODE.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.BIO_TYPE IS 'Biometric authentication type from the approved platform metadata field; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.REG_METHOD IS 'Registration method from the approved platform metadata field; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.AUTH_METHOD IS 'Authentication method from the approved platform metadata field; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.LANG IS 'BCO CRM language code: en, sc or tc, derived from the active locale.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.APP_VERSION IS 'Client application version from the approved platform metadata field; null when unavailable.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SOURCE_SYSTEM IS 'Source system identifier; current HTH collector writes HTH.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CHANNEL_TYPE IS 'Originating portal: CM for customer management, BM for bank management.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TARGET_USER_CHANNEL IS 'Target user channel HTH; null for company-level operations.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ACTIVITY_KEY IS 'Internal HTH operation, such as ACCESS_CREATE, ACCESS_EDIT or PASSWORD_SETUP.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.PHASE IS 'Recorded stage: SUBMIT, APPLY, GENERATE, EXECUTE, APPROVAL_APPROVE, APPROVAL_REJECT or APPROVAL_ACTION.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TARGET_USER_ID IS 'User affected by the operation; null for company-level operations.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.RELATIONSHIP_TYPE IS 'Account/service access relationship type supplied by the operation, such as Related or Associated.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SERVICE_ID IS 'Application service identifier that produced the HTH CRM event.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.TASK_CODE IS 'Platform task identifier captured from the operation context when available.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.SOURCE_ACTION_ID IS 'Stable identifier for a specific action, when supplied; distinct from the transaction reference.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.REQUEST_ID IS 'Request identifier supplied by the operation, when available.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.ERROR_CODE IS 'Sanitized application error code; BUSINESS_ROLLBACK denotes a rolled-back business transaction.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.DEDUP_KEY IS 'SHA-256 event deduplication key when a reliable action identifier is available; otherwise null.';
COMMENT ON COLUMN HTH_BEA.HTH_CRM_EVENT_DETAILS.CREATED_AT IS 'Record write time in Asia/Hong_Kong time; null for legacy rows without this metadata.';

-- Confirm the database and login used for this execution.
SELECT SYS_CONTEXT('USERENV','DB_NAME') AS DATABASE_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','SESSION_USER') AS LOGIN_USER
FROM DUAL;

-- Check stored comments directly; do not rely on cached client metadata.
SELECT OWNER, TABLE_NAME, COMMENTS FROM ALL_TAB_COMMENTS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS';
SELECT c.COLUMN_ID, c.COLUMN_NAME, d.COMMENTS
FROM ALL_TAB_COLUMNS c LEFT JOIN ALL_COL_COMMENTS d
  ON d.OWNER=c.OWNER AND d.TABLE_NAME=c.TABLE_NAME AND d.COLUMN_NAME=c.COLUMN_NAME
WHERE c.OWNER='HTH_BEA' AND c.TABLE_NAME='HTH_CRM_EVENT_DETAILS'
ORDER BY c.COLUMN_ID;
