package com.ofss.digx.cz.bea.domain.hosttohost.entity.crm.repository.adapter;

import java.sql.SQLIntegrityConstraintViolationException;

import com.ofss.digx.cz.bea.domain.hosttohost.entity.crm.HthCRMEvent3DomainDTO;
import com.ofss.fc.infra.das.orm.Session;

/** Persists the HTH entity through its ORM mapping, using only the supplied session. */
public final class LocalHthCRMRepositoryAdapter {
    public void create(Session session, HthCRMEvent3DomainDTO event) throws java.lang.Exception {
        if (event == null || event.getKey() == null || event.getKey().getEventId() == null) {
            throw new IllegalArgumentException("HTH CRM event key is required");
        }
        // CRM events are append-only. The entity-name overload uses this session directly;
        // the Class overload consults the framework's thread-bound MetaModel/session.
        if (session.get("HthCRMEvent3DomainDTO", event.getKey()) != null) {
            throw new SQLIntegrityConstraintViolationException("HTH CRM event already exists");
        }
        // In the bundled framework, save()/super.create() consult the thread-bound business
        // session. saveOrUpdate() uses this explicit session's EntityManager instead. New
        // event UUIDs are generated by the assembler; the guard above rejects existing keys.
        session.saveOrUpdate(event);
    }
}
