SELECT PROP_ID, PROP_VALUE
FROM DIGX_FW_CONFIG_OUT_RS_CFG_V
WHERE (
    PROP_ID LIKE 'AUTH_DECRYPT_PROVIDER.%'
    OR PROP_ID LIKE 'AUTH_PUBLICKEY_PROVIDER.%'
)
AND (
    PROP_ID LIKE '%.contextUrl'
    OR PROP_ID LIKE '%.serviceUrl'
    OR PROP_ID LIKE '%.mockServiceUrl'
)
ORDER BY PROP_ID;