-- Run in the OBDX configuration/profile schema. DDL commits implicitly in Oracle.
-- Persistent delivery intent, NOT another User/Profile/Password table. Never drop on redeployment.
DECLARE
  existing_table NUMBER;
  existing_index NUMBER;
BEGIN
  SELECT COUNT(*) INTO existing_table FROM USER_TABLES WHERE TABLE_NAME = 'DIGX_CZ_HTH_CONTACT_OUTBOX';
  IF existing_table = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DIGX_CZ_HTH_CONTACT_OUTBOX (
      ID VARCHAR2(32) NOT NULL, TARGET_UNIT VARCHAR2(50) NOT NULL,
      APPROVAL_REF VARCHAR2(100) NOT NULL, PARTY_ID VARCHAR2(50) NOT NULL,
      TARGET_USER_ID VARCHAR2(254) NOT NULL, APPROVER_ID VARCHAR2(254) NOT NULL,
      CHANGE_TYPE VARCHAR2(10) NOT NULL, RECIPIENT_ROLE VARCHAR2(30) NOT NULL,
      CHANNEL VARCHAR2(5) NOT NULL, ADDRESS VARCHAR2(320) NOT NULL,
      RECIPIENT_USER_ID VARCHAR2(254) NOT NULL, USER_LOCALE VARCHAR2(20),
      APPROVED_AT VARCHAR2(30) NOT NULL, STATE VARCHAR2(30) NOT NULL,
      EVENT_ID VARCHAR2(100) NOT NULL, NEW_EMAIL VARCHAR2(320),
      FALLBACK_ID VARCHAR2(32), PARENT_ID VARCHAR2(32), COD_ACT_DATA_ID VARCHAR2(100),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_HTH_851_NOTIFY PRIMARY KEY (ID),
      CONSTRAINT FK_HTH_851_PARENT FOREIGN KEY (PARENT_ID) REFERENCES DIGX_CZ_HTH_CONTACT_OUTBOX (ID),
      CONSTRAINT CK_HTH_851_TYPE CHECK (CHANGE_TYPE IN (''BOTH'',''EMAIL'',''MOBILE'')),
      CONSTRAINT CK_HTH_851_CHANNEL CHECK (CHANNEL IN (''EMAIL'',''SMS'')),
      CONSTRAINT CK_HTH_851_STATE CHECK (STATE IN (''READY'',''PUBLISHING'',''PUBLISHED'',''SENDING'',''SUBMITTED'',''REJECTED'',''UNKNOWN'',''DELIVERY_FAILED'',''FALLBACK_QUEUED'',''FALLBACK_LINKED'',''FAILED_FINAL'',''OFFICE_FOLLOWUP'',''OFFICE_NOTIFIED''))
    )';
  END IF;
  SELECT COUNT(*) INTO existing_index FROM USER_INDEXES WHERE INDEX_NAME='IX_HTH_851_PENDING';
  IF existing_index = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_HTH_851_PENDING ON DIGX_CZ_HTH_CONTACT_OUTBOX (TARGET_UNIT, STATE, UPDATED_AT)';
  END IF;
END;
/
