-- Rerunnable, default OFF; preserve existing switch/JNDI. No BCO events/templates are changed.
BEGIN

  SAVEPOINT HTH_CONTACT_CONFIG;

INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS, SUMMARY_TEXT,
  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
SELECT 'HTH_PROFILE_CONTACT_NOTIFICATION_ENABLED', 'HthProfileContactNotification', 'false', 'N', 'BCOH2H-851 contact notification',
 'HTH Profile Contact Notification', USER, SYSDATE, USER, SYSDATE, 'A', 1, 'N', NULL FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_FW_CONFIG_ALL_B WHERE CATEGORY_ID = 'HthProfileContactNotification' AND PROP_ID = 'HTH_PROFILE_CONTACT_NOTIFICATION_ENABLED');

INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS, SUMMARY_TEXT,
  CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
SELECT 'dispatchDataSource', 'HthProfileContactNotification', 'NONXA', 'N', 'BCOH2H-851 contact notification',
 'HTH Profile Contact Notification', USER, SYSDATE, USER, SYSDATE, 'A', 1, 'N', NULL FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DIGX_FW_CONFIG_ALL_B WHERE CATEGORY_ID = 'HthProfileContactNotification' AND PROP_ID = 'dispatchDataSource');

EXCEPTION WHEN OTHERS THEN
  ROLLBACK TO HTH_CONTACT_CONFIG;
  RAISE;
END;
/
COMMIT;
