-- Read only. These are EXISTING BCO events/templates; do not install the retired six HTH events.
SELECT CATEGORY_ID, PROP_ID, PROP_VALUE FROM DIGX_FW_CONFIG_ALL_B
WHERE CATEGORY_ID = 'HthProfileContactNotification' ORDER BY PROP_ID;

-- Expect a live recipient/template binding for each supported locale (en / zh-Hant / zh-Hans-CN).
-- Any missing row or missing template must be reconciled with the current BCO baseline before enabling.
WITH expected AS (
  SELECT 'update' op, 'INFO_UPDATE_BY_CORP_ADMIN' event_id, 'EMAIL' channel FROM DUAL UNION ALL
  SELECT 'update', 'USER_EMAIL_ADDRESS_UPDATE', 'SMS' FROM DUAL UNION ALL
  SELECT 'update', 'USER_MOBILE_NUMBER_UPDATED_REMINDER', 'SMS' FROM DUAL UNION ALL
  SELECT 'create', 'CORPORATEPLUS_WELCOME_MAIL', 'SMS' FROM DUAL
), locales AS (
  SELECT 'en' locale FROM DUAL UNION ALL SELECT 'zh-Hant' FROM DUAL UNION ALL SELECT 'zh-Hans-CN' FROM DUAL
)
SELECT E.EVENT_ID, E.CHANNEL, L.LOCALE, R.COD_MSG_TMPL_ID,
       R.SUBSCRIBER_TYPE, R.ALERTTYPE, T.OBJECT_STATUS, T.TXT_SUBJECT_TMPL, T.TXT_MSG_TMPL
FROM expected E CROSS JOIN locales L
LEFT JOIN DIGX_EP_EVT_REC_B R
 ON R.COD_ACT_ID = 'com.ofss.digx.cz.bea.app.sms.service.user.UserExtensionData.' || E.OP
 AND R.COD_EVENT_ID = E.EVENT_ID AND R.TXT_DEST_TYP = E.CHANNEL AND R.LOCALE = L.LOCALE
LEFT JOIN DIGX_EP_MSG_TMPL_B T
 ON T.COD_TMPL_ID = R.COD_MSG_TMPL_ID AND T.DETERMINANT_VALUE = 'OBDX_BU'
ORDER BY E.EVENT_ID, L.LOCALE;

-- Existing field mappings should resolve getters on UserProfUpdateActivityLogDTO (851 inherits them).
SELECT S.COD_ACT_ID, S.COD_MESS_TMPL_ID, S.COD_ATTR_ID, A.TYP_DATA_SRC, A.REF_FIELD_DEFN_ID
FROM DIGX_EP_MSG_SRC_B S JOIN DIGX_MD_SERVICE_ATTR A ON A.COD_SERVICE_ATTR_ID = S.COD_SERVICE_ATTR_ID
WHERE S.COD_MESS_TMPL_ID IN (
  SELECT COD_MSG_TMPL_ID FROM DIGX_EP_EVT_REC_B
  WHERE COD_EVENT_ID IN ('INFO_UPDATE_BY_CORP_ADMIN','USER_EMAIL_ADDRESS_UPDATE',
                        'USER_MOBILE_NUMBER_UPDATED_REMINDER','CORPORATEPLUS_WELCOME_MAIL'))
ORDER BY S.COD_ACT_ID, S.COD_MESS_TMPL_ID, S.COD_ATTR_ID;

-- Chinese subject/content are reused from existing BCO configuration (six non-empty values).
SELECT PROP_ID, PROP_VALUE FROM DIGX_CZ_FW_CONFIG_ALL_O
WHERE PROP_ID IN ('INFOUPDATE_EMAIL_UPDATE_MAILSUBJ','INFOUPDATE_EMAIL_UPDATE_MAILCONTENT',
 'INFOUPDATE_MOB_UPDATE_MAILSUBJ','INFOUPDATE_MOB_UPDATE_MAILCONTENT',
 'INFOUPDATE_EMAILMOB_UPDATE_MAILSUBJ','INFOUPDATE_EMAILMOB_UPDATE_MAILCONTENT');

-- Counts only: no contact details or body content in this operational summary.
SELECT EVENT_ID, CHANNEL, STATE, COUNT(*) ROW_COUNT
FROM DIGX_CZ_HTH_CONTACT_OUTBOX GROUP BY EVENT_ID, CHANNEL, STATE ORDER BY EVENT_ID, CHANNEL, STATE;
SELECT N.ID, N.APPROVAL_REF, N.RECIPIENT_ROLE, N.EVENT_ID, N.STATE,
       N.FALLBACK_ID, M.REFNUMBER, M.RESPONSE_STATUS, M.LAST_UPDATED_DATE
FROM DIGX_CZ_HTH_CONTACT_OUTBOX N LEFT JOIN DIGX_CZ_EMAIL_MNG M ON M.REFNUMBER = 'H851' || N.ID
ORDER BY N.CREATED_AT DESC;
