-- BCOH2H-788 / BCOH2H-790: HTH API Password lifecycle schema.
-- Execute once as HTH_BEA (or a deployment owner with direct CREATE privileges).
-- This schema never stores the HTH API Password. UAM remains the credential source of truth.
-- HTH_API_PASSWORD_CODE is populated by the Password Code Generation feature (BCOH2H-789).
-- CODE_HASH must be lowercase SHA-256 hex of UTF-8 bytes: CODE_SALT || ':' || clearCode.
-- Oracle DDL commits implicitly. Do not re-run after successful creation.

CREATE TABLE HTH_BEA.HTH_API_PASSWORD_CODE (
  ID                    VARCHAR2(36 BYTE)  NOT NULL,
  PARTY_ID              VARCHAR2(64 BYTE)  NOT NULL,
  USER_ID               VARCHAR2(255 BYTE) NOT NULL,
  PURPOSE               VARCHAR2(8 BYTE)   NOT NULL,
  CODE_HASH             VARCHAR2(64 BYTE)  NOT NULL,
  CODE_SALT             VARCHAR2(64 BYTE)  NOT NULL,
  GENERATION_REFERENCE  VARCHAR2(100 BYTE),
  STATUS                VARCHAR2(16 BYTE)  DEFAULT 'ACTIVE' NOT NULL,
  REQUEST_ID            VARCHAR2(36 BYTE),
  EXPIRES_AT            DATE               NOT NULL,
  FAILED_ATTEMPTS       NUMBER(3)          DEFAULT 0 NOT NULL,
  MAX_ATTEMPTS          NUMBER(3)          DEFAULT 5 NOT NULL,
  USED_AT               DATE,
  CREATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE         DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY       VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE      DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_STATUS         VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  OBJECT_VERSION_NUMBER NUMBER(10)         DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_API_PWD_CODE PRIMARY KEY (ID),
  CONSTRAINT FK_HTH_API_PWD_CODE_USER FOREIGN KEY (PARTY_ID, USER_ID)
    REFERENCES HTH_BEA.HTH_USER_PROFILE (PARTY_ID, CLOSE_ID),
  CONSTRAINT CK_HTH_API_PWD_PURPOSE CHECK (PURPOSE IN ('SETUP', 'RESET')),
  CONSTRAINT CK_HTH_API_PWD_CODE_ST CHECK
    (STATUS IN ('ACTIVE', 'IN_PROGRESS', 'USED', 'LOCKED', 'EXPIRED', 'REVOKED',
                'UNKNOWN')),
  CONSTRAINT CK_HTH_API_PWD_ATTEMPTS CHECK
    (FAILED_ATTEMPTS >= 0 AND MAX_ATTEMPTS > 0 AND FAILED_ATTEMPTS <= MAX_ATTEMPTS),
  CONSTRAINT CK_HTH_API_PWD_CODE_OBJ CHECK (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEA.IX_HTH_API_PWD_CODE_USER
  ON HTH_BEA.HTH_API_PASSWORD_CODE
    (PARTY_ID, USER_ID, PURPOSE, STATUS, EXPIRES_AT);

CREATE INDEX HTH_BEA.IX_HTH_API_PWD_CODE_REQ
  ON HTH_BEA.HTH_API_PASSWORD_CODE (REQUEST_ID);

-- Oracle permits multiple NULL values in a unique index. This enforces at most one live Code
-- per HTH user/purpose while allowing all consumed, expired, locked, and revoked history rows.
CREATE UNIQUE INDEX HTH_BEA.UX_HTH_API_PWD_CODE_LIVE
  ON HTH_BEA.HTH_API_PASSWORD_CODE (
    CASE WHEN OBJECT_STATUS = 'A'
              AND STATUS IN ('ACTIVE', 'IN_PROGRESS', 'UNKNOWN') THEN PARTY_ID END,
    CASE WHEN OBJECT_STATUS = 'A'
              AND STATUS IN ('ACTIVE', 'IN_PROGRESS', 'UNKNOWN') THEN USER_ID END,
    CASE WHEN OBJECT_STATUS = 'A'
              AND STATUS IN ('ACTIVE', 'IN_PROGRESS', 'UNKNOWN') THEN PURPOSE END
  );

COMMENT ON TABLE HTH_BEA.HTH_API_PASSWORD_CODE IS
  'Hashed one-time codes authorizing HTH API Password setup or reset; no clear code is stored.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.PARTY_ID IS
  'HTH corporate party owning the user.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.USER_ID IS
  'Canonical HTH CloseID without the @partyId session suffix.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.PURPOSE IS
  'SETUP or RESET; a code cannot be used for the other operation.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.CODE_HASH IS
  'Lowercase SHA-256 hex of CODE_SALT, colon, and the clear one-time code.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.CODE_SALT IS
  'Random non-secret salt used only to verify the one-time code digest.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.GENERATION_REFERENCE IS
  'Non-sensitive reference from the Password Code Generation operation (BCOH2H-789).';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.STATUS IS
  'ACTIVE, IN_PROGRESS, USED, LOCKED, EXPIRED, REVOKED, or UNKNOWN.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.REQUEST_ID IS
  'Idempotency request reserving or consuming the code.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.EXPIRES_AT IS
  'Absolute database time after which the code cannot be used.';

CREATE TABLE HTH_BEA.HTH_API_PASSWORD_STATE (
  PARTY_ID               VARCHAR2(64 BYTE)  NOT NULL,
  USER_ID                VARCHAR2(255 BYTE) NOT NULL,
  CREDENTIAL_STATUS      VARCHAR2(16 BYTE)  DEFAULT 'NOT_SETUP' NOT NULL,
  CREDENTIAL_VERSION     NUMBER(10)         DEFAULT 0 NOT NULL,
  SETUP_AT               DATE,
  LAST_RESET_AT          DATE,
  LAST_REQUEST_ID        VARCHAR2(36 BYTE),
  LAST_REFERENCE_NUMBER  VARCHAR2(100 BYTE),
  CREATED_BY             VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE          DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE       DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_STATUS          VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  OBJECT_VERSION_NUMBER  NUMBER(10)         DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_API_PWD_STATE PRIMARY KEY (PARTY_ID, USER_ID),
  CONSTRAINT FK_HTH_API_PWD_STATE_USER FOREIGN KEY (PARTY_ID, USER_ID)
    REFERENCES HTH_BEA.HTH_USER_PROFILE (PARTY_ID, CLOSE_ID),
  CONSTRAINT CK_HTH_API_PWD_STATE CHECK
    (CREDENTIAL_STATUS IN ('NOT_SETUP', 'ACTIVE', 'LOCKED', 'UNKNOWN')),
  CONSTRAINT CK_HTH_API_PWD_STATE_OBJ CHECK (OBJECT_STATUS IN ('A', 'I'))
);

COMMENT ON TABLE HTH_BEA.HTH_API_PASSWORD_STATE IS
  'Non-sensitive local projection of the UAM HTH API credential state.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_STATE.CREDENTIAL_STATUS IS
  'Cached projection only; the UAM credential status remains authoritative.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_STATE.CREDENTIAL_VERSION IS
  'Monotonic successful setup/reset counter; never contains a password version secret.';

CREATE TABLE HTH_BEA.HTH_API_PASSWORD_OPERATION (
  REQUEST_ID             VARCHAR2(36 BYTE)  NOT NULL,
  PARTY_ID               VARCHAR2(64 BYTE)  NOT NULL,
  USER_ID                VARCHAR2(255 BYTE) NOT NULL,
  OPERATION              VARCHAR2(8 BYTE)   NOT NULL,
  CODE_ID                VARCHAR2(36 BYTE)  NOT NULL,
  STATUS                 VARCHAR2(16 BYTE)  NOT NULL,
  REFERENCE_NUMBER       VARCHAR2(100 BYTE),
  CREATED_BY             VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE          DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE       DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_STATUS          VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  OBJECT_VERSION_NUMBER  NUMBER(10)         DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_API_PWD_OP PRIMARY KEY (REQUEST_ID),
  CONSTRAINT FK_HTH_API_PWD_OP_USER FOREIGN KEY (PARTY_ID, USER_ID)
    REFERENCES HTH_BEA.HTH_USER_PROFILE (PARTY_ID, CLOSE_ID),
  CONSTRAINT FK_HTH_API_PWD_OP_CODE FOREIGN KEY (CODE_ID)
    REFERENCES HTH_BEA.HTH_API_PASSWORD_CODE (ID),
  CONSTRAINT CK_HTH_API_PWD_OP_TYPE CHECK (OPERATION IN ('SETUP', 'RESET')),
  CONSTRAINT CK_HTH_API_PWD_OP_STATE CHECK
    (STATUS IN ('IN_PROGRESS', 'SUCCESS', 'FAILED', 'UNKNOWN')),
  CONSTRAINT CK_HTH_API_PWD_OP_OBJ CHECK (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEA.IX_HTH_API_PWD_OP_USER
  ON HTH_BEA.HTH_API_PASSWORD_OPERATION
    (PARTY_ID, USER_ID, OPERATION, CREATION_DATE);

COMMENT ON TABLE HTH_BEA.HTH_API_PASSWORD_OPERATION IS
  'Idempotency and reconciliation state for setup/reset calls to UAM.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_OPERATION.REQUEST_ID IS
  'Client-generated UUID; repeated successful requests return the original result.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_OPERATION.STATUS IS
  'UNKNOWN prevents an unsafe password rotation retry after an indeterminate UAM result.';

COMMIT;
