-- BCOH2H-788/790/1204: incremental schema over the BCOH2H-787 Code producer.
-- SQL*Plus / SQLcl: run 20260830_BCOH2H-787_HTH_API_Password/1...Schema.sql FIRST.
-- Preserves CODE_CIPHER and approval-anchored EXPIRY_TIME. Never recreates the Code table.
-- A previously deployed hash-only 788 schema is NOT compatible: stop and plan migration.
-- DDL commits implicitly; back up and validate the deployment baseline before running.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS
   WHERE OWNER = 'HTH_BEA' AND TABLE_NAME = 'HTH_API_PASSWORD_CODE'
     AND COLUMN_NAME IN ('USER_NAME', 'CODE_CIPHER', 'ATTEMPT_COUNT', 'EXPIRY_TIME', 'USED_TIME');
  IF n <> 5 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Requires the 787 ciphertext Code schema; do not drop existing Code data.');
  END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER = 'HTH_BEA'
    AND TABLE_NAME = 'HTH_API_PASSWORD_CODE' AND COLUMN_NAME = 'PURPOSE';
  IF n = 0 THEN EXECUTE IMMEDIATE
    'ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE ADD PURPOSE VARCHAR2(8 BYTE) DEFAULT ''SETUP'' NOT NULL'; END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER = 'HTH_BEA'
    AND TABLE_NAME = 'HTH_API_PASSWORD_CODE' AND COLUMN_NAME = 'REQUEST_ID';
  IF n = 0 THEN EXECUTE IMMEDIATE
    'ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE ADD REQUEST_ID VARCHAR2(36 BYTE)'; END IF;
  SELECT COUNT(*) INTO n FROM ALL_TAB_COLUMNS WHERE OWNER = 'HTH_BEA'
    AND TABLE_NAME = 'HTH_API_PASSWORD_CODE' AND COLUMN_NAME = 'MAX_ATTEMPTS';
  IF n = 0 THEN EXECUTE IMMEDIATE
    'ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE ADD MAX_ATTEMPTS NUMBER(3) DEFAULT 5 NOT NULL'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_CONSTRAINTS WHERE OWNER = 'HTH_BEA'
    AND CONSTRAINT_NAME = 'CK_HTH_API_PWD_CODE_STATUS';
  IF n > 0 THEN EXECUTE IMMEDIATE
    'ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE DROP CONSTRAINT CK_HTH_API_PWD_CODE_STATUS'; END IF;
  EXECUTE IMMEDIATE q'~ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE ADD CONSTRAINT
    CK_HTH_API_PWD_CODE_STATUS CHECK (STATUS IN
      ('PENDING','ACTIVE','USED','EXPIRED','INVALID','IN_PROGRESS','UNKNOWN'))~';
  SELECT COUNT(*) INTO n FROM ALL_CONSTRAINTS WHERE OWNER = 'HTH_BEA'
    AND CONSTRAINT_NAME = 'CK_HTH_API_PWD_PURPOSE';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE ADD CONSTRAINT
    CK_HTH_API_PWD_PURPOSE CHECK (PURPOSE IN ('SETUP','RESET'))~'; END IF;
  SELECT COUNT(*) INTO n FROM ALL_CONSTRAINTS WHERE OWNER = 'HTH_BEA'
    AND CONSTRAINT_NAME = 'CK_HTH_API_PWD_ATTEMPTS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~ALTER TABLE HTH_BEA.HTH_API_PASSWORD_CODE ADD CONSTRAINT
    CK_HTH_API_PWD_ATTEMPTS CHECK (ATTEMPT_COUNT >= 0 AND MAX_ATTEMPTS > 0
      AND ATTEMPT_COUNT <= MAX_ATTEMPTS)~'; END IF;
END;
/

-- Detect duplicate live codes before creating the unique index; do not silently invalidate data.
-- Bare and @party-qualified usernames represent the same principal.
DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER = 'HTH_BEA'
    AND INDEX_NAME = 'UX_HTH_API_PWD_CODE_LIVE';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX HTH_BEA.UX_HTH_API_PWD_CODE_LIVE
    ON HTH_BEA.HTH_API_PASSWORD_CODE (
      CASE WHEN OBJECT_STATUS = 'A' AND STATUS IN ('ACTIVE','IN_PROGRESS','UNKNOWN') THEN PARTY_ID END,
      CASE WHEN OBJECT_STATUS = 'A' AND STATUS IN ('ACTIVE','IN_PROGRESS','UNKNOWN') THEN
        CASE WHEN SUBSTR(USER_NAME, -LENGTH(PARTY_ID)-1) = '@' || PARTY_ID
          THEN SUBSTR(USER_NAME, 1, LENGTH(USER_NAME)-LENGTH(PARTY_ID)-1) ELSE USER_NAME END END,
      CASE WHEN OBJECT_STATUS = 'A' AND STATUS IN ('ACTIVE','IN_PROGRESS','UNKNOWN') THEN PURPOSE END)~';
  END IF;
END;
/

COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.PURPOSE IS
  'SETUP by default for 787 creation; RESET must be explicitly requested by reset-code generation.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.REQUEST_ID IS
  'Request holding this code IN_PROGRESS/UNKNOWN or consuming it to USED.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.MAX_ATTEMPTS IS
  'Maximum failed verification attempts; INVALID when exhausted.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.STATUS IS
  '787 PENDING/ACTIVE/USED/EXPIRED/INVALID, plus IN_PROGRESS/UNKNOWN for UAM operation safety.';

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER = 'HTH_BEA' AND TABLE_NAME = 'HTH_API_PASSWORD_STATE';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE HTH_BEA.HTH_API_PASSWORD_STATE (
  PARTY_ID               VARCHAR2(64 BYTE)  NOT NULL,
  USER_ID                VARCHAR2(255 BYTE) NOT NULL,
  CREDENTIAL_STATUS      VARCHAR2(16 BYTE)  DEFAULT 'NOT_SETUP' NOT NULL,
  CREDENTIAL_VERSION     NUMBER(10)         DEFAULT 0 NOT NULL,
  SETUP_AT               DATE,
  LAST_RESET_AT          DATE,
  LAST_REQUEST_ID        VARCHAR2(36 BYTE),
  LAST_REFERENCE_NUMBER  VARCHAR2(100 BYTE),
  CREATED_BY             VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE          DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE       DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_STATUS          VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  OBJECT_VERSION_NUMBER  NUMBER(10)         DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_API_PWD_STATE PRIMARY KEY (PARTY_ID, USER_ID),
  CONSTRAINT FK_HTH_API_PWD_STATE_USER FOREIGN KEY (PARTY_ID, USER_ID)
    REFERENCES HTH_BEA.HTH_USER_PROFILE (PARTY_ID, CLOSE_ID),
  CONSTRAINT CK_HTH_API_PWD_STATE CHECK
    (CREDENTIAL_STATUS IN ('NOT_SETUP', 'ACTIVE', 'LOCKED', 'UNKNOWN')),
  CONSTRAINT CK_HTH_API_PWD_STATE_OBJ CHECK (OBJECT_STATUS IN ('A', 'I'))
)~'; END IF;
END;
/

COMMENT ON TABLE HTH_BEA.HTH_API_PASSWORD_STATE IS
  'Non-sensitive local projection of the UAM HTH API credential state.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_STATE.CREDENTIAL_STATUS IS
  'Cached projection only; the UAM credential status remains authoritative.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_STATE.CREDENTIAL_VERSION IS
  'Monotonic successful setup/reset counter; never contains a password version secret.';

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER = 'HTH_BEA' AND TABLE_NAME = 'HTH_API_PASSWORD_OPERATION';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE HTH_BEA.HTH_API_PASSWORD_OPERATION (
  REQUEST_ID             VARCHAR2(36 BYTE)  NOT NULL,
  PARTY_ID               VARCHAR2(64 BYTE)  NOT NULL,
  USER_ID                VARCHAR2(255 BYTE) NOT NULL,
  OPERATION              VARCHAR2(8 BYTE)   NOT NULL,
  CODE_ID                VARCHAR2(36 BYTE)  NOT NULL,
  STATUS                 VARCHAR2(16 BYTE)  NOT NULL,
  REFERENCE_NUMBER       VARCHAR2(100 BYTE),
  CREATED_BY             VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE          DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE       DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_STATUS          VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  OBJECT_VERSION_NUMBER  NUMBER(10)         DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_API_PWD_OP PRIMARY KEY (REQUEST_ID),
  CONSTRAINT FK_HTH_API_PWD_OP_USER FOREIGN KEY (PARTY_ID, USER_ID)
    REFERENCES HTH_BEA.HTH_USER_PROFILE (PARTY_ID, CLOSE_ID),
  CONSTRAINT FK_HTH_API_PWD_OP_CODE FOREIGN KEY (CODE_ID)
    REFERENCES HTH_BEA.HTH_API_PASSWORD_CODE (ID),
  CONSTRAINT CK_HTH_API_PWD_OP_TYPE CHECK (OPERATION IN ('SETUP', 'RESET')),
  CONSTRAINT CK_HTH_API_PWD_OP_STATE CHECK
    (STATUS IN ('IN_PROGRESS', 'SUCCESS', 'FAILED', 'UNKNOWN')),
  CONSTRAINT CK_HTH_API_PWD_OP_OBJ CHECK (OBJECT_STATUS IN ('A', 'I'))
)~'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM ALL_INDEXES WHERE OWNER = 'HTH_BEA' AND INDEX_NAME = 'IX_HTH_API_PWD_OP_USER';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE INDEX HTH_BEA.IX_HTH_API_PWD_OP_USER
  ON HTH_BEA.HTH_API_PASSWORD_OPERATION
    (PARTY_ID, USER_ID, OPERATION, CREATION_DATE)~'; END IF;
END;
/

COMMENT ON TABLE HTH_BEA.HTH_API_PASSWORD_OPERATION IS
  'Idempotency and reconciliation state for setup/reset calls to UAM.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_OPERATION.REQUEST_ID IS
  'Client-generated UUID; repeated successful requests return the original result.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_OPERATION.STATUS IS
  'UNKNOWN prevents an unsafe password rotation retry after an indeterminate UAM result.';

COMMIT;
