-- Oracle SQL/PLSQL; no SQL*Plus commands or substitution variables.
-- Execute each complete DECLARE/BEGIN ... END; block as one statement (no slash).
-- BCOH2H-788 / 790: DATABASE by default, UAM only when explicitly selected.
-- Run 1 Schema, 2 Process and 3 Permission first. Code key and storage settings commit together.
-- DATABASE needs no UAM URL, client ID or APIC credentials.
-- UAM requires confirmed HTTPS URL and all three paths; no guessed endpoint defaults.
-- Changing the backend does NOT migrate passwords. Stop traffic and plan credential migration first.
-- On first deployment, provide the original Code key locally; never commit a populated script.
-- On rerun, NULL reuses the configured key; a different supplied key is rejected.
-- APIC secret configuration is preserved.

DECLARE
  V_STORAGE_BACKEND VARCHAR2(8) := 'DATABASE';
  V_SERVICE_URL VARCHAR2(1000) := NULL;
  V_STATUS_PATH VARCHAR2(500) := NULL;
  V_SETUP_PATH VARCHAR2(500) := NULL;
  V_RESET_PATH VARCHAR2(500) := NULL;
  V_ORIGINAL_KEY VARCHAR2(4000) := NULL;
  V_EXISTING_KEY VARCHAR2(4000);
  V_KEY_BYTES RAW(2000);
  V_KEY_COUNT NUMBER;
BEGIN
  SAVEPOINT HTH_API_PASSWORD_CONFIG;
  V_STORAGE_BACKEND := UPPER(TRIM(V_STORAGE_BACKEND));
  IF V_STORAGE_BACKEND IS NULL OR V_STORAGE_BACKEND NOT IN ('DATABASE', 'UAM') THEN
    RAISE_APPLICATION_ERROR(-20021, 'STORAGE_BACKEND must be DATABASE or UAM.');
  END IF;
  IF V_STORAGE_BACKEND = 'UAM' THEN
    IF V_SERVICE_URL IS NULL OR V_SERVICE_URL NOT LIKE 'https://%'
       OR V_SERVICE_URL LIKE '%CHANGE_ME%'
       OR V_STATUS_PATH IS NULL OR V_SETUP_PATH IS NULL OR V_RESET_PATH IS NULL
       OR V_STATUS_PATH NOT LIKE '/%' OR V_SETUP_PATH NOT LIKE '/%' OR V_RESET_PATH NOT LIKE '/%' THEN
      RAISE_APPLICATION_ERROR(-20001, 'UAM requires the approved HTTPS URL and status/setup/reset paths.');
    END IF;
  END IF;
  -- Preserve the configured key so existing Code ciphertext remains decryptable.
  V_ORIGINAL_KEY := TRIM(V_ORIGINAL_KEY);
  SELECT COUNT(*) INTO V_KEY_COUNT FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
   WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
     AND PROP_ID = 'HTH_API_PWD_CODE_CIPHER_KEY';
  IF V_KEY_COUNT > 1 THEN
    RAISE_APPLICATION_ERROR(-20013, 'Duplicate Code key configuration; resolve before deployment.');
  ELSIF V_KEY_COUNT = 1 THEN
    SELECT TRIM(PROP_VALUE) INTO V_EXISTING_KEY FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
     WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
       AND PROP_ID = 'HTH_API_PWD_CODE_CIPHER_KEY';
    IF V_EXISTING_KEY IS NULL THEN
      RAISE_APPLICATION_ERROR(-20012, 'Existing Code key is empty; resolve before deployment.');
    END IF;
    IF V_ORIGINAL_KEY IS NOT NULL AND V_ORIGINAL_KEY <> V_EXISTING_KEY THEN
      RAISE_APPLICATION_ERROR(-20012, 'Existing Code key differs; refusing to overwrite.');
    END IF;
    V_ORIGINAL_KEY := V_EXISTING_KEY;
  END IF;
  IF V_ORIGINAL_KEY IS NULL
     OR NOT REGEXP_LIKE(V_ORIGINAL_KEY, '^[A-Za-z0-9+/]{43}=$', 'c') THEN
    RAISE_APPLICATION_ERROR(-20010, 'Provide the original Base64 AES-256 Code key locally.');
  END IF;
  V_KEY_BYTES := UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW(V_ORIGINAL_KEY));
  IF UTL_RAW.LENGTH(V_KEY_BYTES) <> 32 THEN
    RAISE_APPLICATION_ERROR(-20011, 'The Code key must decode to 32 bytes.');
  END IF;
  IF V_KEY_COUNT = 0 THEN
    INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
    VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PWD_CODE_CIPHER_KEY', V_ORIGINAL_KEY);
  END IF;


DELETE FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
 WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
   AND PROP_ID IN (
     'HTH_API_PASSWORD.STORAGE_BACKEND',
     'HTH_API_PASSWORD.ADAPTER_CLASS',
     'HTH_API_PASSWORD.ENABLED',
     'HTH_API_PASSWORD.SERVICE_URL',
     'HTH_API_PASSWORD.STATUS_PATH',
     'HTH_API_PASSWORD.SETUP_PATH',
     'HTH_API_PASSWORD.RESET_PATH',
     'HTH_API_PASSWORD.CHANNEL',
     'HTH_API_PASSWORD.CONNECT_TIMEOUT_MS',
     'HTH_API_PASSWORD.READ_TIMEOUT_MS',
     'HTH_API_PASSWORD.POLICY_MIN_LENGTH',
     'HTH_API_PASSWORD.POLICY_MAX_LENGTH',
     'HTH_API_PASSWORD.POLICY_NUMERIC_REQUIRED',
     'HTH_API_PASSWORD.POLICY_ALPHABET_REQUIRED',
     'HTH_API_PASSWORD.POLICY_SPECIAL_ALLOWED',
     'HTH_API_PASSWORD.POLICY_SPACES_ALLOWED'
   );

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.STORAGE_BACKEND', V_STORAGE_BACKEND);

-- Single-row INSERT supports the configuration view; INSERT ALL does not.
INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.ADAPTER_CLASS',
          'com.ofss.digx.cz.bea.extxface.hosttohost.adapter.impl.HthApiCredentialAdapter');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.ENABLED', 'true');

IF V_STORAGE_BACKEND = 'UAM' THEN
INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.SERVICE_URL',
          V_SERVICE_URL);

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.STATUS_PATH',
          V_STATUS_PATH);

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.SETUP_PATH',
          V_SETUP_PATH);

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.RESET_PATH',
          V_RESET_PATH);

END IF;

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.CHANNEL', 'BCO');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.CONNECT_TIMEOUT_MS', '5000');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.READ_TIMEOUT_MS', '15000');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_MIN_LENGTH', '8');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_MAX_LENGTH', '16');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_NUMERIC_REQUIRED', '2');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_ALPHABET_REQUIRED', '1');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_SPECIAL_ALLOWED', 'false');

INSERT INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_SPACES_ALLOWED', 'false');

-- Repository factories resolve the same local implementation for base and OBDX_BU settings.
DELETE FROM DIGX_FW_CONFIG_ALL_B
 WHERE CATEGORY_ID = 'repositoryadapterconfig' AND PROP_ID = 'HTH_API_PASSWORD_CREDENTIAL_LOCAL_REPOSITORY_ADAPTER';
INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS,
  SUMMARY_TEXT, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE,
  OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
VALUES ('HTH_API_PASSWORD_CREDENTIAL_LOCAL_REPOSITORY_ADAPTER', 'repositoryadapterconfig',
 'com.ofss.digx.cz.bea.domain.hosttohost.entity.repository.adapter.LocalHthApiPasswordCredentialRepositoryAdapter',
 'N', 'HTH API password credential persistence', 'HTH API password credential repository',
 'ofssuser', SYSDATE, 'ofssuser', SYSDATE, NULL, 1, 'N', NULL);
DELETE FROM DIGX_FW_CONFIG_ALL_O
 WHERE PREFERENCE_NAME = 'RepositoryAdapterFactories' AND PROP_ID = 'HTH_API_PASSWORD_CREDENTIAL_LOCAL_REPOSITORY_ADAPTER';
INSERT INTO DIGX_FW_CONFIG_ALL_O
 (PROP_ID, PREFERENCE_NAME, PROP_VALUE, DETERMINANT_VALUE, CREATED_BY,
  CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES ('HTH_API_PASSWORD_CREDENTIAL_LOCAL_REPOSITORY_ADAPTER', 'RepositoryAdapterFactories',
 'com.ofss.digx.cz.bea.domain.hosttohost.entity.repository.adapter.LocalHthApiPasswordCredentialRepositoryAdapter',
 'OBDX_BU', 'ofssuser', SYSDATE, 'ofssuser', SYSDATE);

DELETE FROM DIGX_FW_CONFIG_ALL_B
 WHERE CATEGORY_ID = 'repositoryadapterconfig' AND PROP_ID = 'HTH_API_PASSWORD_STATE_LOCAL_REPOSITORY_ADAPTER';
INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS,
  SUMMARY_TEXT, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE,
  OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
VALUES ('HTH_API_PASSWORD_STATE_LOCAL_REPOSITORY_ADAPTER', 'repositoryadapterconfig',
 'com.ofss.digx.cz.bea.domain.hosttohost.entity.repository.adapter.LocalHthApiPasswordStateRepositoryAdapter',
 'N', 'HTH API password state persistence', 'HTH API password state repository',
 'ofssuser', SYSDATE, 'ofssuser', SYSDATE, NULL, 1, 'N', NULL);
DELETE FROM DIGX_FW_CONFIG_ALL_O
 WHERE PREFERENCE_NAME = 'RepositoryAdapterFactories' AND PROP_ID = 'HTH_API_PASSWORD_STATE_LOCAL_REPOSITORY_ADAPTER';
INSERT INTO DIGX_FW_CONFIG_ALL_O
 (PROP_ID, PREFERENCE_NAME, PROP_VALUE, DETERMINANT_VALUE, CREATED_BY,
  CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES ('HTH_API_PASSWORD_STATE_LOCAL_REPOSITORY_ADAPTER', 'RepositoryAdapterFactories',
 'com.ofss.digx.cz.bea.domain.hosttohost.entity.repository.adapter.LocalHthApiPasswordStateRepositoryAdapter',
 'OBDX_BU', 'ofssuser', SYSDATE, 'ofssuser', SYSDATE);

DELETE FROM DIGX_FW_CONFIG_ALL_B
 WHERE CATEGORY_ID = 'repositoryadapterconfig' AND PROP_ID = 'HTH_API_PASSWORD_OPERATION_LOCAL_REPOSITORY_ADAPTER';
INSERT INTO DIGX_FW_CONFIG_ALL_B
 (PROP_ID, CATEGORY_ID, PROP_VALUE, FACTORY_SHIPPED_FLAG, PROP_COMMENTS,
  SUMMARY_TEXT, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE,
  OBJECT_STATUS, OBJECT_VERSION_NUMBER, EDITABLE, CATEGORY_DESCRIPTION)
VALUES ('HTH_API_PASSWORD_OPERATION_LOCAL_REPOSITORY_ADAPTER', 'repositoryadapterconfig',
 'com.ofss.digx.cz.bea.domain.hosttohost.entity.repository.adapter.LocalHthApiPasswordOperationRepositoryAdapter',
 'N', 'HTH API password operation persistence', 'HTH API password operation repository',
 'ofssuser', SYSDATE, 'ofssuser', SYSDATE, NULL, 1, 'N', NULL);
DELETE FROM DIGX_FW_CONFIG_ALL_O
 WHERE PREFERENCE_NAME = 'RepositoryAdapterFactories' AND PROP_ID = 'HTH_API_PASSWORD_OPERATION_LOCAL_REPOSITORY_ADAPTER';
INSERT INTO DIGX_FW_CONFIG_ALL_O
 (PROP_ID, PREFERENCE_NAME, PROP_VALUE, DETERMINANT_VALUE, CREATED_BY,
  CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE)
VALUES ('HTH_API_PASSWORD_OPERATION_LOCAL_REPOSITORY_ADAPTER', 'RepositoryAdapterFactories',
 'com.ofss.digx.cz.bea.domain.hosttohost.entity.repository.adapter.LocalHthApiPasswordOperationRepositoryAdapter',
 'OBDX_BU', 'ofssuser', SYSDATE, 'ofssuser', SYSDATE);

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO HTH_API_PASSWORD_CONFIG;
    RAISE;
END;

SELECT CATEGORY_ID, PROP_ID,
       CASE WHEN PROP_ID LIKE '%SECRET%' OR PROP_ID LIKE '%CIPHER_KEY%' THEN '[PROTECTED]' ELSE PROP_VALUE END AS PROP_VALUE
  FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
 WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
 ORDER BY PROP_ID;
