-- BCOH2H-788 / BCOH2H-790: UAM HTH API credential adapter configuration.
-- Execute after replacing HTH_API_PASSWORD_SERVICE_URL with the approved environment URL.
-- The URL must be HTTPS and must not end with a credential operation path.
-- APIC client id/secret default to the existing DSPApi configuration and are not duplicated here.
-- If UAM uses different APIC credentials, provision HTH_API_PASSWORD.APIC_CLIENT_ID and
-- HTH_API_PASSWORD.APIC_CLIENT_SECRET through the approved secret/configuration process.
-- Re-runnable. Before enabling the feature, provision HTH_API_PWD_CODE_CIPHER_KEY
-- under HthApiCredentialAdapterConfig using the approved secret configuration mechanism.
-- It must be the SAME Base64 AES-256 key used for existing 787 CODE_CIPHER records.
-- This script does not overwrite the key. There is no hard-coded fallback.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE HTH_API_PASSWORD_SERVICE_URL = https://CHANGE_ME.example.invalid

DECLARE
  V_SERVICE_URL VARCHAR2(1000) := '&HTH_API_PASSWORD_SERVICE_URL';
  V_KEY_COUNT NUMBER;
BEGIN
  IF V_SERVICE_URL LIKE '%CHANGE_ME%'
     OR V_SERVICE_URL NOT LIKE 'https://%' THEN
    RAISE_APPLICATION_ERROR(-20001,
      'Set HTH_API_PASSWORD_SERVICE_URL to the approved HTTPS UAM base URL before deployment.');
  END IF;
  SELECT COUNT(*) INTO V_KEY_COUNT FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
   WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
     AND PROP_ID = 'HTH_API_PWD_CODE_CIPHER_KEY'
     AND PROP_VALUE IS NOT NULL;
  IF V_KEY_COUNT <> 1 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Provision the existing 787 cipher key before enabling API password self service.');
  END IF;
END;
/

DELETE FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
 WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
   AND PROP_ID IN (
     'HTH_API_PASSWORD.ADAPTER_CLASS',
     'HTH_API_PASSWORD.ENABLED',
     'HTH_API_PASSWORD.SERVICE_URL',
     'HTH_API_PASSWORD.STATUS_PATH',
     'HTH_API_PASSWORD.SETUP_PATH',
     'HTH_API_PASSWORD.RESET_PATH',
     'HTH_API_PASSWORD.CHANNEL',
     'HTH_API_PASSWORD.CONNECT_TIMEOUT_MS',
     'HTH_API_PASSWORD.READ_TIMEOUT_MS',
     'HTH_API_PASSWORD.POLICY_MIN_LENGTH',
     'HTH_API_PASSWORD.POLICY_MAX_LENGTH',
     'HTH_API_PASSWORD.POLICY_NUMERIC_REQUIRED',
     'HTH_API_PASSWORD.POLICY_ALPHABET_REQUIRED',
     'HTH_API_PASSWORD.POLICY_SPECIAL_ALLOWED',
     'HTH_API_PASSWORD.POLICY_SPACES_ALLOWED'
   );

INSERT ALL
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.ADAPTER_CLASS',
          'com.ofss.digx.cz.bea.extxface.hosttohost.adapter.impl.HthApiCredentialAdapter')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.ENABLED', 'true')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.SERVICE_URL',
          '&HTH_API_PASSWORD_SERVICE_URL')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.STATUS_PATH',
          '/uam/hth/users/password/status')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.SETUP_PATH',
          '/uam/hth/users/password')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.RESET_PATH',
          '/uam/hth/users/password/reset')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.CHANNEL', 'BCO')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.CONNECT_TIMEOUT_MS', '5000')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.READ_TIMEOUT_MS', '15000')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_MIN_LENGTH', '8')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_MAX_LENGTH', '16')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_NUMERIC_REQUIRED', '2')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_ALPHABET_REQUIRED', '1')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_SPECIAL_ALLOWED', 'false')
  INTO DIGX_FW_CONFIG_ADAPTER_PROP_V (CATEGORY_ID, PROP_ID, PROP_VALUE)
  VALUES ('HthApiCredentialAdapterConfig', 'HTH_API_PASSWORD.POLICY_SPACES_ALLOWED', 'false')
SELECT 1 FROM DUAL;

COMMIT;

SELECT CATEGORY_ID, PROP_ID,
       CASE WHEN PROP_ID LIKE '%SECRET%' OR PROP_ID LIKE '%CIPHER_KEY%' THEN '[PROTECTED]' ELSE PROP_VALUE END AS PROP_VALUE
  FROM DIGX_FW_CONFIG_ADAPTER_PROP_V
 WHERE CATEGORY_ID = 'HthApiCredentialAdapterConfig'
 ORDER BY PROP_ID;

UNDEFINE HTH_API_PASSWORD_SERVICE_URL
