-- Oracle SQL/PLSQL; execute the complete BEGIN ... END; block as one statement.
-- Run in the OBDX configuration schema; no SQL*Plus commands or slash delimiter.
-- 789: Code approval emails to user/company, deduplicated by the service.
-- 1204/1205: successful setup/reset user email and SMS, like BCO Login PIN reset.
-- Uses the existing BCO event/action/recipient dispatch mechanism and retry policy.
-- No passwords or Code values are included in templates. Re-runnable.

BEGIN
  SAVEPOINT HTH_API_PASSWORD_CONFIG;

-- Activities are parents of event mappings; preserve their identity on rerun.
-- PC / A / CZ follows the existing BCO Login PIN notification Activity registration.
UPDATE DIGX_EP_ACT_B
   SET TXT_ACT_NAME = 'HostToHostApiPassword.setup',
       TXT_ACT_DESC = 'Set up HTH API Password', MODULE_TYPE = 'PC',
       OBJECT_STATUS = 'A', DOMAIN_OBJECT_EXTN = 'CZ',
       LAST_UPDATED_BY = USER, LAST_UPDATED_DATE = SYSDATE,
       OBJECT_VERSION_NUMBER = NVL(OBJECT_VERSION_NUMBER, 0) + 1
 WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup';

INSERT INTO DIGX_EP_ACT_B
  (COD_ACT_ID, TXT_ACT_NAME, TXT_ACT_DESC, MODULE_TYPE, FLG_IP_REQD, FLG_OP_REQD,
   FLG_LOG_REQD, TXT_LOG_CLASS, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY,
   LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
SELECT 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup',
       'HostToHostApiPassword.setup', 'Set up HTH API Password',
       'PC', NULL, NULL, NULL, NULL, USER, SYSDATE, USER, SYSDATE, 1, 'A', 'CZ'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM DIGX_EP_ACT_B
                   WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup');

UPDATE DIGX_EP_ACT_B
   SET TXT_ACT_NAME = 'HostToHostApiPassword.reset',
       TXT_ACT_DESC = 'Reset HTH API Password', MODULE_TYPE = 'PC',
       OBJECT_STATUS = 'A', DOMAIN_OBJECT_EXTN = 'CZ',
       LAST_UPDATED_BY = USER, LAST_UPDATED_DATE = SYSDATE,
       OBJECT_VERSION_NUMBER = NVL(OBJECT_VERSION_NUMBER, 0) + 1
 WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset';

INSERT INTO DIGX_EP_ACT_B
  (COD_ACT_ID, TXT_ACT_NAME, TXT_ACT_DESC, MODULE_TYPE, FLG_IP_REQD, FLG_OP_REQD,
   FLG_LOG_REQD, TXT_LOG_CLASS, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY,
   LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
SELECT 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset',
       'HostToHostApiPassword.reset', 'Reset HTH API Password',
       'PC', NULL, NULL, NULL, NULL, USER, SYSDATE, USER, SYSDATE, 1, 'A', 'CZ'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM DIGX_EP_ACT_B
                   WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset');

UPDATE DIGX_EP_ACT_B
   SET TXT_ACT_NAME = 'HostToHostApiPassword.activateOnUserApproval',
       TXT_ACT_DESC = 'Approve HTH API Password Code', MODULE_TYPE = 'PC',
       OBJECT_STATUS = 'A', DOMAIN_OBJECT_EXTN = 'CZ',
       LAST_UPDATED_BY = USER, LAST_UPDATED_DATE = SYSDATE,
       OBJECT_VERSION_NUMBER = NVL(OBJECT_VERSION_NUMBER, 0) + 1
 WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval';

INSERT INTO DIGX_EP_ACT_B
  (COD_ACT_ID, TXT_ACT_NAME, TXT_ACT_DESC, MODULE_TYPE, FLG_IP_REQD, FLG_OP_REQD,
   FLG_LOG_REQD, TXT_LOG_CLASS, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY,
   LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
SELECT 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval',
       'HostToHostApiPassword.activateOnUserApproval', 'Approve HTH API Password Code',
       'PC', NULL, NULL, NULL, NULL, USER, SYSDATE, USER, SYSDATE, 1, 'A', 'CZ'
  FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM DIGX_EP_ACT_B
                   WHERE COD_ACT_ID = 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval');

DELETE FROM DIGX_EP_EVT_REC_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_SETUP_SUCCESS';

DELETE FROM DIGX_EP_ACT_EVT_ACN_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_SETUP_SUCCESS';

DELETE FROM DIGX_EP_ACT_EVT_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_SETUP_SUCCESS';

DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN (
  'HTH_API_PWD_SETUP_USER_EMAIL_en',
  'HTH_API_PWD_SETUP_USER_EMAIL_zh-Hans-CN',
  'HTH_API_PWD_SETUP_USER_EMAIL_zh-Hant',
  'HTH_API_PWD_SETUP_USER_SMS_en',
  'HTH_API_PWD_SETUP_USER_SMS_zh-Hans-CN',
  'HTH_API_PWD_SETUP_USER_SMS_zh-Hant'
) AND DETERMINANT_VALUE = 'OBDX_BU';

DELETE FROM DIGX_PM_EVENT_ALL_B
 WHERE EVENT_CODE = 'HTH_API_PASSWORD_SETUP_SUCCESS';

INSERT INTO DIGX_PM_EVENT_ALL_B
  (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE,
   FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY, ACCT_DOMAIN_CATEGORY, ALERTS_FLAG,
   FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
   REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE,
   DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES
  ('HTH_API_PASSWORD_SETUP_SUCCESS', 'HTH API Password setup user notification',
   NULL, NULL, NULL, NULL, NULL, NULL, 'Y', 'N', 'N', 'N', 'N', NULL, 'N', 'N',
   NULL, NULL, 'N', 'N', 'N');

INSERT INTO DIGX_EP_ACT_EVT_B
  (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP,
   DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup',
   'HTH_API_PASSWORD_SETUP_SUCCESS', 'HTH API Password setup user notification',
   'OTHER', 'ONLINE', 'CZ');

INSERT INTO DIGX_EP_ACT_EVT_ACN_B
  (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE,
   COD_DEC_ID, FLG_CONDITIONAL, COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY,
   CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
   NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE,
   ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup',
   'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'N', NULL, '0', 'N', '1',
   'HTH API Password SETUP USER', 'superadmin', SYSDATE,
   'superadmin', SYSDATE, 1, 0, 'N', DATE '2099-12-31',
   'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_SETUP_USER_EMAIL_en', 'EMAIL', 'HTH API Password SETUP_USER EMAIL en', 'SETUP_USER', '<p>Dear Customer,</p><p>Your HTH API Password has been set up successfully.</p><p>If you did not perform this action, please contact the Bank on (852) 2211 1321.</p><p>The Bank of East Asia, Limited</p><p>This is a system-generated email. Please do not reply.</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', 'BEA Corporate Online: HTH API Password Setup Successful', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup', 'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'HTH_API_PWD_SETUP_USER_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_SETUP_USER_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH API Password SETUP_USER EMAIL zh-Hans-CN', 'SETUP_USER', '<p>尊贵的客户：</p><p>您的 HTH API 密码已成功设置。</p><p>若此操作并非由您执行，请致电 (852) 2211 1321 联络本行。</p><p>东亚银行有限公司</p><p>此电邮由系统自动发出，请勿回复。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '东亚企业网上银行：HTH API 密码设置成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup', 'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'HTH_API_PWD_SETUP_USER_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_SETUP_USER_EMAIL_zh-Hant', 'EMAIL', 'HTH API Password SETUP_USER EMAIL zh-Hant', 'SETUP_USER', '<p>尊貴的客戶：</p><p>您的 HTH API 密碼已成功設定。</p><p>若此操作並非由您執行，請致電 (852) 2211 1321 聯絡本行。</p><p>東亞銀行有限公司</p><p>此電郵由系統自動發出，請勿回覆。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '東亞企業網上銀行：HTH API 密碼設定成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup', 'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'HTH_API_PWD_SETUP_USER_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_SETUP_USER_SMS_en', 'SMS', 'HTH API Password SETUP_USER SMS en', 'SETUP_USER', 'Your HTH API Password has been set up successfully. If you did not perform this action, please contact the Bank on (852) 2211 1321.', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', 'BEA Corporate Online: HTH API Password Setup Successful', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup', 'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'HTH_API_PWD_SETUP_USER_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_SETUP_USER_SMS_zh-Hans-CN', 'SMS', 'HTH API Password SETUP_USER SMS zh-Hans-CN', 'SETUP_USER', '您的 HTH API 密码已成功设置。 若此操作并非由您执行，请致电 (852) 2211 1321 联络本行。', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '东亚企业网上银行：HTH API 密码设置成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup', 'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'HTH_API_PWD_SETUP_USER_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_SETUP_USER_SMS_zh-Hant', 'SMS', 'HTH API Password SETUP_USER SMS zh-Hant', 'SETUP_USER', '您的 HTH API 密碼已成功設定。 若此操作並非由您執行，請致電 (852) 2211 1321 聯絡本行。', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '東亞企業網上銀行：HTH API 密碼設定成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.setup', 'HTH_API_PASSWORD_SETUP_SUCCESS', 'A', 'HTH_API_PWD_SETUP_USER_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');


DELETE FROM DIGX_EP_EVT_REC_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_RESET_SUCCESS';

DELETE FROM DIGX_EP_ACT_EVT_ACN_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_RESET_SUCCESS';

DELETE FROM DIGX_EP_ACT_EVT_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_RESET_SUCCESS';

DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN (
  'HTH_API_PWD_RESET_USER_EMAIL_en',
  'HTH_API_PWD_RESET_USER_EMAIL_zh-Hans-CN',
  'HTH_API_PWD_RESET_USER_EMAIL_zh-Hant',
  'HTH_API_PWD_RESET_USER_SMS_en',
  'HTH_API_PWD_RESET_USER_SMS_zh-Hans-CN',
  'HTH_API_PWD_RESET_USER_SMS_zh-Hant'
) AND DETERMINANT_VALUE = 'OBDX_BU';

DELETE FROM DIGX_PM_EVENT_ALL_B
 WHERE EVENT_CODE = 'HTH_API_PASSWORD_RESET_SUCCESS';

INSERT INTO DIGX_PM_EVENT_ALL_B
  (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE,
   FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY, ACCT_DOMAIN_CATEGORY, ALERTS_FLAG,
   FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
   REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE,
   DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES
  ('HTH_API_PASSWORD_RESET_SUCCESS', 'HTH API Password reset user notification',
   NULL, NULL, NULL, NULL, NULL, NULL, 'Y', 'N', 'N', 'N', 'N', NULL, 'N', 'N',
   NULL, NULL, 'N', 'N', 'N');

INSERT INTO DIGX_EP_ACT_EVT_B
  (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP,
   DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset',
   'HTH_API_PASSWORD_RESET_SUCCESS', 'HTH API Password reset user notification',
   'OTHER', 'ONLINE', 'CZ');

INSERT INTO DIGX_EP_ACT_EVT_ACN_B
  (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE,
   COD_DEC_ID, FLG_CONDITIONAL, COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY,
   CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
   NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE,
   ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset',
   'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'N', NULL, '0', 'N', '1',
   'HTH API Password RESET USER', 'superadmin', SYSDATE,
   'superadmin', SYSDATE, 1, 0, 'N', DATE '2099-12-31',
   'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_RESET_USER_EMAIL_en', 'EMAIL', 'HTH API Password RESET_USER EMAIL en', 'RESET_USER', '<p>Dear Customer,</p><p>Your HTH API Password has been reset successfully.</p><p>If you did not perform this action, please contact the Bank on (852) 2211 1321.</p><p>The Bank of East Asia, Limited</p><p>This is a system-generated email. Please do not reply.</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', 'BEA Corporate Online: HTH API Password Reset Successful', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset', 'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'HTH_API_PWD_RESET_USER_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_RESET_USER_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH API Password RESET_USER EMAIL zh-Hans-CN', 'RESET_USER', '<p>尊贵的客户：</p><p>您的 HTH API 密码已成功重设。</p><p>若此操作并非由您执行，请致电 (852) 2211 1321 联络本行。</p><p>东亚银行有限公司</p><p>此电邮由系统自动发出，请勿回复。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '东亚企业网上银行：HTH API 密码重设成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset', 'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'HTH_API_PWD_RESET_USER_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_RESET_USER_EMAIL_zh-Hant', 'EMAIL', 'HTH API Password RESET_USER EMAIL zh-Hant', 'RESET_USER', '<p>尊貴的客戶：</p><p>您的 HTH API 密碼已成功重設。</p><p>若此操作並非由您執行，請致電 (852) 2211 1321 聯絡本行。</p><p>東亞銀行有限公司</p><p>此電郵由系統自動發出，請勿回覆。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '東亞企業網上銀行：HTH API 密碼重設成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset', 'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'HTH_API_PWD_RESET_USER_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_RESET_USER_SMS_en', 'SMS', 'HTH API Password RESET_USER SMS en', 'RESET_USER', 'Your HTH API Password has been reset successfully. If you did not perform this action, please contact the Bank on (852) 2211 1321.', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', 'BEA Corporate Online: HTH API Password Reset Successful', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset', 'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'HTH_API_PWD_RESET_USER_SMS_en', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_RESET_USER_SMS_zh-Hans-CN', 'SMS', 'HTH API Password RESET_USER SMS zh-Hans-CN', 'RESET_USER', '您的 HTH API 密码已成功重设。 若此操作并非由您执行，请致电 (852) 2211 1321 联络本行。', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '东亚企业网上银行：HTH API 密码重设成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset', 'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'HTH_API_PWD_RESET_USER_SMS_zh-Hans-CN', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_RESET_USER_SMS_zh-Hant', 'SMS', 'HTH API Password RESET_USER SMS zh-Hant', 'RESET_USER', '您的 HTH API 密碼已成功重設。 若此操作並非由您執行，請致電 (852) 2211 1321 聯絡本行。', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '東亞企業網上銀行：HTH API 密碼重設成功', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.reset', 'HTH_API_PASSWORD_RESET_SUCCESS', 'A', 'HTH_API_PWD_RESET_USER_SMS_zh-Hant', 'SMS', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');


DELETE FROM DIGX_EP_EVT_REC_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT';

DELETE FROM DIGX_EP_ACT_EVT_ACN_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT';

DELETE FROM DIGX_EP_ACT_EVT_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT';

DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN (
  'HTH_API_PWD_CODE_USER_EMAIL_en',
  'HTH_API_PWD_CODE_USER_EMAIL_zh-Hans-CN',
  'HTH_API_PWD_CODE_USER_EMAIL_zh-Hant'
) AND DETERMINANT_VALUE = 'OBDX_BU';

DELETE FROM DIGX_PM_EVENT_ALL_B
 WHERE EVENT_CODE = 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT';

INSERT INTO DIGX_PM_EVENT_ALL_B
  (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE,
   FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY, ACCT_DOMAIN_CATEGORY, ALERTS_FLAG,
   FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
   REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE,
   DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES
  ('HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'HTH API Password code user notification',
   NULL, NULL, NULL, NULL, NULL, NULL, 'Y', 'N', 'N', 'N', 'N', NULL, 'N', 'N',
   NULL, NULL, 'N', 'N', 'N');

INSERT INTO DIGX_EP_ACT_EVT_B
  (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP,
   DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval',
   'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'HTH API Password code user notification',
   'OTHER', 'ONLINE', 'CZ');

INSERT INTO DIGX_EP_ACT_EVT_ACN_B
  (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE,
   COD_DEC_ID, FLG_CONDITIONAL, COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY,
   CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
   NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE,
   ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval',
   'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'A', 'N', NULL, '0', 'N', '1',
   'HTH API Password CODE USER', 'superadmin', SYSDATE,
   'superadmin', SYSDATE, 1, 0, 'N', DATE '2099-12-31',
   'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_CODE_USER_EMAIL_en', 'EMAIL', 'HTH API Password CODE_USER EMAIL en', 'CODE_USER', '<p>Dear Customer,</p><p>Your HTH API Password Code has been approved for user #hthApiPasswordUserName#. Please contact your company’s Authorised Person or System Administrator to obtain the Code. Complete API password setup or reset before #hthApiPasswordExpiryDateTime# HKT.</p><p>If you did not perform this action, please contact the Bank on (852) 2211 1321.</p><p>The Bank of East Asia, Limited</p><p>This is a system-generated email. Please do not reply.</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', 'BEA Corporate Online: HTH API Password Code Approved', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval', 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'A', 'HTH_API_PWD_CODE_USER_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_CODE_USER_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH API Password CODE_USER EMAIL zh-Hans-CN', 'CODE_USER', '<p>尊贵的客户：</p><p>用户 #hthApiPasswordUserName# 的 HTH API 密码代码已获批准。请联络贵公司的获授权人士或系统管理员索取代码，并于香港时间 #hthApiPasswordExpiryDateTime# 前完成 API 密码设置或重设。</p><p>若此操作并非由您执行，请致电 (852) 2211 1321 联络本行。</p><p>东亚银行有限公司</p><p>此电邮由系统自动发出，请勿回复。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '东亚企业网上银行：HTH API 密码代码已获批准', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval', 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'A', 'HTH_API_PWD_CODE_USER_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_CODE_USER_EMAIL_zh-Hant', 'EMAIL', 'HTH API Password CODE_USER EMAIL zh-Hant', 'CODE_USER', '<p>尊貴的客戶：</p><p>用戶 #hthApiPasswordUserName# 的 HTH API 密碼代碼已獲批准。請聯絡貴公司的獲授權人士或系統管理員索取代碼，並於香港時間 #hthApiPasswordExpiryDateTime# 前完成 API 密碼設定或重設。</p><p>若此操作並非由您執行，請致電 (852) 2211 1321 聯絡本行。</p><p>東亞銀行有限公司</p><p>此電郵由系統自動發出，請勿回覆。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '東亞企業網上銀行：HTH API 密碼代碼已獲批准', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval', 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'A', 'HTH_API_PWD_CODE_USER_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');


DELETE FROM DIGX_EP_EVT_REC_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT';

DELETE FROM DIGX_EP_ACT_EVT_ACN_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT';

DELETE FROM DIGX_EP_ACT_EVT_B
 WHERE COD_ACT_ID =
       'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval'
   AND COD_EVENT_ID = 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT';

DELETE FROM DIGX_EP_MSG_TMPL_B WHERE COD_TMPL_ID IN (
  'HTH_API_PWD_CODE_COMPANY_EMAIL_en',
  'HTH_API_PWD_CODE_COMPANY_EMAIL_zh-Hans-CN',
  'HTH_API_PWD_CODE_COMPANY_EMAIL_zh-Hant'
) AND DETERMINANT_VALUE = 'OBDX_BU';

DELETE FROM DIGX_PM_EVENT_ALL_B
 WHERE EVENT_CODE = 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT';

INSERT INTO DIGX_PM_EVENT_ALL_B
  (EVENT_CODE, EVENT_DESC, PRODUCT_CLASS, PRICING_EVENT_TYPE, ALERT_EVENT_TYPE,
   FINANCIAL_TYPE, PRICING_DOMAIN_CATEGORY, ACCT_DOMAIN_CATEGORY, ALERTS_FLAG,
   FEES_FLAG, DOCUMENTATION_FLAG, ACCOUNTING_FLAG, ACCT_ENTRY_FLAG, DOMAIN_CODE,
   REWARDS_FLAG, RESTRICT_OFFER_FLAG, TASK_NAME, FEE_RECOGNITION_BRANCH_TYPE,
   DOMAIN_GEN_BANK_LEVEL_FLAG, DOMAIN_SPE_BANK_LEVEL_FLAG, TXN_RES_FLAG)
VALUES
  ('HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT', 'HTH API Password code company notification',
   NULL, NULL, NULL, NULL, NULL, NULL, 'Y', 'N', 'N', 'N', 'N', NULL, 'N', 'N',
   NULL, NULL, 'N', 'N', 'N');

INSERT INTO DIGX_EP_ACT_EVT_B
  (COD_ACT_ID, COD_EVENT_ID, TXT_ACT_EVT_DESC, TXT_EVT_TYP, TXT_ACT_EVT_TYP,
   DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval',
   'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT', 'HTH API Password code company notification',
   'OTHER', 'ONLINE', 'CZ');

INSERT INTO DIGX_EP_ACT_EVT_ACN_B
  (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, FLG_TRANSACTIONAL, ACTION_SOURCE,
   COD_DEC_ID, FLG_CONDITIONAL, COD_ACN_TMPL_ID, ALERT_NAME, CREATED_BY,
   CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER,
   NUM_RETRY_CNT, FLG_RETRY_ALLOWED, EXPIRY_DATE, ALERT_TYPE,
   ALERT_DISPATCH_TYPE, OBJECT_STATUS, DOMAIN_OBJECT_EXTN)
VALUES
  ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval',
   'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT', 'A', 'N', NULL, '0', 'N', '1',
   'HTH API Password CODE COMPANY', 'superadmin', SYSDATE,
   'superadmin', SYSDATE, 1, 0, 'N', DATE '2099-12-31',
   'M', 'I', 'A', 'CZ');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_CODE_COMPANY_EMAIL_en', 'EMAIL', 'HTH API Password CODE_COMPANY EMAIL en', 'CODE_COMPANY', '<p>Dear Customer,</p><p>Your company user’s HTH API Password Code has been approved for user #hthApiPasswordUserName#. Please contact your company’s Authorised Person or System Administrator to obtain the Code. Complete API password setup or reset before #hthApiPasswordExpiryDateTime# HKT.</p><p>If you did not perform this action, please contact the Bank on (852) 2211 1321.</p><p>The Bank of East Asia, Limited</p><p>This is a system-generated email. Please do not reply.</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', 'BEA Corporate Online: HTH API Password Code Approved', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval', 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT', 'A', 'HTH_API_PWD_CODE_COMPANY_EMAIL_en', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'en', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_CODE_COMPANY_EMAIL_zh-Hans-CN', 'EMAIL', 'HTH API Password CODE_COMPANY EMAIL zh-Hans-CN', 'CODE_COMPANY', '<p>尊贵的客户：</p><p>用户 #hthApiPasswordUserName# 的 HTH API 密码代码已获批准。请联络贵公司的获授权人士或系统管理员索取代码，并于香港时间 #hthApiPasswordExpiryDateTime# 前完成 API 密码设置或重设。</p><p>若此操作并非由您执行，请致电 (852) 2211 1321 联络本行。</p><p>东亚银行有限公司</p><p>此电邮由系统自动发出，请勿回复。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '东亚企业网上银行：HTH API 密码代码已获批准', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval', 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT', 'A', 'HTH_API_PWD_CODE_COMPANY_EMAIL_zh-Hans-CN', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hans-CN', NULL, 'NA', 0, NULL, 'USER');

INSERT INTO DIGX_EP_MSG_TMPL_B (COD_TMPL_ID, DESTINATION_TYPE, MSG_TMPL_NAME, MSG_TMPL_DESC, TXT_MSG_TMPL, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, OBJECT_VERSION_NUMBER, OBJECT_STATUS, TXT_SUBJECT_TMPL, DOMAIN_OBJECT_EXTN, DETERMINANT_VALUE)
VALUES ('HTH_API_PWD_CODE_COMPANY_EMAIL_zh-Hant', 'EMAIL', 'HTH API Password CODE_COMPANY EMAIL zh-Hant', 'CODE_COMPANY', '<p>尊貴的客戶：</p><p>用戶 #hthApiPasswordUserName# 的 HTH API 密碼代碼已獲批准。請聯絡貴公司的獲授權人士或系統管理員索取代碼，並於香港時間 #hthApiPasswordExpiryDateTime# 前完成 API 密碼設定或重設。</p><p>若此操作並非由您執行，請致電 (852) 2211 1321 聯絡本行。</p><p>東亞銀行有限公司</p><p>此電郵由系統自動發出，請勿回覆。</p>', 'superadmin', SYSDATE, 'superadmin', SYSDATE, 1, 'A', '東亞企業網上銀行：HTH API 密碼代碼已獲批准', 'CZ', 'OBDX_BU');

INSERT INTO DIGX_EP_EVT_REC_B (COD_ACT_ID, COD_EVENT_ID, COD_ACTION_ID, COD_MSG_TMPL_ID, TXT_DEST_TYP, COD_DEC_ID, FLG_CONDITIONAL, SUBSCRIBER_TYPE, RECIPIENT_TYPE, ALERTTYPE, DOMAIN_OBJECT_EXTN, LOCALE, GROUPE_NAME, BANKER_TYPE, AMOUNT, UNSECURE_MSG_TMPL_ID, SUBSCRIBER_VALUE)
VALUES ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostApiPassword.activateOnUserApproval', 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT', 'A', 'HTH_API_PWD_CODE_COMPANY_EMAIL_zh-Hant', 'EMAIL', '0', 'N', 'EXTERNAL', NULL, 'M', 'CZ', 'zh-Hant', NULL, 'NA', 0, NULL, 'USER');


COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO HTH_API_PASSWORD_CONFIG;
    RAISE;
END;

SELECT COD_EVENT_ID, TXT_DEST_TYP, LOCALE, COD_MSG_TMPL_ID
FROM DIGX_EP_EVT_REC_B
WHERE COD_EVENT_ID IN ('HTH_API_PASSWORD_SETUP_SUCCESS', 'HTH_API_PASSWORD_RESET_SUCCESS', 'HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT', 'HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT')
ORDER BY COD_EVENT_ID, TXT_DEST_TYP, LOCALE;
