package com.ofss.digx.cz.bea.common.constants;

public class UserExtensionDataConstants {

	public static final String SUSPEND_EMAIL_REJECTION_ON_PIN_RESET = "SUSPEND_EMAIL_REJECTION_ON_PIN_RESET";
	public static final String USER_EMAIL_ADDRESS_UPDATE = "USER_EMAIL_ADDRESS_UPDATE";
	public static final String USER_MOBILE_NUMBER_UPDATED_REMINDER = "USER_MOBILE_NUMBER_UPDATED_REMINDER";

	public static final String INFO_UPDATE_BY_CORP_ADMIN = "INFO_UPDATE_BY_CORP_ADMIN";

	public static final String CORPORATEPLUS_WELCOME_MAIL = "CORPORATEPLUS_WELCOME_MAIL";

	public static final String USER_MANAGEMENT_EDIT = "USER_MANAGEMENT_EDIT";

	public static final String USER_MANAGEMENT_CREATE = "USER_MANAGEMENT_CREATE";
	
	public static final String SUBMITTED_RESET_SIGNER_PIN_REQUEST_EMAIL_EVENT = "SUBMITTED_RESET_SIGNER_PIN_REQUEST_EMAIL_EVENT";
	
	public static final String SUBMITTED_RESET_SIGNER_PIN_REQUEST_SMS_EVENT = "SUBMITTED_RESET_SIGNER_PIN_REQUEST_SMS_EVENT";
	
	public static final String APPROVED_RESET_SIGNER_PIN_REQUEST_EMAIL_EVENT = "APPROVED_RESET_SIGNER_PIN_REQUEST_EMAIL_EVENT";
	
	public static final String APPROVED_RESET_SIGNER_PIN_REQUEST_SMS_EVENT = "APPROVED_RESET_SIGNER_PIN_REQUEST_SMS_EVENT";

	public static final String APPROVED_RESET_SIGNER_PIN_REQUEST_AP_SMS_EVENT = "APPROVED_RESET_SIGNER_PIN_REQUEST_AP_SMS_EVENT";

	public static final String REJECTED_RESET_SIGNER_PIN_REQUEST_EMAIL_EVENT = "REJECTED_RESET_SIGNER_PIN_REQUEST_EMAIL_EVENT";
	
	public static final String REJECTED_RESET_SIGNER_PIN_REQUEST_SMS_EVENT = "REJECTED_RESET_SIGNER_PIN_REQUEST_SMS_EVENT";

	public static final String REJECTED_RESET_SIGNER_PIN_REQUEST_AP_SMS_EVENT = "REJECTED_RESET_SIGNER_PIN_REQUEST_AP_SMS_EVENT";
	
	public static final String SYSTEM_REJECT_RESET_SIGNER_PIN_EMAIL_EVENT = "SYSTEM_REJECT_RESET_SIGNER_PIN_EMAIL_EVENT";
	public static final String SYSTEM_REJECT_RESET_SIGNER_PIN_SMS_EN = "SYSTEM_REJECT_RESET_SIGNER_PIN_SMS_EN";
	public static final String SYSTEM_REJECT_RESET_SIGNER_PIN_SMS_SC = "SYSTEM_REJECT_RESET_SIGNER_PIN_SMS_SC";
	public static final String SYSTEM_REJECT_RESET_SIGNER_PIN_SMS_TC = "SYSTEM_REJECT_RESET_SIGNER_PIN_SMS_TC";

	public static final String DUPLICATED_SIGNER_PIN_REQUEST_EMAIL_EVENT = "DUPLICATED_SIGNER_PIN_REQUEST_EMAIL_EVENT";
	public static final String DUPLICATED_SIGNER_PIN_REQUEST_SMS_EVENT = "DUPLICATED_SIGNER_PIN_REQUEST_SMS_EVENT";
	public static final String DUPLICATED_SIGNER_PIN_REQUEST_SMS_EN = "DUPLICATED_SIGNER_PIN_REQUEST_SMS_EN";
	public static final String DUPLICATED_SIGNER_PIN_REQUEST_SMS_SC = "DUPLICATED_SIGNER_PIN_REQUEST_SMS_SC";
	public static final String DUPLICATED_SIGNER_PIN_REQUEST_SMS_TC = "DUPLICATED_SIGNER_PIN_REQUEST_SMS_TC";

    public static final String USER_SUCCESS_RESET_SIGNER_PIN_EMAIL_EVENT = "USER_SUCCESS_RESET_SIGNER_PIN_EMAIL_EVENT";

    public static final String USER_SUCCESS_RESET_SIGNER_PIN_SMS_EVENT = "USER_SUCCESS_RESET_SIGNER_PIN_SMS_EVENT";
	
	public static final String HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT =
		"HTH_API_PASSWORD_CODE_APPROVED_USER_EMAIL_EVENT";
	public static final String HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT =
		"HTH_API_PASSWORD_CODE_APPROVED_COMPANY_EMAIL_EVENT";
}
