define({
    root: {
        title: "HTH Onboarding Details",
        download: "Download HTH Audit Details",
        field: "Field",
        value: "Value",
        auditId: "Audit ID",
        operation: "Operation",
        actorUserId: "Action User",
        targetUserId: "Target User",
        partyId: "Company ID",
        targetUnit: "Business Unit",
        oldUserChannelType: "Previous User Channel Type",
        newUserChannelType: "New User Channel Type",
        approvalReference: "Approval Reference",
        referenceNumber: "Reference Number",
        occurredAt: "Time (UTC)",
        businessOutcome: "Result",
        errorCode: "Error Code",
        codeId: "Code Record ID",
        previousCodeId: "Previous Code Record ID",
        purpose: "Code Purpose",
        codeStatus: "Code Status",
        requestId: "Request ID",
        idempotentReplay: "Repeated Request",
        accessPartyId: "Access Company ID",
        linkageType: "Linkage Type",
        effectiveChange: "Access Changed",
        change: "Change",
        accountType: "Account Type",
        maskedAccountNumber: "Account",
        apiMasterId: "API Service ID"
    },
    "zh-Hant": true,
    "zh-CN": true
});
