define(["ojL10n!resources/nls/generic",
    "ojL10n!resources/nls/user-management-common",
    "ojL10n!resources/nls/accessible-entity",
    "ojL10n!resources/nls/user-management-headers"
], function (Generic, UMCommon, AccessibleEntity, UMHeaders) {
    "use strict";

    const UserReadLocale = function () {
        return {
            root: {
                headers: {
                    view: "View",
                    personalinfo: "Personal Information",
                    contacts: "Contact Information",
                    limitrole: "User Authorities and User Roles",
                    status: "Status",
                    usermanagement: "User Management",
                    role: "User Authorities and User Roles",
                    edit: "Edit",
                    others: "Other Details",
                    resetCredentials: "Reset Credentials",
                    deviceRegistration: "Device Registration",
                    pushNotification: "Push Notification",
                    download: "Download",
                    downloadFile: "Download profile",
                    internalAccessPoints: "Touch Points",
                    loginIdInfo: "Login PIN Information",
                    signerIdInfo: "Signer PIN Information",
                    itokenService:"i-Token Services"
                },
                buttons: {
                    back: "Back",
                    cancel: "Cancel",
                    resetpassword: "Reset Password",
                    edit: "Edit",
                    yes: "Yes",
                    no: "No",
                    delete: "Delete",
                    revoke: "Revoke"
                },
                fieldname: {
                    tokenStatus:"Status",
                    linkedDevice:"Linked Device:",
                    lastUpdateDate:"Last Update Date of Activation",
                    lastUpdatedBy: "Last Updated By",
                    lastUpdatedOn: "Last Updated On",
                    emptyString:"TT TT",
                    Inactive: "Inactive",
                    Activated: "Activated",
                    Locked: "Locked",
                    Suspended: "Suspended",
                    TemporarilyLocked: "Temporarily Locked",
                    "Temporarily Locked": "Temporarily Locked",
                    username: "Username",
                    firstname: "Full Name",
                    lastname: "Last Name",
                    email: "Email Address",
                    mobilenumber: "Mobile Number",
                    partyname: "CDC Account Name",
                    partyid: "CDC Account Number",
                    emailid: "Email Address",
                    middlename: "Middle Name",
                    userRole: "User Authorities and User Roles",
                    title: "Title",
                    address1: "Address Line 1",
                    address2: "Address Line 2",
                    address3: "Address Line 3",
                    address4: "Address Line 4",
                    city: "City",
                    state: "State",
                    country: "Country",
                    pincode: "Zip Code",
                    dob: "Date of Birth",
                    contactlandline: "Contact Number (Landline)",
                    contactmobile: "Mobile Number",
                    organization: "Organization",
                    manager: "Manager",
                    empno: "Employee Number",
                    userType: "User Type",
                    role: "User Roles",
                    userChannelType: "User Channel Type",
                    limit: "Limit",
                    lockUser: "Lock User",
                    lock: "Suspended",
                    unlock: "Normal",
                    transactionName: "Reset Password",
                    uuid: "Universally Unique ID",
                    deleteUser: "Delete User",
                    revokeUser: "Revoke User",
                    accessibleentity: "Accessible Entity",
                    entityName: "Entity Name",
                    androidDevice: "Android Devices",
                    iOsDevice: "iOS Devices",
                    retailUser: "Retail User",
                    administrator: "Administrator",
                    selectAccessPoints: "Select Touch Points",
                    selectedAccessPoints: "Selected Touch Points",
                    selectedSegment: "Selected Segment",
                    documentType: "Identification Document Type",
                    documentCountry: "Issuing Country/Region",
                    documentId: "ID No.",
                    hkId: "Hong Kong Identity Card",
                    passport: "Passport",
                    chineseTravelPermit: "Chinese Travel Permit",
                    id: "ID (except HKID)",
                    others: "Others",
                    defaultRole: "Default Selected Role",
                    defaultGroup: "Default Selected Group",
                    loginId: "Login PIN",
                    signerId: "Signer PIN",
                    pinReferenceNo: "PIN Reference Number",
                    pinStatus: "PIN Status",
                    holdStatus: "Hold Status",
                    holdReason: "PIN Hold Reason",
                    idDocumentSubmitted: "ID Document Submitted",
                    authorizedPerson: "Authorised Person",
                    companyActivityLog: "View all company activity log",
                    cdcId: "CDC Account Number",
                    companyName: "Company Name",
                    mobileWithCode: "{code} - {mobileNo}",
                    mapped: "Y",
                    notMapped: "N",
                    newPinReferenceNo: "New PIN Reference Number",
                    newPinStatus: "New PIN Status",
                    newHoldStatus: "New Hold Status",
                    newHoldReason: "New PIN Hold Reason",
                    currentPinReferenceNo: "Current PIN Reference Number",
                    currentPinStatus: "Current PIN Status",
                    currentHoldStatus: "Current Hold Status",
                    currentHoldReason: "Current PIN Hold Reason",
                    nil: "NIL",
                    mr: "Mr.",
                    mrs: "Mrs.",
                    ms: "Ms.",
                    miss: "Miss.",
                    other: "Other",
                    unhold: "Unhold",
                    inactive: "Inactive",
                    normal: "Normal",
                    beingReset: "Being Reset",
                    noActivityAllowed: "No Activity Allowed",
                    retryExceeded: "Retry Count Exceeded",
                    reqByCustomer: "Requested by Customer",
                    corpCustomer: "Corporate Customer",
                    loginPINResetCode: "Login PIN Reset Code",
                    loginPINResetCodeStatus: "Login PIN Reset Code Status",
                    loginPINResetCodeDisabled: "Disabled",
                    loginPINResetCodeEnabled: "Enable (Valid by {date} HKT)",
                    enable: "Enable",
                    loginPINResetCodeMask: "******",
                    hthApiPasswordCode: "HTH API Password Code",
                    hthApiPasswordCodeMask: "******"
                },
                info: {
                    hthUsed: "This Code has been used.",
                    hthExpiryAfterApproval: "This Code validity: T+1 23:59:59 after approval."
                },
                message: {
                    confirmationMessage: "Are you sure you want to cancel this transaction ?",
                    resetalert: "Are you sure you want to reset the password of this user?",
                    noLimitAssigned: "No Limit attached to the user",
                    deleteAlert: "Are you sure you want to delete the user?",
                    revokeAlert: "Are you sure you want to revoke the deleted user?",
                    deleteSigner: "Signer ID has been deleted."
                },
                roles: {
                    AP_TL: "Authorised Person",
                    SYSADM_TL: "System Administrator",
                    Approver_TL: "Approver",
                    Maker_TL: "Maker",
                    Viewer_TL: "Viewer",
                    Migrated_SYSADM_TL: "CCB System Administrator",
                    Maker: "Maker",
                    Checker: "Checker",
                    Viewer: "Viewer"
                },
                accessibleEntity: AccessibleEntity,
                generic: Generic,
                common: UMCommon,
                userGroupHeaders: UMHeaders
            },
            ar: true,
            es: true,
            pt: true,
            fr: true,
            cs: true,
            sv: true,
            en: false,
            "en-us": false,
            el: true,
            "zh-CN": true,
            "zh-Hant": true
        };
    };

    return new UserReadLocale();
});
