define({
    title: "HTH 开通审计详情",
    download: "下载 HTH 审计详情",
    field: "字段",
    value: "值",
    auditId: "审计编号",
    operation: "操作",
    actorUserId: "操作用户",
    targetUserId: "目标用户",
    partyId: "公司编号",
    targetUnit: "业务单位",
    oldUserChannelType: "原用户渠道类型",
    newUserChannelType: "新用户渠道类型",
    approvalReference: "审批参考编号",
    referenceNumber: "参考编号",
    occurredAt: "时间 (UTC)",
    businessOutcome: "结果",
    errorCode: "错误代码",
    codeId: "Code 记录编号",
    previousCodeId: "原 Code 记录编号",
    purpose: "Code 用途",
    codeStatus: "Code 状态",
    requestId: "请求编号",
    idempotentReplay: "重复请求",
    accessPartyId: "权限所属公司",
    linkageType: "关联类型",
    effectiveChange: "权限已变更",
    change: "变更",
    accountType: "账户类型",
    maskedAccountNumber: "账户",
    apiMasterId: "API 服务编号"
});
