-- BCOH2H-1293. Connect as HTH_BEA and execute the entire DECLARE ... END; block.
-- No BCO or DIGX_CZ object is modified. Safe to rerun after a completed install.
-- Oracle DDL commits implicitly; an interrupted install can be rerun.
DECLARE
  v_count NUMBER;
  v_stage VARCHAR2(50) := 'PREFLIGHT';
BEGIN
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES
   WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS';
  IF v_count<>1 THEN
    RAISE_APPLICATION_ERROR(-20129, '1293: HTH CRM source table missing');
  END IF;
  SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
   WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EVENT_DETAILS'
     AND COLUMN_NAME='CREATED_AT' AND DATA_TYPE LIKE 'TIMESTAMP%';
  IF v_count<>1 THEN
    RAISE_APPLICATION_ERROR(-20129, '1293: CREATED_AT is missing or incompatible');
  END IF;

  v_stage := 'RUN_TABLE';
  SELECT COUNT(*) INTO v_count FROM ALL_TABLES
   WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EXTRACT_RUN';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE HTH_BEA.HTH_CRM_EXTRACT_RUN (
      RUN_ID VARCHAR2(36 CHAR) NOT NULL,
      BUSINESS_DATE DATE NOT NULL,
      RUN_TYPE VARCHAR2(12 CHAR) NOT NULL,
      OPERATOR_ID VARCHAR2(128 CHAR),
      STARTED_AT TIMESTAMP(6) NOT NULL,
      ENDED_AT TIMESTAMP(6),
      STATUS VARCHAR2(12 CHAR) NOT NULL,
      RECORD_COUNT NUMBER(18,0) DEFAULT 0 NOT NULL,
      FILE_NAME VARCHAR2(255 CHAR),
      FILE_BYTES NUMBER(18,0),
      ERROR_STAGE VARCHAR2(64 CHAR),
      ERROR_TYPE VARCHAR2(128 CHAR),
      ERROR_CODE VARCHAR2(64 CHAR),
      ERROR_MESSAGE VARCHAR2(256 CHAR),
      CONSTRAINT PK_HTH_CRM_EXTRACT_RUN PRIMARY KEY (RUN_ID),
      CONSTRAINT CK_HTH_CRM_EXTRACT_STATUS CHECK (STATUS IN ('RUNNING','SUCCESS','FAILED')),
      CONSTRAINT CK_HTH_CRM_EXTRACT_TYPE CHECK (RUN_TYPE IN ('SCHEDULED','MANUAL')),
      CONSTRAINT CK_HTH_CRM_EXTRACT_COUNT CHECK (RECORD_COUNT >= 0)
    )~';
  ELSE
    FOR col IN (
      SELECT 'RUN_ID' name, 'VARCHAR2' typ FROM DUAL UNION ALL
      SELECT 'BUSINESS_DATE', 'DATE' FROM DUAL UNION ALL
      SELECT 'RUN_TYPE', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'OPERATOR_ID', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'STARTED_AT', 'TIMESTAMP' FROM DUAL UNION ALL
      SELECT 'ENDED_AT', 'TIMESTAMP' FROM DUAL UNION ALL
      SELECT 'STATUS', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'RECORD_COUNT', 'NUMBER' FROM DUAL UNION ALL
      SELECT 'FILE_NAME', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'FILE_BYTES', 'NUMBER' FROM DUAL UNION ALL
      SELECT 'ERROR_STAGE', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'ERROR_TYPE', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'ERROR_CODE', 'VARCHAR2' FROM DUAL UNION ALL
      SELECT 'ERROR_MESSAGE', 'VARCHAR2' FROM DUAL
    ) LOOP
      SELECT COUNT(*) INTO v_count FROM ALL_TAB_COLUMNS
       WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EXTRACT_RUN'
         AND COLUMN_NAME=col.name
         AND (DATA_TYPE=col.typ OR (col.typ='TIMESTAMP' AND DATA_TYPE LIKE 'TIMESTAMP%'));
      IF v_count<>1 THEN
        RAISE_APPLICATION_ERROR(-20129, '1293: incompatible run column ' || col.name);
      END IF;
    END LOOP;
  END IF;

  v_stage := 'ACTIVE_RUN_INDEX';
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
   WHERE OWNER='HTH_BEA' AND INDEX_NAME='UX_HTH_CRM_EXTRACT_ACTIVE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX HTH_BEA.UX_HTH_CRM_EXTRACT_ACTIVE
      ON HTH_BEA.HTH_CRM_EXTRACT_RUN
      (CASE WHEN STATUS='RUNNING' THEN BUSINESS_DATE END)~';
  ELSE
    SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
     WHERE OWNER='HTH_BEA' AND INDEX_NAME='UX_HTH_CRM_EXTRACT_ACTIVE'
       AND TABLE_OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EXTRACT_RUN'
       AND UNIQUENESS='UNIQUE';
    IF v_count<>1 THEN
      RAISE_APPLICATION_ERROR(-20129, '1293: active-run index is incompatible');
    END IF;
  END IF;

  v_stage := 'RUN_DATE_INDEX';
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
   WHERE OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_CRM_EXTRACT_DATE';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX HTH_BEA.IX_HTH_CRM_EXTRACT_DATE ON HTH_BEA.HTH_CRM_EXTRACT_RUN (BUSINESS_DATE,STARTED_AT)';
  END IF;

  v_stage := 'SOURCE_DATE_INDEX';
  SELECT COUNT(*) INTO v_count FROM ALL_INDEXES
   WHERE OWNER='HTH_BEA' AND INDEX_NAME='IX_HTH_CRM_CREATED_AT';
  IF v_count=0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX HTH_BEA.IX_HTH_CRM_CREATED_AT ON HTH_BEA.HTH_CRM_EVENT_DETAILS (CREATED_AT,EVENT_ID)';
  END IF;

  v_stage := 'COMMENTS';
  EXECUTE IMMEDIATE q'~COMMENT ON TABLE HTH_BEA.HTH_CRM_EXTRACT_RUN IS 'BCOH2H-1293 HTH-only daily CRM CSV extraction attempts; no source processing markers.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.RUN_ID IS 'Unique identifier of this extraction attempt.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.BUSINESS_DATE IS 'Hong Kong calendar date selected by the CREATED_AT half-open interval.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.RUN_TYPE IS 'SCHEDULED daily execution or MANUAL dated rerun.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.OPERATOR_ID IS 'Operating-system user running the batch process.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.STARTED_AT IS 'Run start in Asia/Hong_Kong local time.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.ENDED_AT IS 'Run completion in Asia/Hong_Kong local time.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.STATUS IS 'RUNNING, SUCCESS or FAILED.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.RECORD_COUNT IS 'Number of data rows written in this attempt; excludes the CSV header.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.FILE_NAME IS 'Published CSV file name; null if the no-file empty policy applies.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.FILE_BYTES IS 'Published file size in bytes.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.ERROR_STAGE IS 'Failure stage; no input or output data.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.ERROR_TYPE IS 'Exception class only; no exception message or sensitive data.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.ERROR_CODE IS 'Database vendor error number when available; no raw error message.'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN HTH_BEA.HTH_CRM_EXTRACT_RUN.ERROR_MESSAGE IS 'Sanitized failure summary built from stage, exception class and safe error code.'~';
EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20129, '1293 schema stage=' || v_stage || ': ' || SQLERRM);
END;
