-- Read-only checks. Run with HTH_BEA after 1_HTH_CRM_1293_Schema.sql.
SELECT TABLE_NAME FROM ALL_TABLES
WHERE OWNER='HTH_BEA' AND TABLE_NAME IN ('HTH_CRM_EVENT_DETAILS','HTH_CRM_EXTRACT_RUN')
ORDER BY TABLE_NAME;

SELECT COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EXTRACT_RUN'
ORDER BY COLUMN_ID;

SELECT INDEX_NAME,TABLE_NAME,UNIQUENESS
FROM ALL_INDEXES
WHERE OWNER='HTH_BEA' AND INDEX_NAME IN
 ('UX_HTH_CRM_EXTRACT_ACTIVE','IX_HTH_CRM_EXTRACT_DATE','IX_HTH_CRM_CREATED_AT')
ORDER BY INDEX_NAME;

SELECT COLUMN_NAME,COMMENTS FROM ALL_COL_COMMENTS
WHERE OWNER='HTH_BEA' AND TABLE_NAME='HTH_CRM_EXTRACT_RUN'
ORDER BY COLUMN_NAME;

SELECT BUSINESS_DATE,RUN_TYPE,STATUS,RECORD_COUNT,FILE_NAME,STARTED_AT,ENDED_AT,
       ERROR_STAGE,ERROR_TYPE,ERROR_CODE,ERROR_MESSAGE
FROM HTH_BEA.HTH_CRM_EXTRACT_RUN
ORDER BY STARTED_AT DESC FETCH FIRST 50 ROWS ONLY;
