WW=Transaction Working Window
WW_N_CWW=Create Working Window
WW_N_UWW=Update Working Window
WW_N_DWW=Delete Working Window
PC_M_CGP=Create Global Payee
SP_N_SCT=Split categorized Transaction
BG_N_CBG=Create Budget
BG_N_LBG=List Budget
BG_N_UBG=Update Budget
BG_N_DBG=Delete Budget
PC_F_EXT=External Transfer Confirm
PC_F_CEXT=External Transfer Initiate
FU_WW_ILFT=International Transfer - File Upload
FU_WW_IFT=Internal Transfer - Upload Working Window
FU_WW_DFTN=Domestic Transfer - NEFT
FU_WW_DFTR=Domestic Transfer - RTGS
PC_N_CPTPP=Create Peer To Peer Payee
FU_UP=文件上传
PC_F_CPTP=PeerToPeer Transfer Initiate
PC_F_PTP=PeerToPeer Transfer Confirm
PC_F_PRTOPR=PeerToPeer Transfer
FU_I=File Upload
FU_VW=Inquiries
PC_F_BLPMT=Bill Payment
PC_F_ID=International Draft
CH_I_ESTF=E-Statement Subscription Read
CH_I_LDC=List Debit cards
CH_I_RDC=Read Debit card
CH_I_DCL=Read Debit card Limit
CH_N_ACDC=Activate Debit card
CH_N_RLDC=Replace Debit card
LN_I_OI=Read Oustanding information
LN_I_RD=Read Repayment details
LN_I_FTU=Read Top ups
LN_N_TU=Top up
TD_I_PII=Read Pay In details
TD_I_POI=Read Pay out details
TD_I_TUI=Read top up details
TD_F_TTDP=TD top up Simulation
TD_I_TDPI=Fetch TD penalties
PC_F_ET=External Transfer
PC_F_CGNDP=Adhoc Domestic Payment
PC_F_CGNIP=Adhoc Internal Transfer
PC_F_CGNITNP=Adhoc International Payment
LAT_N_DA=用户账户及服务管理 - 删除 (关联账户配对)
LAT_N_CA=用户账户及服务管理 - 创建 (关联账户配对)
LAT_N_UA=用户账户及服务管理 - 编辑 (关联账户配对)
LAT=User Linkage Account Transactions
TD_F_TP=TD Top UP
AL_N_CS=设立设定提示
AL_N_US=设立/更新提示设定
AL_N_DS=删除设定提示
ALS_MT=设定提示
AF=All Non Account Financial Transactions
TF_N=Trade Finance
TF_AF=Trade Finance Non Account Financial
TF_N_LC=Letter Of Credit
TF_N_ULC=Attach document to Letter of Credit
TF_N_CLC=Initiate Letter of Credit
TF_N_SLC=Letter Of Credit Draft and Template
TF_N_LTR=List Trade Application
TF_N_RTR=Read Trade Application
TF_N_LTRC=List Trade Clarification
TF_N_UTRC=Update Trade Clarification
TF_AF_SG=Shipping Guarantee
TF_AF_LSG=List Shipping Guarantee
TF_N_BL=Bills Discrepancies
TF_AF_DBL=Customer Acceptance for Discrepancies in Import Bills
TF_AF_CLC=Initiate Letter of Credit
TF_AF_LC=Letter Of Credit
TF_AF_TSBL=Trade Bill Settlement
TF_F=Trade Finance Account Financial
TF_AF_CEL=Customer Acceptance for Export LC Amendment
TF_N_LC=Letter Of Credit
TF_AF_AIL=Initiate Import LC Amendment
TF_AF_CCL=Initiate Collection
TF_AF_CL=收款
LO=ATM/Branch Create
LO_ATM_CR=ATM Create
LO_ATM_DE=ATM Delete
LO_ATM_UP=ATM Update
LO_BRN_CR=Branch Create
LO_BRN_DE=Branch Delete
LO_BRN_UP=Branch Update
MB_N=Mobile
MB_N_MCR=Mobile Device Registration
FL_MT=Financial Limits
FL_N_CLT=Create Limit
FL_N_CLP=Create Limit Package
FL_N_ULP=Update Limit Package
FL_N_DLT=Delete Limit
FL_N_DLP=Delete Limit Package
PC_F_CDPR=Domestic Payer
PC_F_DPR=Domestic Payer
PC_F_CDPI=Domestic Payin Pay Later
PC_F_DPI=Domestic Payin Pay Later
USPM=UserSegment Map
USPM_N_UM=Update Product Mapping
UM_N_TSR=Create Token Seed
USPM_N_CM=Create Product Mapping
AU=Authentication Maintenance
AU_N_CAM=Authentication - Create
AU_N_UAM=Authentication - Edit
AM_VIEW=Authentication - View
PC_CM_ME=登录
CC_N=Credit Cards
CC_N_RP=Reset Credit Card Pin
CH_N_RP=Reset Debit Card Pin
CH_N_LES=List Demand Deposit Electronic Statement
LN_N_LES=List Loan Electronic Statement
LO_UP=Location Upload
AU_USQ_U=设置安全问题
ML_N_DM=Delete Mailers
PC_F_UK_FAS=Domestic UK Payment - Faster
TD_N_LES=List Deposit Electronic Statement
ML_N_CM=Create Mailers
CH_N_DES=Demand Deposit Electronic Statement Download
LN_N_DES=Loan Electronic Statement download
PC_F_UK_NOU=Domestic UK Payment - NON URGENT
TD_N_DES=Deposit Electronic Statement download
ML_N_UM=Update Mailers
ML=Mailers
PC_F_UK_URG=Domestic UK Payment - URGENT
PC_F_INTRNL=Internal Transfer
PC_F_IT=International Transfer
PC_F_ITF=Internal Transfer Pay Now
PC_F_ITFI=Internal Transfer Pay Later/SI
PC_F_ITR=海外转账
PC_F_ITRI=International Payment Pay Later/SI
PC_F_SELF=Self Transfer
PC_F_SFT=Own Account Transfer
PC_F_SFTI=Own Account Transfer Pay Later/SI
PC_F_DOMDRAFT=Domestic Draft
PC_F_SEPA_CARD=Domestic SEPA Payment - CARD
PC_F_SEPA_CREDIT=Domestic SEPA Payment - CREDIT
CM=All Common Transactions
MT=All Admin Maintenances
IT=All Inquiry Transactions
NT=All Non Financial Transactions
FT=All Financial Transactions
TD_F_OTD=开立新定期存款
TD_N_ATD=修改定期存款到期指示
TD_F_RTD=定期存款提取
LN_F_LRP=Loan and Finance Repayment
CH_N_CBR=申请支票簿
CH_N_CIN=停止支付支票
CH_I_CSE=支票簿查询
PC_F=Payments
PC_N=Payments
TD_F=Term Deposits - Financial
TD_N=Term Deposits
LN_F=Loans
LN_N=Loans
CH_F=CASA
CH_N=CASA
TD_F_TTD=Deposit Top-Up
PC_F_BPT=Bill Payment
PC_N_PBR=Add Biller
PC_F_PIC=Instruction Cancellation
PC_N_DOP=Create Domestic Payee
PC_N_UPBR=Edit Biller
PC_N_DPBR=Delete Biller
CH_N_RAS=Request Demand Deposit Statement
CH_N_EST=E-Statement Subscription
CH_N_BDC=Block Debit Card
CH_N_RDCP=Request Debit Card Pin
CH_N_ADC=Apply Debit Card
TD_N_RAS=Request Deposit Statement
AP_N_UUG=Update User Group
AP_N_AUG=Add User to Group
AP_N_DUG=Delete User from Group
AP_N_UWF=Update Workflow
AP_N_DWF=Delete Workflow
AT_N_CCA=账户及服务管理 - 创建
AT_N_DCA=账户及服务管理 - 删除
AT_N_UCA=账户及服务管理 - 编辑
AT=Account Transactions
PP=Party Preference
PP_N_CRE=账户资料 - 创建
PP_N_UPD=账户资料 - 编辑
PP_N_DEL=账户资料 - 删除
PP_N_VIEW=账户资料 - 查看
RM_MT=交易批核规则管理
AP_N_CR=交易批核规则管理-创建规则
AP_N_UR=交易批核规则管理-编辑规则
AP_N_DR=交易批核规则管理-删除规则
UM=User Management
AP=Approvals
RP=System Rules
UM_N_UCR=Create User
UM_N_UMD=Modify User
UM_N_UDL=Delete User
AP_N_CUG=User Group
AP_N_CWF=Create Workflow
AP_N_CRU=Create Rule
RP_N_RPM=System Rules
UM_N_UGM=Assign Group to User
UM_N_UGC=Change User Status
UAT=用户账户及服务管理
UAT_N_CA=用户账户及服务管理-配对(创建)
UAT_N_DA=删除用户账户及服务的访问权限
UAT_N_UA=用户账户及服务管理-修改
UAT_N_HUA_NEW=HTH 用户账户及服务访问-创建
UAT_N_HUA_EDT=HTH 用户账户及服务访问-修改
UAT_N_HUA_DEL=HTH 用户账户及服务访问-删除
PC_F_IDD=International Demand Draft
TD_I_RI=Redemption Inquiry
FU_R_IFT=Internal Transfer - Record Level Approval
FU_R_ILFT=International Payment - Record Level Approval
FU_R_DFT=Domestic Transfer - Record Level Approval
FU_R_MFT=Mixed Payment - Record Level Approval
FU_MT=File Upload
FU_FT=File Upload
FU_F_ILFT=International Payment - File Level Approval
FU_F_DFT=Domestic Payment - File Level Approval
FU_F_MFT=Mixed Payment - File Level Approval
FU_F_AILFT=International Payment - Upload
FU_F_ADFT=Domestic Payment - Upload
FU_F_AMIX=Mixed Payment - Upload
FU_F_IFT=Internal Transfer - File Level Approval
FU_F_AIFT=Internal Transfer - Upload
FU_N_CFR=Create File Identifier Registration
FU_N_UFR=Update File Identifier Registration
FU_N_CUM=Create User File Identifier Mapping
FU_N_UUM=用户文件检验配对 -编辑
FU_N_DUM=Delete User File Identifier Mapping
FU_N_DFR=Delete File Identifier Registration
PC_F_CBPT=Bill Payment
PC_N_CDDP=Create Demand Draft Payee
PC_F_CITF=Internal Transfer Pay Now
PC_F_CDFTI=Domestic Payment Pay Later
PC_F_CIDD=International Demand Draft Pay Now
PC_F_CITFI=Internal Transfer Pay Later/SI
PC_F_CITR=International Payment Pay Now
PC_F_CSFT=Own Account Transfer Pay Now
PC_F_CDDDI=Domestic Demand Draft Pay Later
PC_F_DDDI=Domestic Demand Draft Pay Later
PC_F_CITRI=International Payment Pay Later/SI
PC_F_CSFTI=Own Account Transfer Pay Later/SI
PC_F_CDDD=Domestic Demand Draft Pay Now
PC_F_CIDDI=International Demand Draft Pay Later
PC_F_DFTI=Domestic Payment Pay Later/SI
PC_F_IDDI=International Demand Draft Pay Later
PC_F_DFT=Domestic Payment
PC_F_GNIP=Adhoc Internal Transfer
PC_F_GNITNP=Adhoc International Payment
PC_F_GNDP=Adhoc Domestic Payment
CH_I=CASA Inquiries
LN_I=Loan Inquiries
TD_I=TD Inquiries
PC_I=Payments Inquiries
CH_I_AS=账户概览
CH_I_AA=查看账户记录
CH_I_AD=账户详情
TD_I_AS=定期存款交易记录
TD_I_AA=定期存款查询
TD_I_AD=定期存款详情
LN_I_SI=Schedule Inquiry
LN_I_DD=Disbursement Details
LN_I_LS=Loan Summary
LN_I_LD=Loan Details
LN_I_LA=Loan Account Activity
PC_I_INRL=汇入汇款概览
PC_I_OUTRL=付款追踪服务
PC_I_INSTRL=预设付款指示查询
TD_I_CM=TD Calculate Maturity
MN=全部维护
PC_M=Payee
PC_F_CDFT=Domestic Payment Pay Now
PAT=Linkage Account Transactions
PAT_N_CA=Create Linkage Account Transaction Mapping
PAT_N_DA=Delete Linkage Account Transaction Mapping
PAT_N_UA=Update Linkage Account Transaction Mapping
LIN=Party To Party Linkage
GL_N_CGC=Create Goal Category
GL_N_RGC=Read Goal Category
GL_N_UGC=Update Goal Category
GL_N_DGC=Delete Goal Category
GL_N_LGC=List Goal Category
GL_N_CGCL=Goal Calculator
GL_N_CGCS=Save Goal Calculation
GL_N_RGCS=Read Goal Calculation
GL_N_RGP=Read Goal Product
GL_N_LGP=List Goal Product
AL=Alert Maintenance
AL_N_CR=Create Alert
AL_N_UPD=Update Alert
AL_N_DEL=Delete Alert
UP_LIN=Update Party To Party Linkage
CP_LIN=Create Party To Party Linkage
SP_N_CSC=Create Spend Category
SP_N_DSC=Delete Spend Category
SP_N_FCT=Fetch categorized Transactions
SP_N_LSC=List Spend Category
SP_N_RSC=Read Spend Category
SP_N_USC=Update Spend Category
PFM_F=PFM
GL_N_CGLA=Create Goal Account
GL_N_RGLA=Read Goal Account
GL_N_UGLA=Update Goal Account
GL_N_LGLA=List Goal Account
GL_N_CSIGLA=Create Standing Instruction Goal Account
SM=Transaction Blackout
SM_N_CTB=Create Transaction Blackout
SM_N_DTB=Delete Transaction Blackout
SM_N_UTB=Update Transaction Blackout
PAM=Payment Admin Maintenance
PC_N_PCL=Payee Restriction Set-up
PC_F_DOM_NEFT=Domestic Payment - NEFT
PC_F_DOM_RTGS=Domestic Payment - RTGS
PC_F_NPDOM=Domestic Payment
PC_F_SEPACREDIT=Domestic Payment - SEPA Credit
PC_F_DOM_IMPS=Domestic Payment - IMPS
SP_N_PUCT=Persist uncategorized spend transactions
UM_N_RCR=Reset Credentials
APT=Transaction Approval
PA_APT=执行行动
GL_N_CNSIGLA=Cancel Standing Instruction Goal Account
GL_N_PGLA=Payin Goal Account
GL_N_REGLA=Redeem Goal Account
GL_N_FTGLA=Fetch Transactions Goal Account
FU_MN=File Upload
FU_R_ILP=International Payee - Record Level Approval
FU_F_ILP=International Payee - File Level Approval
FU_R_DDP=Demand Draft Payee - Record Level Approval
FU_F_DDP=Demand Draft Payee - File Level Approval
FU_F_IP=Internal Payee - File Level Approval
FU_F_DP=Domestic Payee - File Level Approval
FU_R_DP=Domestic Payee - Record Level Approval
FU_R_IP=Internal Payee - Record Level Approval
FU_F_MPY=Mixed Payee - File Level Approval
UGSM=User Group Subject Mapping
UGSM_N_CM=Create User Group Subject Mapping
UGSM_N_DM=Delete User Group Subject Mapping
UGSM_N_UM=Update User Group Subject Mapping
PC_F_DDD=Domestic Demand Draft
PC_F_DOM=Domestic Payment
PC_F_INTRNL_ADHOC=Adhoc Internal Transfer - Limits
SG_M_LSE=List User Segment
SG_M_USE=Update User Segment
SG_M_CSE=Create User Segment
SG_M_RSE=Read User
FU_F_OP=Other Party Maintenance - File Level Approval
FU_R_OP=Other Party Maintenance - Record Level Approval
TF_N_TACM=Trade Additional Condition
TFAC_CR=Create Additional Condition Maintenance
TFAC_UP=Update Additional Condition Maintenance
FU_F_LC=Letter Of Credit - File Level Approval
FU_R_LC=Letter Of Credit - Record Level Approval
TF_N_TCM=Trade Clause Maintenance
TFCM_CR=Create Trade Clause Maintenance
TFCM_UP=Update Trade Clause Maintenance
FL_C_MIHO=每日交易限額維護 - 提高限額
FL_C_MDHO=每日交易限额维护 - 降低限额,

PC_F_CRNSFT=转账 - 我的账户转账
PC_F_CRNIFT=转账至已登记账户 - 东亚银行（香港）
PC_F_CRNBCT=转账至已登记账户 - 东亚银行（中国）
PC_F_CRNDFT=转账至已登记账户 - 本地转账
PC_F_CRNDFT_FPS=转账至已登记账户 - 本地转账 [快速支付系统]
PC_F_CRNINFT=转账至已登记账户 - 海外转账
PC_F_GCRNIFT=转账至未登记账户 - 东亚银行（香港）转账
PC_F_GCRNBCT=转账至未登记账户 - 东亚银行（中国）
PC_F_GCRNDFT=转账至未登记账户 - 本地转账
PC_F_GCRNDFT_FPS=转账至未登记账户 - 本地转账 [快速支付系统]
PC_F_GCRNINFT=转账至未登记账户 - 海外转账

PC_F_CRNSFT_SI=预设付款 - 转账 - 我的账户转账
PC_F_CRNIFT_SI=预设付款 - 转账至已登记账户 - 东亚银行（香港）
PC_F_CRNBCT_SI=预设付款 - 转账至已登记账户 - 东亚银行（中国）
PC_F_CRNDFT_SI=预设付款 - 转账至已登记账户 - 本地转账 [快速支付系统]
PC_F_CRNDFT_FPS_SI=预设付款 - 转账至已登记账户 - 本地转账
PC_F_CRNINFT_SI=预设付款 - 转账至已登记账户 - 海外转账
PC_F_GCRNIFT_SI=预设付款 - 转账至未登记账户 - 东亚银行（香港）转账
PC_F_GCRNBCT_SI=预设付款 - 转账至未登记账户 - 东亚银行（中国）
PC_F_GCRNDFT_SI=预设付款 - 转账至未登记账户 - 本地转账
PC_F_GCRNDFT_FPS_SI=预设付款 - 转账至未登记账户 - 本地转账 [快速支付系统]
PC_F_GCRNINFT_SI=预设付款 - 转账至未登记账户 - 海外转账

PC_F_NPSELF=我的账户
PC_F_NPINTRNL=内部转账
PC_F_NPINTRNL_ADHOC=转账至未登记账户 - 东亚银行（中国）
PC_F_NPIT=海外转账
PC_F_NPIT_ADHOC=转账至未登记账户 - 海外转账

PC_N_CIP=添加收款人 - 东亚银行（香港）
PC_N_UIP=修改收款人 - 东亚银行（香港）
PC_N_DIP=删除收款人 - 东亚银行（香港）
PC_N_DOP_VT=添加收款人 - 本地转账
PC_N_UDOP_VT=修改收款人 - 本地转账
PC_N_DDP_VT=删除收款人 - 本地转账
PC_N_CITNP=添加收款人 - 海外转账
PC_N_UITNP=修改收款人 - 海外转账
PC_N_DITNP=删除收款人 - 海外转账
PC_N_CBP=添加收款人 - 东亚银行（中国）
PC_N_UBP=修改收款人 - 东亚银行（中国）
PC_N_DBP=删除收款人 - 东亚银行（中国）
PC_N_CIP_A=添加收款人 - 东亚银行（香港）
PC_N_UIP_A=修改收款人 - 东亚银行（香港）
PC_N_DIP_A=删除收款人 - 东亚银行（香港）
PC_N_DOP_VT_A=添加收款人 - 本地转账
PC_N_UDOP_VT_A=修改收款人 - 本地转账
PC_N_DDP_VT_A=删除收款人 - 本地转账
PC_N_CITNP_A=添加收款人 - 海外转账
PC_N_UITNP_A=修改收款人 - 海外转账
PC_N_DITNP_A=删除收款人 - 海外转账
PC_N_CBP_A=添加收款人 - 东亚银行（中国）
PC_N_UBP_A=修改收款人 - 东亚银行（中国）
PC_N_DBP_A=删除收款人 - 东亚银行（中国）


MT_M_COP=开放 API 服务 - 设定 - 创建
MT_M_UOP=开放 API 服务 - 设定
MT_N_AFP=启用转数快账户绑定服务
MT_N_EFP =编辑转数快账户绑定服务
MT_N_TFP =终止转数快账户绑定服务
MT_N_VFP =转数快账户绑定服务 - 查看
MT_N_RFP =重启转数快账户绑定服务

PC_F_PIC_SFT=取消预设付款指示 - 我的账户 - 删除
PC_F_PIC_IFT=取消预设付款指示 - 东亚银行（香港） - 删除
PC_F_PIC_BCT=取消预设付款指示 - 东亚银行（中国）- 删除
PC_F_PIC_DFT=取消预设付款指示 - 本地转账 - 删除
PC_F_PIC_INFT=取消预设付款指示 - 海外转账 - 删除

EB_F_BP_SI=预设账单缴费
EB_F_BP=账单缴费
EB_F_BP_D=取消预设账单缴费
OAC_REVOKE=撤回同意第三方服务供应商
MT_N_UUS=用户管理-编辑
MT_N_CUS=用户管理-创建
MT_N_RUS=用户管理-查看
CH_N_RADHSTMT=申请临时结单
CH_N_DADHSTMT=删除临时结单申请
CH_N_LADHSTMT=临时结单概览
UM_ID_MU=ID Maintenance - Login ID/Phone Banking ID- Edit
UM_ID_MR=ID Maintenance - Inquiry (Login/Phone Banking Pin) Search/View
UM_ID_MD=ID Maintenance - Login ID/Phone Banking ID- Delete
UM_ID_MC=ID Maintenance - Create (Login/Phone Banking Pin)
EADESTMTU=Account Preference Settings - Edit
EADESTMTUR=用戶註冊概覽
CASA=往来及储蓄
EB_F=账单缴费
TD_FT=定期存款
TD_NT=定期存款
CH_NF=支票
TPS_MT=第三服务供应商同意管理
OAC_GRANT=給予同意第三方服務供應商
OAC_REFRESH=续期同意第三方服务供应商
EA_MN=电子结单/电子交易通知
EA_NT=电子结单/电子交易通知
CH_N_ESTM=查看电子结单
CH_N_EADV=查看电子交易通知
LM_N_EADV=查看电子交易通知
FPS_MN=转数快账户绑定服务
FPS=转数快账户绑定服务
FL_C_MIHO=提高每日交易限额
FL_C_MDHO=降低每日交易限额
FL_C_RHO=每日交易限额 - 查阅
FL_C_UHO=每日交易限额 - 编辑
FL_C_MT=每日交易限额维护
SP_CUST_R=特殊限额权限维护 - 查看
UM_MT=用戶管理
UM_N_ULS=更改用户状态
UM_N_USD=更改网上银行使用权限
OPN_MT=开放API服务-设置
UM_N_ULS_UL=更改用户状态
UM_N_ULS_L=更改用户状态
EADESTMTC=账户偏好设定 - 更新
EADESTMTU=账户偏好设定
EADESTMTL=账户偏好设定
FXRATECALC=外汇计算器转换请求
FXRATEALC=设立到价提示
FXRATEALU=Edit Rate Alert
FXRATEALD=删除到价提示
FXRATEALL=List Rate Alert
FXRATEWLC=设立外币汇价列表
FXRATEWLU=Edit FX Watchlist
FXRATEWLD=删除外币汇价列表
FXRATEWLL=List FX Watchlist
FXRATECRL=外汇主页
TRF_FT=转账-查询
TRFTOA_FT=转账-我的账户
TRFTOTA_FT=转账-其他账户
FTOA_TD=定期存款
PC_F_SED=设立新电子直接付款授权
PC_F_AED=编辑电子直接付款授权
PC_F_AED_CONFIRM=确认电子直接付款授权
PC_F_AED_REJECT=拒绝电子直接付款授权
PC_F_AED_SUSPEND=暂停电子直接付款授权
PC_F_AED_RESUME=恢复电子直接付款授权
PC_F_AED_TERMINATE=终止电子直接付款授权
PC_F_LED=电子直接付款授权摘要
EDDA=电子直接付款授权
M_DB_AUDIT=主页
CASA_DB_AUDIT=往来及储蓄概览主页
TD_DB_AUDIT=定期存款主页
AU_CZ_LOGOUT=登出
CM_N_FP=忘记密码
CM_N_FPN=忘记密码
CM_N_CUSQTN=设置安全问题
CH_N_ESTMEADV_DW=下载结单
CM_CH_SC=更改签核者密码
CM_N_CC=更改登录密码
CM_N_FCC=强制更改密码
BU_AUTOPAY_CREATE=自动转账
BU_PAYROLL_CREATE=支薪
BU_COLLECTION_CREATE=收款
FU_F_APC=文件上传
APC=自动转账、支薪及收款
FU_VW=文件上传查询
BU_SI_LIST=自动转账 支付薪资及托收查询
BU_SI_DELETE_AP=自动转账输入 - 预设指示删除
BU_SI_DELETE_PR=支薪输入 - 预设指示删除
BU_SI_DELETE_FU=文件上传 - 预设指示删除
BU_SI_DELETE_CL=收款输入 - 预设指示删除
FU_UP_AP=上传文件自动转账
FU_UP_PR=上传文件支薪
FU_UP_CL=上传文件收款
CZ_PA_APT=多重交易审批
CTD_C=Preferential Time Deposit Enquiry and Maintenance
IN_F_CIMPF=供款查询
IN_F_CMPF=公司详情
IN_F_SMPF=成员详情
IN_F_CDMPF=供款详情
IN_F_VPMPF=自愿性供款的归属规则
IN_F_DIMPF=拖欠供款查询
IN_F_DCMPF=拖欠供款查询详情
IN_F_MPFINFO=强积金资料
MPF=强积金
IN_F_SATMPF=供款详情
LMI_F_CLM=设立指示
LMI_I_VLLM=指示列表
LMI_I_VHLLM=交易记录及报告
MRCH_I_AACT=账户交易下载
MRCH=商户服务
LMI_I_VLM=验证 LM 指令
LMI=流动资金管理指示
LMI_F_ULM=更新 LM 指令
LMI_F_DLM=删除 LM 指令
LMI_I_VLMD=查看 LM 指令详细信息
LMI_F_ACLM=设立指示 - 东亚银行 (香港) - 建立
LMI_F_CCLM=设立指示 - 东亚银行 (中国) - 建立
LMI_F_LCLM=设立指示 - 本地 - 建立
LMI_F_TCLM=设立指示 - 海外 - 建立
LMI_F_OCLM=设立指示 - 我的账户 - 建立
LMI_F_AULM=设立指示 - 东亚银行 (香港) - 编辑
LMI_F_CULM=设立指示 - 东亚银行 (中国) - 编辑
LMI_F_LULM=设立指示 - 本地 - 编辑
LMI_F_TULM=设立指示 - 海外 - 编辑
LMI_F_OULM=设立指示 - 我的账户 - 编辑
LMI_F_ADLM=设立指示 - 东亚银行 (香港) - 删除
LMI_F_CDLM=设立指示 - 东亚银行 (中国) - 删除
LMI_F_LDLM=设立指示 - 本地 - 删除
LMI_F_TDLM=设立指示 - 海外 - 删除
LMI_F_ODLM=设立指示 - 我的账户 - 删除
FRXAGREE=外汇交易
FT_F_PFR=外汇交易
MRCH_I_AA=是日交易记录
MRCH_I_MTE=商户交易查询
MRCH_I_DMA=商户存入销售单通知下载
MRCH_N_LDMU=Merchant User Maintenance - Edit Pin Mapping
MRCH_N_LDMC=Merchant User Maintenance - Edit Pin Mapping
MRCH_I_AACH=账户记录
MRCH_N_LMUP=Merchant User Maintenance - View PIN Mapping
IVM=投资
IVM_N_ST=股票买卖
IVM_R_A=风险评估
INV_A=投资账户
INV_A_AD=投资概览
INV_A_TH=投资交易记录
BP_FT=转账-批量付款
BPFU_BP_FT=批量付款文件上传
BPI_BP_FT=批量付款查询
UFO_BP_FT=上传文件概览
FPSMRCH=「转数快」商戶收款服务
FPSMRCH_N_QR=创建转数快二维码
FPSMRCH_N_QRACREPO=二维码活动纪录
FPSMRCH_N_PTH=转数快商戶收款交易记录
FPSMRCH_N_CFP=创建转码快二维码
FPSMRCH_N_LPA=二维码活动纪录
PC_F_CRNSFT=我的账户转账
TL_N=贸易和贷款
TF_N_TAD=贸易和贷款主目录
BT_FT=转账-批量转账
PC_F_BTFT=批量转账文件上传
PC_F_BTIQ=批量转账查询
PC_F_BTOV=上传文件概览
PC_I_OUTRIU=付款追踪服务
PC_I_OUTRL=付款追踪服务
PC_I_INRIU=付款追踪服务
