WW=Transaction Working Window
WW_N_CWW=Create Working Window
WW_N_UWW=Update Working Window
WW_N_DWW=Delete Working Window
PC_M_CGP=Create Global Payee
SP_N_SCT=Split categorized Transaction
BG_N_CBG=Create Budget
BG_N_LBG=List Budget
BG_N_UBG=Update Budget
BG_N_DBG=Delete Budget
PC_F_EXT=External Transfer Confirm
PC_F_CEXT=External Transfer Initiate
FU_WW_ILFT=International Transfer - File Upload
FU_WW_IFT=Internal Transfer - Upload Working Window
FU_WW_DFTN=Domestic Transfer - NEFT
FU_WW_DFTR=Domestic Transfer - RTGS
PC_N_CPTPP=Create Peer To Peer Payee
FU_UP=文件上傳
PC_F_CPTP=PeerToPeer Transfer Initiate
PC_F_PTP=PeerToPeer Transfer Confirm
PC_F_PRTOPR=PeerToPeer Transfer
FU_I=File Upload
FU_VW=Inquiries
PC_F_BLPMT=Bill Payment
PC_F_ID=International Draft
CH_I_ESTF=E-Statement Subscription Read
CH_I_LDC=List Debit cards
CH_I_RDC=Read Debit card
CH_I_DCL=Read Debit card Limit
CH_N_ACDC=Activate Debit card
CH_N_RLDC=Replace Debit card
LN_I_OI=Read Oustanding information
LN_I_RD=Read Repayment details
LN_I_FTU=Read Top ups
LN_N_TU=Top up
TD_I_PII=Read Pay In details
TD_I_POI=Read Pay out details
TD_I_TUI=Read top up details
TD_F_TTDP=TD top up Simulation
TD_I_TDPI=Fetch TD penalties
PC_F_ET=External Transfer
PC_F_CGNDP=Adhoc Domestic Payment
PC_F_CGNIP=Adhoc Internal Transfer
PC_F_CGNITNP=Adhoc International Payment
LAT_N_DA=用戶賬戶及服務管理 - 刪除 (關聯賬戶配對)
LAT_N_CA=用戶賬戶及服務管理 - 建立 (關聯賬戶配對)
LAT_N_UA=用戶賬戶及服務管理 - 編輯 (關聯賬戶配對)
LAT=User Linkage Account Transactions
TD_F_TP=TD Top UP
AL_N_CS=設立設定提示
AL_N_US=設立/更新提示設定
AL_N_DS=刪除設定提示
ALS_MT=設定提示
AF=All Non Account Financial Transactions
TF_N=Trade Finance
TF_AF=Trade Finance Non Account Financial
TF_N_LC=Letter Of Credit
TF_N_ULC=Attach document to Letter of Credit
TF_N_CLC=Initiate Letter of Credit
TF_N_SLC=Letter Of Credit Draft and Template
TF_N_LTR=List Trade Application
TF_N_RTR=Read Trade Application
TF_N_LTRC=List Trade Clarification
TF_N_UTRC=Update Trade Clarification
TF_AF_SG=Shipping Guarantee
TF_AF_LSG=List Shipping Guarantee
TF_N_BL=Bills Discrepancies
TF_AF_DBL=Customer Acceptance for Discrepancies in Import Bills
TF_AF_CLC=Initiate Letter of Credit
TF_AF_LC=Letter Of Credit
TF_AF_TSBL=Trade Bill Settlement
TF_F=Trade Finance Account Financial
TF_AF_CEL=Customer Acceptance for Export LC Amendment
TF_N_LC=Letter Of Credit
TF_AF_AIL=Initiate Import LC Amendment
TF_AF_CCL=Initiate Collection
TF_AF_CL=收款
LO=ATM/Branch Create
LO_ATM_CR=ATM Create
LO_ATM_DE=ATM Delete
LO_ATM_UP=ATM Update
LO_BRN_CR=Branch Create
LO_BRN_DE=Branch Delete
LO_BRN_UP=Branch Update
MB_N=Mobile
MB_N_MCR=Mobile Device Registration
FL_MT=Financial Limits
FL_N_CLT=Create Limit
FL_N_CLP=Create Limit Package
FL_N_ULP=Update Limit Package
FL_N_DLT=Delete Limit
FL_N_DLP=Delete Limit Package
PC_F_CDPR=Domestic Payer
PC_F_DPR=Domestic Payer
PC_F_CDPI=Domestic Payin Pay Later
PC_F_DPI=Domestic Payin Pay Later
USPM=UserSegment Map
USPM_N_UM=Update Product Mapping
UM_N_TSR=Create Token Seed
USPM_N_CM=Create Product Mapping
AU=Authentication Maintenance
AU_N_CAM=Authentication - Create
AU_N_UAM=Authentication - Edit
AM_VIEW=Authentication - View
PC_CM_ME=登入
CC_N=Credit Cards
CC_N_RP=Reset Credit Card Pin
CH_N_RP=Reset Debit Card Pin
CH_N_LES=List Demand Deposit Electronic Statement
LN_N_LES=List Loan Electronic Statement
LO_UP=Location Upload
AU_USQ_U=設置安全問題
ML_N_DM=Delete Mailers
PC_F_UK_FAS=Domestic UK Payment - Faster
TD_N_LES=List Deposit Electronic Statement
ML_N_CM=Create Mailers
CH_N_DES=Demand Deposit Electronic Statement Download
LN_N_DES=Loan Electronic Statement download
PC_F_UK_NOU=Domestic UK Payment - NON URGENT
TD_N_DES=Deposit Electronic Statement download
ML_N_UM=Update Mailers
ML=Mailers
PC_F_UK_URG=Domestic UK Payment - URGENT
PC_F_INTRNL=Internal Transfer
PC_F_IT=International Transfer
PC_F_ITF=Internal Transfer Pay Now
PC_F_ITFI=Internal Transfer Pay Later/SI
PC_F_ITR=海外轉賬
PC_F_ITRI=International Payment Pay Later/SI
PC_F_SELF=Self Transfer
PC_F_SFT=Own Account Transfer
PC_F_SFTI=Own Account Transfer Pay Later/SI
PC_F_DOMDRAFT=Domestic Draft
PC_F_SEPA_CARD=Domestic SEPA Payment - CARD
PC_F_SEPA_CREDIT=Domestic SEPA Payment - CREDIT
CM=All Common Transactions
MT=All Admin Maintenances
IT=All Inquiry Transactions
NT=All Non Financial Transactions
FT=All Financial Transactions
TD_F_OTD=定期存款開立
TD_N_ATD=修改定期存款到期指示
TD_F_RTD=定期存款提取
LN_F_LRP=Loan and Finance Repayment
CH_N_CBR=申請支票簿
CH_N_CIN=停止支票過數
CH_I_CSE=支票簿查詢
PC_F=Payments
PC_N=Payments
TD_F=Term Deposits - Financial
TD_N=Term Deposits
LN_F=Loans
LN_N=Loans
CH_F=CASA
CH_N=CASA
TD_F_TTD=Deposit Top-Up
PC_F_BPT=Bill Payment
PC_N_PBR=Add Biller
PC_F_PIC=Instruction Cancellation
PC_N_DOP=Create Domestic Payee
PC_N_UPBR=Edit Biller
PC_N_DPBR=Delete Biller
CH_N_RAS=Request Demand Deposit Statement
CH_N_EST=E-Statement Subscription
CH_N_BDC=Block Debit Card
CH_N_RDCP=Request Debit Card Pin
CH_N_ADC=Apply Debit Card
TD_N_RAS=Request Deposit Statement
AP_N_UUG=Update User Group
AP_N_AUG=Add User to Group
AP_N_DUG=Delete User from Group
AP_N_UWF=Update Workflow
AP_N_DWF=Delete Workflow
AT_N_CCA=賬戶及服務管理 - 建立
AT_N_DCA=賬戶及服務管理 - 刪除
AT_N_UCA=賬戶及服務管理 - 編輯
AT=Account Transactions
PP=Party Preference
PP_N_CRE=賬戶資料 - 建立
PP_N_UPD=賬戶資料 - 編輯
PP_N_DEL=賬戶資料 - 刪除
PP_N_VIEW=賬戶資料 - 查看
RM_MT=交易批核規則管理
AP_N_CR=交易批核規則管理-建立規則
AP_N_UR=交易批核規則管理-編輯規則
AP_N_DR=交易批核規則管理-刪除規則
UM=User Management
AP=Approvals
RP=System Rules
UM_N_UCR=Create User
UM_N_UMD=Modify User
UM_N_UDL=Delete User
AP_N_CUG=Create User Group
AP_N_CWF=Create Workflow
AP_N_CRU=Create Rule
RP_N_RPM=System Rules
UM_N_UGM=Assign Group to User
UM_N_UGC=Change User Status
UAT=用戶賬戶及服務管理
UAT_N_CA=用戶賬戶及服務管理-配對(創立)
UAT_N_DA=刪除用戶賬戶及服務的訪問權限
UAT_N_UA=用戶賬戶及服務管理-修改
UAT_N_HUA_NEW=HTH 用戶賬戶及服務訪問-建立
UAT_N_HUA_EDT=HTH 用戶賬戶及服務訪問-修改
UAT_N_HUA_DEL=HTH 用戶賬戶及服務訪問-刪除
PC_F_IDD=International Demand Draft
TD_I_RI=Redemption Inquiry
FU_R_IFT=Internal Transfer - Record Level Approval
FU_R_ILFT=International Payment - Record Level Approval
FU_R_DFT=Domestic Transfer - Record Level Approval
FU_R_MFT=Mixed Payment - Record Level Approval
FU_MT=File Upload
FU_FT=File Upload
FU_F_ILFT=International Payment - File Level Approval
FU_F_DFT=Domestic Payment - File Level Approval
FU_F_MFT=Mixed Payment - File Level Approval
FU_F_AILFT=International Payment - Upload
FU_F_ADFT=Domestic Payment - Upload
FU_F_AMIX=Mixed Payment - Upload
FU_F_IFT=Internal Transfer - File Level Approval
FU_F_AIFT=Internal Transfer - Upload
FU_N_CFR=Create File Identifier Registration
FU_N_UFR=Update File Identifier Registration
FU_N_CUM=Create User File Identifier Mapping
FU_N_UUM=用戶文件檢驗配對 – 編輯
FU_N_DUM=Delete User File Identifier Mapping
FU_N_DFR=Delete File Identifier Registration
PC_F_CBPT=Bill Payment
PC_N_CDDP=Create Demand Draft Payee
PC_F_CITF=Internal Transfer Pay Now
PC_F_CDFTI=Domestic Payment Pay Later
PC_F_CIDD=International Demand Draft Pay Now
PC_F_CITFI=Internal Transfer Pay Later/SI
PC_F_CITR=International Payment Pay Now
PC_F_CSFT=Own Account Transfer Pay Now
PC_F_CDDDI=Domestic Demand Draft Pay Later
PC_F_DDDI=Domestic Demand Draft Pay Later
PC_F_CITRI=International Payment Pay Later/SI
PC_F_CSFTI=Own Account Transfer Pay Later/SI
PC_F_CDDD=Domestic Demand Draft Pay Now
PC_F_CIDDI=International Demand Draft Pay Later
PC_F_DFTI=Domestic Payment Pay Later/SI
PC_F_IDDI=International Demand Draft Pay Later
PC_F_DFT=Domestic Payment
PC_F_GNIP=Adhoc Internal Transfer
PC_F_GNITNP=Adhoc International Payment
PC_F_GNDP=Adhoc Domestic Payment
CH_I=CASA Inquiries
LN_I=Loan Inquiries
TD_I=TD Inquiries
PC_I=Payments Inquiries
CH_I_AS=賬戶概覽
CH_I_AA=查看賬戶記錄
CH_I_AD=賬戶詳細資訊
TD_I_AS=定期存款交易記錄
TD_I_AA=定期存款查詢
TD_I_AD=定期存款詳細資訊
LN_I_SI=Schedule Inquiry
LN_I_DD=Disbursement Details
LN_I_LS=Loan Summary
LN_I_LD=Loan Details
LN_I_LA=Loan Account Activity
PC_I_INRL=匯入匯款概覽
PC_I_OUTRL=付款追蹤服務
PC_I_INSTRL=預設付款指示查詢
TD_I_CM=TD Calculate Maturity
MN=全部維護
PC_M=Payee
PC_F_CDFT=Domestic Payment Pay Now
PAT=Linkage Account Transactions
PAT_N_CA=Create Linkage Account Transaction Mapping
PAT_N_DA=Delete Linkage Account Transaction Mapping
PAT_N_UA=Update Linkage Account Transaction Mapping
LIN=Party To Party Linkage
GL_N_CGC=Create Goal Category
GL_N_RGC=Read Goal Category
GL_N_UGC=Update Goal Category
GL_N_DGC=Delete Goal Category
GL_N_LGC=List Goal Category
GL_N_CGCL=Goal Calculator
GL_N_CGCS=Save Goal Calculation
GL_N_RGCS=Read Goal Calculation
GL_N_RGP=Read Goal Product
GL_N_LGP=List Goal Product
AL=Alert Maintenance
AL_N_CR=Create Alert
AL_N_UPD=Update Alert
AL_N_DEL=Delete Alert
UP_LIN=Update Party To Party Linkage
CP_LIN=Create Party To Party Linkage
SP_N_CSC=Create Spend Category
SP_N_DSC=Delete Spend Category
SP_N_FCT=Fetch categorized Transactions
SP_N_LSC=List Spend Category
SP_N_RSC=Read Spend Category
SP_N_USC=Update Spend Category
PFM_F=PFM
GL_N_CGLA=Create Goal Account
GL_N_RGLA=Read Goal Account
GL_N_UGLA=Update Goal Account
GL_N_LGLA=List Goal Account
GL_N_CSIGLA=Create Standing Instruction Goal Account
SM=Transaction Blackout
SM_N_CTB=Create Transaction Blackout
SM_N_DTB=Delete Transaction Blackout
SM_N_UTB=Update Transaction Blackout
PAM=Payment Admin Maintenance
PC_N_PCL=Payee Restriction Set-up
PC_F_DOM_NEFT=Domestic Payment - NEFT
PC_F_DOM_RTGS=Domestic Payment - RTGS
PC_F_NPDOM=Domestic Payment
PC_F_SEPACREDIT=Domestic Payment - SEPA Credit
PC_F_DOM_IMPS=Domestic Payment - IMPS
SP_N_PUCT=Persist uncategorized spend transactions
UM_N_RCR=Reset Credentials
APT=Transaction Approval
PA_APT=執行行動
GL_N_CNSIGLA=Cancel Standing Instruction Goal Account
GL_N_PGLA=Payin Goal Account
GL_N_REGLA=Redeem Goal Account
GL_N_FTGLA=Fetch Transactions Goal Account
FU_MN=File Upload
FU_R_ILP=International Payee - Record Level Approval
FU_F_ILP=International Payee - File Level Approval
FU_R_DDP=Demand Draft Payee - Record Level Approval
FU_F_DDP=Demand Draft Payee - File Level Approval
FU_F_IP=Internal Payee - File Level Approval
FU_F_DP=Domestic Payee - File Level Approval
FU_R_DP=Domestic Payee - Record Level Approval
FU_R_IP=Internal Payee - Record Level Approval
FU_F_MPY=Mixed Payee - File Level Approval
UGSM=User Group Subject Mapping
UGSM_N_CM=Create User Group Subject Mapping
UGSM_N_DM=Delete User Group Subject Mapping
UGSM_N_UM=Update User Group Subject Mapping
PC_F_DDD=Domestic Demand Draft
PC_F_DOM=Domestic Payment
PC_F_INTRNL_ADHOC=Adhoc Internal Transfer - Limits
SG_M_LSE=List User Segment
SG_M_USE=Update User Segment
SG_M_CSE=Create User Segment
SG_M_RSE=Read User
FU_F_OP=Other Party Maintenance - File Level Approval
FU_R_OP=Other Party Maintenance - Record Level Approval
TF_N_TACM=Trade Additional Condition
TFAC_CR=Create Additional Condition Maintenance
TFAC_UP=Update Additional Condition Maintenance
FU_F_LC=Letter Of Credit - File Level Approval
FU_R_LC=Letter Of Credit - Record Level Approval
TF_N_TCM=Trade Clause Maintenance
TFCM_CR=Create Trade Clause Maintenance
TFCM_UP=Update Trade Clause Maintenance
FL_C_MIHO=每日交易限額維護 - 提高限額
FL_C_MDHO=每日交易限額維護 - 減低限額

PC_F_CRNSFT=轉賬 - 我的賬戶轉賬
PC_F_CRNIFT=轉賬至已登記賬戶 - 東亞銀行（香港）
PC_F_CRNBCT=轉賬至已登記賬戶 - 東亞銀行（中國）
PC_F_CRNDFT=轉賬至已登記賬戶 - 本地轉賬
PC_F_CRNDFT_FPS=轉賬至已登記賬戶 - 本地轉賬 [快速支付系统]
PC_F_CRNINFT=轉賬至已登記賬戶 - 海外轉賬
PC_F_GCRNIFT=轉賬至未登記賬戶 - 東亞銀行（香港）轉賬
PC_F_GCRNBCT=轉賬至未登記賬戶 - 東亞銀行（中國）
PC_F_GCRNDFT=轉賬至未登記賬戶 - 本地轉賬
PC_F_GCRNDFT_FPS=轉賬至未登記賬戶 - 本地轉賬 [快速支付系统]
PC_F_GCRNINFT=轉賬至未登記賬戶 - 海外轉賬

PC_F_CRNSFT_SI=預設付款 - 轉賬 - 我的賬戶轉賬
PC_F_CRNIFT_SI=預設付款 - 轉賬至已登記賬戶 - 東亞銀行（香港）
PC_F_CRNBCT_SI=預設付款 - 轉賬至已登記賬戶 - 東亞銀行（中國）
PC_F_CRNDFT_SI=預設付款 - 轉賬至已登記賬戶 - 本地轉賬
PC_F_CRNDFT_FPS_SI=預設付款 - 轉賬至已登記賬戶 - 本地轉賬 [快速支付系统]
PC_F_CRNINFT_SI=預設付款 - 轉賬至已登記賬戶 - 海外轉賬
PC_F_GCRNIFT_SI=預設付款 - 轉賬至未登記賬戶 - 東亞銀行（香港）轉賬
PC_F_GCRNBCT_SI=預設付款 - 轉賬至未登記賬戶 - 東亞銀行（中國）
PC_F_GCRNDFT_SI=預設付款 - 轉賬至未登記賬戶 - 本地轉賬
PC_F_GCRNDFT_FPS_SI=預設付款 - 轉賬至未登記賬戶 - 本地轉賬 [快速支付系统]
PC_F_GCRNINFT_SI=預設付款 - 轉賬至未登記賬戶 - 海外轉賬

PC_F_NPSELF=我的賬戶
PC_F_NPINTRNL=東亞銀行（香港）
PC_F_NPINTRNL_ADHOC=轉賬至未登記賬戶 - 東亞銀行（中國）
PC_F_NPIT=海外轉賬
PC_F_NPIT_ADHOC=轉賬至未登記賬戶 - 海外轉賬

PC_N_CIP=添加收款人 - 東亞銀行（香港）
PC_N_UIP=修改收款人 - 東亞銀行（香港）
PC_N_DIP=刪除收款人 - 東亞銀行（香港）
PC_N_DOP_VT=添加收款人 - 本地轉賬
PC_N_UDOP_VT=修改收款人 - 本地轉賬
PC_N_DDP_VT=刪除收款人- 本地轉賬
PC_N_CITNP=添加收款人 - 海外轉賬
PC_N_UITNP=修改收款人 - 海外轉賬
PC_N_DITNP=刪除收款人 - 海外轉賬
PC_N_CBP=添加收款人 - 東亞銀行（中國）
PC_N_UBP=修改收款人 - 東亞銀行（中國）
PC_N_DBP=刪除收款人 - 東亞銀行（中國）
PC_N_CIP_A=添加收款人 - 東亞銀行（香港）
PC_N_UIP_A=修改收款人 - 東亞銀行（香港）
PC_N_DIP_A=刪除收款人 - 東亞銀行（香港）
PC_N_DOP_VT_A=添加收款人 - 本地轉賬
PC_N_UDOP_VT_A=修改收款人 - 本地轉賬
PC_N_DDP_VT_A=刪除收款人- 本地轉賬
PC_N_CITNP_A=添加收款人 - 海外轉賬
PC_N_UITNP_A=修改收款人 - 海外轉賬
PC_N_DITNP_A=刪除收款人 - 海外轉賬
PC_N_CBP_A=添加收款人 - 東亞銀行（中國）
PC_N_UBP_A=修改收款人 - 東亞銀行（中國）
PC_N_DBP_A=刪除收款人 - 東亞銀行（中國）

MT_M_COP=開放 API 服務 - 設定 - 建立
MT_M_UOP=開放 API 服務 - 設定
MT_N_AFP=啟用轉數快賬戶綁定服務
MT_N_EFP =編輯轉數快賬戶綁定服務
MT_N_TFP =終止轉數快賬戶綁定服務
MT_N_RFP =重啟轉數快賬戶綁定服務
MT_N_VFP =轉數快賬戶綁定服務 - 查看
PC_F_PIC_SFT=取消預設付款指示 - 我的賬戶 - 刪除
PC_F_PIC_IFT=取消預設付款指示 - 東亞銀行（香港） - 刪除
PC_F_PIC_BCT=取消預設付款指示 - 東亞銀行（中國）- 刪除
PC_F_PIC_DFT=取消預設付款指示 - 本地轉賬 - 刪除
PC_F_PIC_INFT=取消預設付款指示 - 海外轉賬 - 刪除

EB_F_BP_SI=預設賬單繳費交易
EB_F_BP=賬單繳費
EB_F_BP_D=取消預設賬單繳費交易
OAC_REVOKE=撤回同意第三方服務供應商
MT_N_UUS=用戶管理-編輯
MT_N_CUS=用戶管理-建立
MT_N_RUS=用戶管理-查看
CH_N_RADHSTMT=申請臨時結單
CH_N_DADHSTMT=刪除臨時結單申請
CH_N_LADHSTMT=臨時結單概覽
UM_ID_MU=ID Maintenance - Login ID/Phone Banking ID- Edit
UM_ID_MR=ID Maintenance - Inquiry (Login/Phone Banking Pin) Search/View
UM_ID_MD=ID Maintenance - Login ID/Phone Banking ID- Delete
UM_ID_MC=ID Maintenance - Create (Login/Phone Banking Pin)
EADESTMTU=Account Preference Settings - Edit
EADESTMTUR=用户注册概览
CASA=往來及儲蓄
EB_F=賬單繳費
TD_FT=定期存款
TD_NT=定期存款
CH_NF=支票
TPS_MT=第三方服務供應商同意管理
OAC_GRANT=給予同意第三方服務供應商
OAC_REFRESH=續期同意第三方服務供應商
EA_MN=電子結單/電子交易通知
EA_NT=電子結單/電子交易通知
CH_N_ESTM=查看電子結單
CH_N_EADV=查看電子交易通知
LM_N_EADV=查看電子交易通知
FPS_MN=轉數快賬戶綁定服務
FPS=轉數快賬戶綁定服務
FL_C_MIHO=提高每日交易限額
FL_C_MDHO=減低每日交易限額
FL_C_RHO=每日交易限額 - 查閱
FL_C_UHO=每日交易限額 - 編輯
FL_C_MT=每日交易限額維護
SP_CUST_R=特殊限額權限維護 - 查看
UM_MT=用戶管理
UM_N_ULS=更改用戶狀態
UM_N_USD=更改網上銀行使用權限
OPN_MT=開放API服務-設置
UM_N_ULS_UL=更改用戶狀態
UM_N_ULS_L=更改用戶狀態
EADESTMTC=賬戶偏好設定 - 更新
EADESTMTU=賬戶偏好設定
EADESTMTL=賬戶偏好設定
FXRATECALC=外匯計算器轉換請求
FXRATEALC=設立到價提示
FXRATEALU=Edit Rate Alert
FXRATEALD=刪除到價提示
FXRATEALL=List Rate Alert
FXRATEWLC=設立外幣匯價列表
FXRATEWLU=Edit FX Watchlist
FXRATEWLD=刪除外幣匯價列表
FXRATEWLL=List FX Watchlist
FXRATECRL=外匯主頁
TRF_FT=轉賬-查詢
TRFTOA_FT=轉賬-我的賬戶
TRFTOTA_FT=轉賬-其他賬戶
FTOA_TD=定期存款
PC_F_SED=設立新電子直接付款授權
PC_F_AED=編輯電子直接付款授權
PC_F_AED_CONFIRM=確認電子直接付款授權
PC_F_AED_REJECT=拒絕電子直接付款授權
PC_F_AED_SUSPEND=暫停電子直接付款授權
PC_F_AED_RESUME=恢復電子直接付款授權
PC_F_AED_TERMINATE=終止電子直接付款授權
PC_F_LED=電子直接付款授權摘要
EDDA=電子直接付款授權
M_DB_AUDIT=主頁
CASA_DB_AUDIT=往來及儲蓄概覽主頁
TD_DB_AUDIT=定期存款主頁
AU_CZ_LOGOUT=登出
CM_N_FP=忘記密碼
CM_N_FPN=忘記密碼
CM_N_CUSQTN=設置安全問題
CH_N_ESTMEADV_DW=下載結單
CM_CH_SC=更改簽署人密碼
CM_N_CC=更改登入密碼
CM_N_FCC=強制更改密碼
BU_AUTOPAY_CREATE=自動轉賬
BU_PAYROLL_CREATE=支薪
BU_COLLECTION_CREATE=收款
FU_F_APC=文件上傳
APC=自動轉賬、支薪及收款
FU_VW=文件上傳查詢
BU_SI_LIST=自動轉賬 支付薪資及託收查詢
BU_SI_DELETE_AP=自動轉賬輸入 - 預設指示刪除
BU_SI_DELETE_PR=支薪輸入 - 預設指示刪除
BU_SI_DELETE_FU=文件上傳 - 預設指示刪除
BU_SI_DELETE_CL=收款輸入 - 預設指示刪除
FU_UP_AP=上傳文件自動轉賬
FU_UP_PR=上傳文件支薪
FU_UP_CL=上傳文件收款
CZ_PA_APT=多重交易審批
CTD_C=Preferential Time Deposit Enquiry and Maintenance
IN_F_CIMPF=供款查詢
IN_F_CMPF=公司詳情
IN_F_SMPF=成員詳情
IN_F_CDMPF=供款詳情
IN_F_VPMPF=自願性供款的歸屬規則
IN_F_DIMPF=拖欠供款查詢
IN_F_DCMPF=拖欠供款查詢詳情
IN_F_MPFINFO=強積金資料
MPF=強積金
IN_F_SATMPF=供款詳情
LMI_F_CLM=設立指示
LMI_I_VLLM=指示列表
LMI_I_VHLLM=交易記錄及報告
MRCH_I_AACT=賬戶交易下載
MRCH=商戶服務
LMI_I_VLM=驗證 LM 指令
LMI=流動資金管理指示
LMI_F_ULM=更新LM指令
LMI_F_DLM=刪除LM指令
LMI_I_VLMD=查看 LM 指令詳細信息
LMI_F_ACLM=設立指示 - 東亞銀行 (香港) - 建立
LMI_F_CCLM=設立指示 - 東亞銀行 (中國) - 建立
LMI_F_LCLM=設立指示 - 本地 - 建立
LMI_F_TCLM=設立指示 - 海外 - 建立
LMI_F_OCLM=設立指示 - 我的賬戶 - 建立
LMI_F_AULM=設立指示 - 東亞銀行 (香港) - 編輯
LMI_F_CULM=設立指示 - 東亞銀行 (中國) - 編輯
LMI_F_LULM=設立指示 - 本地 - 編輯
LMI_F_TULM=設立指示 - 海外 - 編輯
LMI_F_OULM=設立指示 - 我的賬戶 - 編輯
LMI_F_ADLM=設立指示 - 東亞銀行 (香港) - 刪除
LMI_F_CDLM=設立指示 - 東亞銀行 (中國) - 刪除
LMI_F_LDLM=設立指示 - 本地 - 刪除
LMI_F_TDLM=設立指示 - 海外 - 刪除
LMI_F_ODLM=設立指示 - 我的賬戶 - 刪除
FRXAGREE=外匯交易
FT_F_PFR=外匯交易
MRCH_I_AA=是日交易記錄
MRCH_I_MTE=商戶交易查詢
MRCH_I_DMA=商戶存入銷售單通知下載
MRCH_N_LDMU=Merchant User Maintenance - Edit Pin Mapping
MRCH_N_LDMC=Merchant User Maintenance - Edit Pin Mapping
MRCH_I_AACH=賬戶記錄
MRCH_N_LMUP=Merchant User Maintenance - View PIN Mapping
IVM=投資
IVM_N_ST=股票買賣
IVM_R_A=風險評估
INV_A=投資賬戶
INV_A_AD=投資概覽
INV_A_TH=投資交易記錄
BP_FT=轉賬-批量付款
BPFU_BP_FT=批量付款文件上傳
BPI_BP_FT=批量付款查詢
UFO_BP_FT=上傳文件概覽
FPSMRCH=「轉數快」商戶收款服務
FPSMRCH_N_QR=創建轉數快二維碼
FPSMRCH_N_QRACREPO=二維碼活動紀錄
FPSMRCH_N_PTH=轉數快商戶收款交易紀錄
FPSMRCH_N_CFP=創建轉數快二維碼
FPSMRCH_N_LPA=二維碼活動紀錄
PC_F_CRNSFT=我的賬戶轉賬
TL_N=貿易和貸款
TF_N_TAD=貿易和貸款主目錄
BT_FT=轉賬-批量轉賬
PC_F_BTFT=批量轉賬文件上傳
PC_F_BTIQ=批量轉賬查詢
PC_F_BTOV=上傳文件概覽
PC_I_OUTRIU=付款追蹤服務
PC_I_OUTRL=付款追蹤服務
PC_I_INRIU=付款追蹤服務
