LAT_N_DA=用户账户及服务管理 - 删除 (关联账户配对)
LAT_N_CA=用户账户及服务管理 - 创建 (关联账户配对)
LAT_N_UA=用户账户及服务管理 - 编辑 (关联账户配对)


PC_N_CIP=管理收款人 - 东亚银行（香港） - 建立
PC_N_UIP=管理收款人 - 东亚银行（香港） - 更新

PC_N_DOP_VT=管理收款人 - 本地转账 - 建立
PC_N_UDOP_VT=管理收款人 - 本地转账 - 更新

PC_N_CITNP=管理收款人 - 海外转账 - 建立
PC_N_UITNP=管理收款人 - 海外转账 - 更新

PC_N_CBP=管理收款人 - 东亚银行（中国） - 建立
PC_N_UBP=管理收款人 - 东亚银行（中国） - 更新

FU_F_APC=文件上传

BU_AUTOPAY_CREATE=自动转账
BU_PAYROLL_CREATE=支薪

PC_F_SED=设立新电子直接付款授权
PC_F_AED=编辑电子直接付款授权
PC_F_AED_CONFIRM=确认电子直接付款授权
PC_F_AED_REJECT=拒绝电子直接付款授权
PC_F_AED_SUSPEND=暂停电子直接付款授权
PC_F_AED_RESUME=恢复电子直接付款授权
PC_F_AED_TERMINATE=终止电子直接付款授权

PC_F_GCRNIFT_SI=预设付款 - 转账至未登记账户 - 东亚银行（香港）
PC_F_GCRNBCT_SI=预设付款 - 转账至未登记账户 - 东亚银行（中国）
PC_F_GCRNDFT_SI=预设付款 - 转账至未登记账户 - 本地转账
PC_F_GCRNDFT_FPS_SI=预设付款 - 转账至未登记账户 - 本地转账
PC_F_GCRNINFT_SI=预设付款 - 转账至未登记账户 - 海外转账

PC_F_GCRNIFT=转账至未登记账户 - 东亚银行（香港）
PC_F_GCRNBCT=转账至未登记账户 - 东亚银行（中国）
PC_F_GCRNDFT=转账至未登记账户 - 本地转账
PC_F_GCRNDFT_FPS=转账至未登记账户 - 本地转账
PC_F_GCRNINFT=转账至未登记账户 - 海外转账

UAT_N_CA=用户账户及服务管理-配对(创建)
UAT_N_DA=删除用户账户及服务的访问权限
UAT_N_UA=用户账户及服务管理-修改
UAT_N_HUA_NEW=HTH 用户账户及服务访问-创建
UAT_N_HUA_EDT=HTH 用户账户及服务访问-修改
UAT_N_HUA_DEL=HTH 用户账户及服务访问-删除

UM_N_ULS_UL=更改用户状态

UM_N_USD=更改网上银行使用权限

MT_N_CUS=用户管理-创建
MT_N_UUS=用户管理-编辑

FL_C_MIHO=每日交易限額維護 - 提高限額

EB_F_BP=账单缴费
EB_F_BP_SI=预设账单缴费
