LAT_N_CA=User Accounts & Services Access - Create (Associated Accounts Mapping)
LAT_N_DA=User Accounts & Services Access - Delete (Associated Accounts Mapping)
LAT_N_UA=User Accounts & Services Access - Edit (Associated Accounts Mapping)


PC_N_CIP=Manage Beneficiaries - BEA(HK) - Create
PC_N_UIP=Edit Beneficiary - BEA (HK) Transfers

PC_N_DOP_VT=Manage Beneficiaries -Local Payments - Create
PC_N_UDOP_VT=Edit Beneficiary - Local Payments

PC_N_CITNP=Manage Beneficiaries - Overseas Payments - Create
PC_N_UITNP=Edit Beneficiary - Overseas Payments

PC_N_CBP=Manage Beneficiaries -  BEA (China) - Create
PC_N_UBP=Edit Beneficiary - BEA (China)

BU_AUTOPAY_CREATE=Autopay
BU_PAYROLL_CREATE=Payroll

FU_F_APC=File Upload

PC_F_SED=Set Up a New e-Direct Debit Authorisation ("eDDA")
PC_F_AED=Edit e-Direct Debit Authorisation ("eDDA")
PC_F_AED_CONFIRM=Confirm e-Direct Debit Authorisation ("eDDA")
PC_F_AED_REJECT=Reject e-Direct Debit Authorisation ("eDDA")
PC_F_AED_SUSPEND=Suspend e-Direct Debit Authorisation ("eDDA")
PC_F_AED_RESUME=Resume e-Direct Debit Authorisation ("eDDA")
PC_F_AED_TERMINATE=Terminate e-Direct Debit Authorisation ("eDDA")

PC_F_GCRNIFT_SI=Scheduled Payment - Transfer to Non-designated Account - BEA (HK)
PC_F_GCRNBCT_SI=Scheduled Payment - Transfer to Non-designated Account - BEA(China)
PC_F_GCRNDFT_SI=Scheduled Payment - Transfer to Non-designated Account - Local Payments
PC_F_GCRNDFT_FPS_SI=Scheduled Payment - Transfer to Non-designated Account - Local Payments [FPS]
PC_F_GCRNINFT_SI=Scheduled Payment - Transfer to Non-designated Account - Overseas Payments

PC_F_GCRNIFT=Transfer to Non-designated Account - BEA (HK)
PC_F_GCRNBCT=Transfer to Non-designated Account - BEA (China)
PC_F_GCRNDFT=Transfer to Non-designated Account - Local Payments
PC_F_GCRNDFT_FPS=Transfer to Non-designated Account - Local Payments [FPS]
PC_F_GCRNINFT=Transfer to Non-designated Account - Overseas Payments

UAT_N_CA=User Accounts & Services Access - Mapping (Create)
UAT_N_DA=User Accounts & Services Access - Delete
UAT_N_UA=User Accounts & Services Access - Edit
UAT_N_HUA_NEW=HTH User Accounts & Services Access - Create
UAT_N_HUA_EDT=HTH User Accounts & Services Access - Edit
UAT_N_HUA_DEL=HTH User Accounts & Services Access - Delete

UM_N_ULS_UL=Update User Status

UM_N_USD=Update Online Banking Access

MT_N_CUS=User Management - Create
MT_N_UUS=User Management - Edit

FL_C_MIHO=Increase Daily Transaction Limit

EB_F_BP=Bill Payments
EB_F_BP_SI=Bill Payments
