LAT_N_DA=用戶賬戶及服務管理 - 刪除 (關聯賬戶配對)
LAT_N_CA=用戶賬戶及服務管理 - 建立 (關聯賬戶配對)
LAT_N_UA=用戶賬戶及服務管理 - 編輯 (關聯賬戶配對)


PC_N_CIP=管理收款人 - 東亞銀行（香港） - 建立
PC_N_UIP=管理收款人 - 東亞銀行（香港） - 更新

PC_N_DOP_VT=管理收款人 - 本地轉賬 - 建立
PC_N_UDOP_VT=管理收款人 - 本地轉賬 - 更新

PC_N_CITNP=管理收款人 - 海外轉賬 - 建立
PC_N_UITNP=管理收款人 - 海外轉賬 - 更新

PC_N_CBP=管理收款人 - 東亞銀行（中國） - 建立
PC_N_UBP=管理收款人 - 東亞銀行（中國） - 更新

FU_F_APC=文件上傳

BU_AUTOPAY_CREATE=自動轉賬
BU_PAYROLL_CREATE=支薪

PC_F_SED=設立新電子直接付款授權
PC_F_AED=編輯電子直接付款授權
PC_F_AED_CONFIRM=確認電子直接付款授權
PC_F_AED_REJECT=拒絕電子直接付款授權
PC_F_AED_SUSPEND=暫停電子直接付款授權
PC_F_AED_RESUME=恢復電子直接付款授權
PC_F_AED_TERMINATE=終止電子直接付款授權

PC_F_GCRNIFT_SI=預設付款 - 轉賬至未登記賬戶 - 東亞銀行（香港）
PC_F_GCRNBCT_SI=預設付款 - 轉賬至未登記賬戶 - 東亞銀行（中國）
PC_F_GCRNDFT_SI=預設付款 - 轉賬至未登記賬戶 - 本地轉賬
PC_F_GCRNDFT_FPS_SI=預設付款 - 轉賬至未登記賬戶 - 本地轉賬
PC_F_GCRNINFT_SI=預設付款 - 轉賬至未登記賬戶 - 海外轉賬

PC_F_GCRNIFT=轉賬至未登記賬戶 - 東亞銀行（香港）
PC_F_GCRNBCT=轉賬至未登記賬戶 - 東亞銀行（中國）
PC_F_GCRNDFT=轉賬至未登記賬戶 - 本地轉賬
PC_F_GCRNDFT_FPS=轉賬至未登記賬戶 - 本地轉賬
PC_F_GCRNINFT=轉賬至未登記賬戶 - 海外轉賬

UAT_N_CA=用戶賬戶及服務管理-配對(創立)
UAT_N_DA=刪除用戶賬戶及服務的訪問權限
UAT_N_UA=用戶賬戶及服務管理-修改
UAT_N_HUA_NEW=HTH 用戶賬戶及服務訪問-建立
UAT_N_HUA_EDT=HTH 用戶賬戶及服務訪問-修改
UAT_N_HUA_DEL=HTH 用戶賬戶及服務訪問-刪除

UM_N_ULS_UL=更改用戶狀態

UM_N_USD=更改網上銀行使用權限

MT_N_CUS=用戶管理-建立
MT_N_UUS=用戶管理-編輯

FL_C_MIHO=每日交易限額維護 - 提高限額

EB_F_BP=賬單繳費
EB_F_BP_SI=預設賬單繳費交易
