-- BCOH2H-538 / BCOH2H-595: Host to Host User Accounts & Services Access schema.
-- Prerequisites:
--   20260416_HTH_Management/1_HTH_Management_Schema.sql
--   20260803_User_Channel_Type/1_User_Channel_Type_Schema.sql
-- This is a one-time DDL script. Do not re-run after the objects have been created.

-- Effective access header. One row represents one HTH user in one account-owning party context.
CREATE TABLE HTH_BEAUAT.HTH_USER_ACCESS (
  ID                    VARCHAR2(36 BYTE)  NOT NULL,
  PARTY_ID              VARCHAR2(64 BYTE)  NOT NULL,
  CLOSE_ID              VARCHAR2(255 BYTE) NOT NULL,
  ACCESS_PARTY_ID       VARCHAR2(64 BYTE)  NOT NULL,
  LINKAGE_TYPE          VARCHAR2(16 BYTE)  NOT NULL,
  OBJECT_STATUS         VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  CREATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE         DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY       VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE      DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_VERSION_NUMBER NUMBER             DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_USER_ACCESS PRIMARY KEY (ID),
  CONSTRAINT UK_HTH_USER_ACCESS_CTX UNIQUE
    (PARTY_ID, CLOSE_ID, ACCESS_PARTY_ID, LINKAGE_TYPE),
  CONSTRAINT FK_HTH_UA_USER_PROFILE FOREIGN KEY (PARTY_ID, CLOSE_ID)
    REFERENCES HTH_BEAUAT.HTH_USER_PROFILE (PARTY_ID, CLOSE_ID),
  CONSTRAINT CK_HTH_UA_LINKAGE CHECK
    (LINKAGE_TYPE IN ('RELATED', 'ASSOCIATED')),
  CONSTRAINT CK_HTH_UA_STATUS CHECK
    (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEAUAT.IX_HTH_UA_ACCESS_PARTY
  ON HTH_BEAUAT.HTH_USER_ACCESS (ACCESS_PARTY_ID);

COMMENT ON TABLE HTH_BEAUAT.HTH_USER_ACCESS IS
  'Effective HTH user access header by user and account-owning party.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS.PARTY_ID IS
  'Primary corporate party that owns the HTH user.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS.CLOSE_ID IS
  'HTH user CloseID from HTH_USER_PROFILE.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS.ACCESS_PARTY_ID IS
  'Party that owns the linked accounts.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS.LINKAGE_TYPE IS
  'RELATED or ASSOCIATED.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS.OBJECT_VERSION_NUMBER IS
  'Aggregate version used for optimistic locking of the effective access.';

-- Effective Current and Savings accounts granted to an HTH user.
CREATE TABLE HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT (
  ID                    VARCHAR2(36 BYTE)  NOT NULL,
  HTH_USER_ACCESS_ID    VARCHAR2(36 BYTE)  NOT NULL,
  ACCOUNT_NUMBER        VARCHAR2(64 BYTE)  NOT NULL,
  ACCOUNT_TYPE          VARCHAR2(8 BYTE)   NOT NULL,
  CURRENCY              VARCHAR2(3 BYTE),
  OBJECT_STATUS         VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  CREATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE         DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY       VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE      DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_VERSION_NUMBER NUMBER             DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_UA_ACCOUNT PRIMARY KEY (ID),
  CONSTRAINT UK_HTH_UA_ACCOUNT UNIQUE
    (HTH_USER_ACCESS_ID, ACCOUNT_NUMBER),
  CONSTRAINT FK_HTH_UAA_TO_ACCESS FOREIGN KEY (HTH_USER_ACCESS_ID)
    REFERENCES HTH_BEAUAT.HTH_USER_ACCESS (ID),
  CONSTRAINT CK_HTH_UAA_TYPE CHECK (ACCOUNT_TYPE = 'CSA'),
  CONSTRAINT CK_HTH_UAA_STATUS CHECK (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEAUAT.IX_HTH_UAA_ACCOUNT_NO
  ON HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT (ACCOUNT_NUMBER);

COMMENT ON TABLE HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT IS
  'Effective Current and Savings accounts granted to an HTH user.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT.ACCOUNT_NUMBER IS
  'Canonical unmasked account identifier; must not be logged in plain text.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT.ACCOUNT_TYPE IS
  'Only CSA is supported by BCOH2H-595.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT.CURRENCY IS
  'Display snapshot only; not used to validate account ownership.';

-- Effective API grants under each HTH user account.
CREATE TABLE HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT_API (
  ID                         VARCHAR2(36 BYTE)  NOT NULL,
  HTH_USER_ACCESS_ACCOUNT_ID VARCHAR2(36 BYTE)  NOT NULL,
  API_MASTER_ID              VARCHAR2(36 BYTE)  NOT NULL,
  OBJECT_STATUS              VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  CREATED_BY                 VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE              DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE           DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_VERSION_NUMBER      NUMBER             DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_UAA_API PRIMARY KEY (ID),
  CONSTRAINT UK_HTH_UAA_API UNIQUE
    (HTH_USER_ACCESS_ACCOUNT_ID, API_MASTER_ID),
  CONSTRAINT FK_HTH_UAAA_TO_ACCOUNT
    FOREIGN KEY (HTH_USER_ACCESS_ACCOUNT_ID)
    REFERENCES HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT (ID),
  CONSTRAINT FK_HTH_UAAA_TO_API FOREIGN KEY (API_MASTER_ID)
    REFERENCES HTH_BEAUAT.HTH_API_MASTER (ID),
  CONSTRAINT CK_HTH_UAAA_STATUS CHECK (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEAUAT.IX_HTH_UAAA_API
  ON HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT_API (API_MASTER_ID);

COMMENT ON TABLE HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT_API IS
  'Effective HTH API grants by HTH user account.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_ACCOUNT_API.API_MASTER_ID IS
  'References the active API definition in HTH_API_MASTER.';

-- Immutable header snapshot submitted into the maker/checker workflow.
CREATE TABLE HTH_BEAUAT.HTH_USER_ACCESS_REQUEST (
  ID                    VARCHAR2(36 BYTE)  NOT NULL,
  TRANSACTION_ID        VARCHAR2(64 BYTE)  NOT NULL,
  REFERENCE_NO          VARCHAR2(64 BYTE)  NOT NULL,
  ACTION_TYPE           VARCHAR2(16 BYTE)  NOT NULL,
  PARTY_ID              VARCHAR2(64 BYTE)  NOT NULL,
  CLOSE_ID              VARCHAR2(255 BYTE) NOT NULL,
  ACCESS_PARTY_ID       VARCHAR2(64 BYTE)  NOT NULL,
  LINKAGE_TYPE          VARCHAR2(16 BYTE)  NOT NULL,
  SUBMITTED_VERSION     NUMBER,
  USER_NAME             VARCHAR2(255 BYTE),
  FULL_NAME             VARCHAR2(255 BYTE),
  ACCESS_PARTY_NAME     VARCHAR2(255 BYTE),
  OBJECT_STATUS         VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  CREATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE         DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY       VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE      DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_VERSION_NUMBER NUMBER             DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_UA_REQUEST PRIMARY KEY (ID),
  CONSTRAINT UK_HTH_UAR_TXN UNIQUE (TRANSACTION_ID),
  CONSTRAINT UK_HTH_UAR_REF UNIQUE (REFERENCE_NO),
  CONSTRAINT CK_HTH_UAR_ACTION CHECK
    (ACTION_TYPE IN ('CREATE', 'EDIT', 'DELETE')),
  CONSTRAINT CK_HTH_UAR_LINKAGE CHECK
    (LINKAGE_TYPE IN ('RELATED', 'ASSOCIATED')),
  CONSTRAINT CK_HTH_UAR_STATUS CHECK
    (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEAUAT.IX_HTH_UAR_CONTEXT
  ON HTH_BEAUAT.HTH_USER_ACCESS_REQUEST
    (PARTY_ID, CLOSE_ID, ACCESS_PARTY_ID, LINKAGE_TYPE);

COMMENT ON TABLE HTH_BEAUAT.HTH_USER_ACCESS_REQUEST IS
  'Immutable HTH user access approval request header snapshot.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQUEST.TRANSACTION_ID IS
  'References the OBDX approval transaction identifier.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQUEST.REFERENCE_NO IS
  'Business reference displayed in approval and audit screens.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQUEST.SUBMITTED_VERSION IS
  'Effective header version submitted by Edit/Delete; null for initial Create.';

-- Account snapshot submitted with a maker request.
CREATE TABLE HTH_BEAUAT.HTH_USER_ACCESS_REQ_ACCOUNT (
  ID                         VARCHAR2(36 BYTE)  NOT NULL,
  HTH_USER_ACCESS_REQUEST_ID VARCHAR2(36 BYTE)  NOT NULL,
  ACCOUNT_NUMBER             VARCHAR2(64 BYTE)  NOT NULL,
  ACCOUNT_TYPE               VARCHAR2(8 BYTE)   NOT NULL,
  CURRENCY                   VARCHAR2(3 BYTE),
  DISPLAY_ORDER              NUMBER,
  OBJECT_STATUS              VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  CREATED_BY                 VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE              DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE           DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_VERSION_NUMBER      NUMBER             DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_UAR_ACCOUNT PRIMARY KEY (ID),
  CONSTRAINT UK_HTH_UAR_ACCOUNT UNIQUE
    (HTH_USER_ACCESS_REQUEST_ID, ACCOUNT_NUMBER),
  CONSTRAINT FK_HTH_UARA_TO_REQUEST
    FOREIGN KEY (HTH_USER_ACCESS_REQUEST_ID)
    REFERENCES HTH_BEAUAT.HTH_USER_ACCESS_REQUEST (ID),
  CONSTRAINT CK_HTH_UARA_TYPE CHECK (ACCOUNT_TYPE = 'CSA'),
  CONSTRAINT CK_HTH_UARA_STATUS CHECK (OBJECT_STATUS IN ('A', 'I'))
);

COMMENT ON TABLE HTH_BEAUAT.HTH_USER_ACCESS_REQ_ACCOUNT IS
  'Account snapshot submitted in an HTH user access approval request.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQ_ACCOUNT.DISPLAY_ORDER IS
  'Original account order submitted by the maker.';

-- API code/name snapshot submitted under each request account.
CREATE TABLE HTH_BEAUAT.HTH_USER_ACCESS_REQ_API (
  ID                         VARCHAR2(36 BYTE)  NOT NULL,
  HTH_USER_ACCESS_REQ_ACC_ID VARCHAR2(36 BYTE)  NOT NULL,
  API_MASTER_ID              VARCHAR2(36 BYTE)  NOT NULL,
  API_CODE                   VARCHAR2(64 BYTE)  NOT NULL,
  API_NAME                   VARCHAR2(255 BYTE) NOT NULL,
  DISPLAY_ORDER              NUMBER,
  OBJECT_STATUS              VARCHAR2(1 BYTE)   DEFAULT 'A' NOT NULL,
  CREATED_BY                 VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE              DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY            VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE           DATE               DEFAULT SYSDATE NOT NULL,
  OBJECT_VERSION_NUMBER      NUMBER             DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTH_UAR_API PRIMARY KEY (ID),
  CONSTRAINT UK_HTH_UAR_API UNIQUE
    (HTH_USER_ACCESS_REQ_ACC_ID, API_MASTER_ID),
  CONSTRAINT FK_HTH_UARA_TO_ACCOUNT
    FOREIGN KEY (HTH_USER_ACCESS_REQ_ACC_ID)
    REFERENCES HTH_BEAUAT.HTH_USER_ACCESS_REQ_ACCOUNT (ID),
  CONSTRAINT FK_HTH_UARA_TO_API FOREIGN KEY (API_MASTER_ID)
    REFERENCES HTH_BEAUAT.HTH_API_MASTER (ID),
  CONSTRAINT CK_HTH_UARAPI_STATUS CHECK (OBJECT_STATUS IN ('A', 'I'))
);

CREATE INDEX HTH_BEAUAT.IX_HTH_UARAPI_API
  ON HTH_BEAUAT.HTH_USER_ACCESS_REQ_API (API_MASTER_ID);

COMMENT ON TABLE HTH_BEAUAT.HTH_USER_ACCESS_REQ_API IS
  'API code/name snapshot submitted for an HTH user account.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQ_API.API_CODE IS
  'Copied at submit time for historical review.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQ_API.API_NAME IS
  'Copied at submit time so later master renames do not change history.';
COMMENT ON COLUMN HTH_BEAUAT.HTH_USER_ACCESS_REQ_API.DISPLAY_ORDER IS
  'Original API order submitted by the maker.';

COMMIT;
