define({
    title: "HTH 開通審計詳情",
    download: "下載 HTH 審計詳情",
    field: "欄位",
    value: "值",
    auditId: "審計編號",
    operation: "操作",
    actorUserId: "操作用戶",
    targetUserId: "目標用戶",
    partyId: "公司編號",
    targetUnit: "業務單位",
    oldUserChannelType: "原用戶渠道類型",
    newUserChannelType: "新用戶渠道類型",
    approvalReference: "審批參考編號",
    referenceNumber: "參考編號",
    occurredAt: "時間 (UTC)",
    businessOutcome: "結果",
    errorCode: "錯誤代碼",
    codeId: "Code 記錄編號",
    previousCodeId: "原 Code 記錄編號",
    purpose: "Code 用途",
    codeStatus: "Code 狀態",
    requestId: "請求編號",
    idempotentReplay: "重複請求",
    accessPartyId: "權限所屬公司",
    linkageType: "關聯類型",
    effectiveChange: "權限已變更",
    change: "變更",
    accountType: "賬戶類型",
    maskedAccountNumber: "賬戶",
    apiMasterId: "API 服務編號"
});
