-- Run in the OBDX configuration/profile schema. DDL commits implicitly in Oracle.
-- Persistent delivery intent, NOT another User/Permission table. Never drop on redeployment.
DECLARE
  existing_table NUMBER;
  existing_index NUMBER;
BEGIN
  SELECT COUNT(*) INTO existing_table FROM USER_TABLES WHERE TABLE_NAME = 'DIGX_CZ_HTH_ACCESS_NOTIFY';
  IF existing_table = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE DIGX_CZ_HTH_ACCESS_NOTIFY (
      ID VARCHAR2(32) NOT NULL, TARGET_UNIT VARCHAR2(50) NOT NULL,
      APPROVAL_REF VARCHAR2(100) NOT NULL, PARTY_ID VARCHAR2(50) NOT NULL,
      TARGET_USER_ID VARCHAR2(254) NOT NULL, APPROVER_ID VARCHAR2(254) NOT NULL,
      CHANGE_TYPE VARCHAR2(10) NOT NULL, RECIPIENT_ROLE VARCHAR2(10) NOT NULL,
      CHANNEL VARCHAR2(5) NOT NULL, ADDRESS VARCHAR2(320) NOT NULL,
      RECIPIENT_USER_ID VARCHAR2(254) NOT NULL, USER_LOCALE VARCHAR2(20),
      APPROVED_AT VARCHAR2(30) NOT NULL, STATE VARCHAR2(30) NOT NULL,
      PARENT_ID VARCHAR2(32), COD_ACT_DATA_ID VARCHAR2(100),
      CLOSE_ID VARCHAR2(254) NOT NULL, ACCESS_PARTY_ID VARCHAR2(50) NOT NULL,
      LINKAGE_TYPE VARCHAR2(10) NOT NULL, COMPANY_NAME VARCHAR2(500),
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_HTH_ACCESS_NOTIFY PRIMARY KEY (ID),
      CONSTRAINT UK_HTH_ACCESS_PARENT UNIQUE (PARENT_ID),
      CONSTRAINT FK_HTH_ACCESS_PARENT FOREIGN KEY (PARENT_ID) REFERENCES DIGX_CZ_HTH_ACCESS_NOTIFY (ID),
      CONSTRAINT CK_HTH_ACCESS_TYPE CHECK (CHANGE_TYPE IN (''LINK'',''UPDATE'')),
      CONSTRAINT CK_HTH_ACCESS_CHANNEL CHECK (CHANNEL IN (''EMAIL'',''SMS'')),
      CONSTRAINT CK_HTH_ACCESS_ROLE CHECK (RECIPIENT_ROLE IN (''API'',''AP'',''COMPANY'',''FALLBACK'')),
      CONSTRAINT CK_HTH_ACCESS_FALLBACK CHECK ((RECIPIENT_ROLE = ''FALLBACK'' AND PARENT_ID IS NOT NULL AND CHANNEL = ''EMAIL'') OR (RECIPIENT_ROLE IN (''API'',''AP'',''COMPANY'') AND PARENT_ID IS NULL)),
      CONSTRAINT CK_HTH_ACCESS_STATE CHECK (STATE IN (''READY'',''PUBLISHING'',''PUBLISHED'',''SENDING'',''SUBMITTED'',''REJECTED'',''UNKNOWN'',''DELIVERY_FAILED'',''FALLBACK_QUEUED'',''FAILED_FINAL''))
    )';
  END IF;
  SELECT COUNT(*) INTO existing_index FROM USER_INDEXES WHERE INDEX_NAME='IX_HTH_ACCESS_PENDING';
  IF existing_index = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_HTH_ACCESS_PENDING ON DIGX_CZ_HTH_ACCESS_NOTIFY (TARGET_UNIT, STATE, UPDATED_AT)';
  END IF;
END;
