-- Read-only verification. Run in the same schema used by DIGX and the configured delivery datasource.
SELECT USER AS LOGIN_SCHEMA, SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA FROM DUAL;

-- Expected: 22 columns, 8 named constraints (7 + state constraint), 1 pending index. Existing partial schemas are not silently altered.
SELECT 'LEDGER_COLUMNS' AS CHECK_ITEM, COUNT(*) AS ACTUAL, 22 AS EXPECTED
FROM USER_TAB_COLUMNS WHERE TABLE_NAME='DIGX_CZ_HTH_ACCESS_NOTIFY'
UNION ALL
SELECT 'LEDGER_CONSTRAINTS', COUNT(*), 7 FROM USER_CONSTRAINTS
WHERE TABLE_NAME='DIGX_CZ_HTH_ACCESS_NOTIFY' AND STATUS='ENABLED' AND CONSTRAINT_NAME IN (
 'PK_HTH_ACCESS_NOTIFY','UK_HTH_ACCESS_PARENT','FK_HTH_ACCESS_PARENT',
 'CK_HTH_ACCESS_TYPE','CK_HTH_ACCESS_CHANNEL','CK_HTH_ACCESS_ROLE','CK_HTH_ACCESS_FALLBACK')
UNION ALL
SELECT 'LEDGER_STATE_CONSTRAINT', COUNT(*), 1 FROM USER_CONSTRAINTS
WHERE TABLE_NAME='DIGX_CZ_HTH_ACCESS_NOTIFY' AND CONSTRAINT_NAME='CK_HTH_ACCESS_STATE' AND STATUS='ENABLED'
UNION ALL
SELECT 'LEDGER_PENDING_INDEX', COUNT(*), 1 FROM USER_INDEXES
WHERE TABLE_NAME='DIGX_CZ_HTH_ACCESS_NOTIFY' AND INDEX_NAME='IX_HTH_ACCESS_PENDING';

SELECT COLUMN_NAME, DATA_TYPE, CHAR_LENGTH, NULLABLE FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='DIGX_CZ_HTH_ACCESS_NOTIFY' ORDER BY COLUMN_ID;

-- Expected: one enabled configuration row per key; enabled=false on first deployment.
SELECT PROP_ID, PROP_VALUE, OBJECT_STATUS, COUNT(*) OVER (PARTITION BY CATEGORY_ID, PROP_ID) AS COPIES
FROM DIGX_FW_CONFIG_ALL_B WHERE CATEGORY_ID='HthUserAccessNotification' ORDER BY PROP_ID;

-- MNG and bounce reference columns must accommodate 'HA' + 32 hex characters (34 total).
-- Also check the actual MNG/provider contract preserves this reference in negative receipts.
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_LENGTH FROM USER_TAB_COLUMNS
WHERE (TABLE_NAME='DIGX_CZ_EMAIL_MNG' AND COLUMN_NAME IN ('REFNUMBER','RECIPIENTID','CUSTOMERID','PARTYID','ACTIVITYID','EVENTID','ORG_REF_NO','MESSAGEBODY','SUBJECT','COD_ACT_DATA_ID'))
   OR (TABLE_NAME='DIGX_CZ_BATCH_BOUNCE_BACK_CCBEMAIL' AND COLUMN_NAME='SRC_SYS_REF_NUM')
ORDER BY TABLE_NAME,COLUMN_NAME;

-- Existing HTH Activity metadata is preserved if present. Verify both activities are active in this environment.
SELECT COD_ACT_ID, TXT_LOG_CLASS, OBJECT_STATUS, DOMAIN_OBJECT_EXTN FROM DIGX_EP_ACT_B
WHERE COD_ACT_ID IN ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostUserAccess.submit','com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostUserAccess.edit');

-- Expected: two events, each with one mandatory immediate action and six recipient/template rows.
WITH expected AS (
 SELECT 'HTH_USER_ACCESS_LINKED' AS EVENT_ID, 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostUserAccess.submit' AS ACTIVITY FROM DUAL UNION ALL
 SELECT 'HTH_USER_ACCESS_UPDATED', 'com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostUserAccess.edit' FROM DUAL
)
SELECT E.EVENT_ID,
 (SELECT COUNT(*) FROM DIGX_PM_EVENT_ALL_B P WHERE P.EVENT_CODE=E.EVENT_ID) AS EVENT_ROWS,
 (SELECT COUNT(*) FROM DIGX_EP_ACT_EVT_B A WHERE A.COD_EVENT_ID=E.EVENT_ID
  AND A.COD_ACT_ID=E.ACTIVITY) AS ACTIVITY_EVENT_ROWS,
 (SELECT COUNT(*) FROM DIGX_EP_ACT_EVT_ACN_B A WHERE A.COD_EVENT_ID=E.EVENT_ID AND A.COD_ACTION_ID='A'
  AND A.COD_ACT_ID=E.ACTIVITY
  AND A.OBJECT_STATUS='A' AND A.ALERT_TYPE='M' AND A.ALERT_DISPATCH_TYPE='I'
  AND A.FLG_RETRY_ALLOWED='N' AND A.NUM_RETRY_CNT=0) AS ACTION_ROWS,
 (SELECT COUNT(*) FROM DIGX_EP_EVT_REC_B R JOIN DIGX_EP_MSG_TMPL_B T
  ON T.COD_TMPL_ID=R.COD_MSG_TMPL_ID AND T.DETERMINANT_VALUE='OBDX_BU'
  WHERE R.COD_EVENT_ID=E.EVENT_ID AND R.COD_ACTION_ID='A'
   AND R.COD_ACT_ID=E.ACTIVITY
   AND R.TXT_DEST_TYP=T.DESTINATION_TYPE AND T.OBJECT_STATUS='A'
   AND R.SUBSCRIBER_TYPE='EXTERNAL' AND R.ALERTTYPE='M'
   AND R.LOCALE IN ('en','zh-Hant','zh-Hans-CN')) AS RECIPIENT_TEMPLATE_ROWS
FROM expected E ORDER BY E.EVENT_ID;

-- Shared generic attributes are not overwritten by 1216. Expected: three active String attributes.
SELECT COD_CONSTRAINT_ATTR_ID, TXT_CONSTRAINT_ATTR_NAME, DATA_TYPE, OBJECT_STATUS
FROM DIGX_MD_GEN_ATTR_LEGACY_B
WHERE COD_CONSTRAINT_ATTR_ID IN ('userNameId','userSysDate','compName')
ORDER BY COD_CONSTRAINT_ATTR_ID;

-- Expected: 12 rows. EMAIL must have three correctly mapped attributes; SMS has none.
WITH expected_fields AS (
 SELECT 'userNameId' AS ATTR_ID, 'com.ofss.digx.cz.bea.app.hosttohost.dto.HthUserAccessActivityLogDTO.UserNameId' AS REF_PATH FROM DUAL UNION ALL
 SELECT 'userSysDate' AS ATTR_ID, 'com.ofss.digx.cz.bea.app.hosttohost.dto.HthUserAccessActivityLogDTO.UserSysDate' AS REF_PATH FROM DUAL UNION ALL
 SELECT 'compName' AS ATTR_ID, 'com.ofss.digx.cz.bea.app.hosttohost.dto.HthUserAccessActivityLogDTO.CompName' AS REF_PATH FROM DUAL
)
SELECT T.COD_TMPL_ID, T.DESTINATION_TYPE,
 (SELECT COUNT(*) FROM DIGX_EP_MSG_ATTR_B A
  JOIN DIGX_EP_MSG_SRC_B M ON M.COD_MESS_TMPL_ID=A.COD_MESS_TMPL_ID AND M.COD_ATTR_ID=A.COD_ATTR_ID
    AND M.DETERMINANT_VALUE=A.DETERMINANT_VALUE
  JOIN DIGX_MD_SERVICE_ATTR S ON S.COD_SERVICE_ATTR_ID=M.COD_SERVICE_ATTR_ID
  JOIN DIGX_MD_GEN_ATTR_LEGACY_B G ON G.COD_CONSTRAINT_ATTR_ID=S.COD_ATTR_ID
  JOIN expected_fields F ON F.ATTR_ID=A.COD_ATTR_ID AND F.REF_PATH=S.REF_FIELD_DEFN_ID
  WHERE A.COD_MESS_TMPL_ID=T.COD_TMPL_ID AND A.DETERMINANT_VALUE=T.DETERMINANT_VALUE
    AND M.COD_ACT_ID IN ('com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostUserAccess.submit','com.ofss.digx.cz.bea.app.hosttohost.service.HostToHostUserAccess.edit')
    AND S.COD_SERVICE_ID=M.COD_ACT_ID AND S.TYP_DATA_SRC='DTO' AND S.OBJECT_STATUS='A'
    AND G.DATA_TYPE='java.lang.String' AND G.OBJECT_STATUS='A'
    AND A.DOMAIN_OBJECT_EXTN='CZ') AS VALID_ATTRIBUTES,
 CASE WHEN T.DESTINATION_TYPE='EMAIL' THEN 3 ELSE 0 END AS EXPECTED_ATTRIBUTES
FROM DIGX_EP_MSG_TMPL_B T WHERE T.COD_TMPL_ID LIKE 'HTH\_1216\_%' ESCAPE '\' AND T.DETERMINANT_VALUE='OBDX_BU'
ORDER BY T.COD_TMPL_ID;

-- Expected: zero. Do not opt 1216 into the generic BCO cascade.
SELECT EVENTID FROM DIGX_CZ_BATCH_HIGH_ALERT_EVENT_LIST WHERE EVENTID IN ('HTH_USER_ACCESS_LINKED','HTH_USER_ACCESS_UPDATED');

-- Delivery diagnostics: no address or message text in this default report.
SELECT N.ID, N.APPROVAL_REF, N.CHANGE_TYPE, N.RECIPIENT_ROLE, N.CHANNEL, N.STATE,
 N.PARENT_ID, N.COD_ACT_DATA_ID, M.REFNUMBER, M.EVENTID, M.RESPONSE_STATUS, N.UPDATED_AT
FROM DIGX_CZ_HTH_ACCESS_NOTIFY N LEFT JOIN DIGX_CZ_EMAIL_MNG M ON M.REFNUMBER='HA'||N.ID
WHERE N.UPDATED_AT >= CURRENT_TIMESTAMP - INTERVAL '7' DAY ORDER BY N.UPDATED_AT DESC;

-- Stuck PUBLISHING/PUBLISHED: template/event worker/configuration; UNKNOWN: investigate the MNG reference, never blindly resend.
SELECT STATE, CHANNEL, COUNT(*) AS ROWS_COUNT, MIN(UPDATED_AT) AS OLDEST
FROM DIGX_CZ_HTH_ACCESS_NOTIFY GROUP BY STATE,CHANNEL ORDER BY STATE,CHANNEL;
