-- BCOH2H-787: HTH API Password - First Time Setup schema.
-- Single table HTH_BEA.HTH_API_PASSWORD_CODE holding the one-time setup code lifecycle:
-- maker generate -> original user-maintenance approval activates -> first-time setup consumes
-- (USED) / expiry (EXPIRED) / regeneration or lockout (INVALID).
-- Conventions follow 20260825_HTH_User_Access: UUID VARCHAR2(36) primary key, logical keys
-- enforced by the application, OBJECT_STATUS soft delete, four audit columns, and no
-- OBJECT_VERSION_NUMBER (same shape as the newer HTH tables).
-- Re-runnable: the feature-owned table is created only when absent.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM ALL_TABLES
   WHERE OWNER = 'HTH_BEA' AND TABLE_NAME = 'HTH_API_PASSWORD_CODE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
CREATE TABLE HTH_BEA.HTH_API_PASSWORD_CODE (
  ID               VARCHAR2(36 BYTE)  NOT NULL,
  PARTY_ID         VARCHAR2(64 BYTE)  NOT NULL,
  USER_NAME        VARCHAR2(255 BYTE) NOT NULL,
  TRANSACTION_ID   VARCHAR2(64 BYTE),
  CODE_CIPHER      VARCHAR2(512 BYTE) NOT NULL,
  STATUS           VARCHAR2(16 BYTE)  DEFAULT ''PENDING'' NOT NULL,
  ATTEMPT_COUNT    NUMBER(3)          DEFAULT 0 NOT NULL,
  EXPIRY_TIME      TIMESTAMP(6),
  USED_TIME        TIMESTAMP(6),
  OBJECT_STATUS    VARCHAR2(1 BYTE)   DEFAULT ''A'' NOT NULL,
  CREATED_BY       VARCHAR2(255 BYTE) NOT NULL,
  CREATION_DATE    DATE               DEFAULT SYSDATE NOT NULL,
  LAST_UPDATED_BY  VARCHAR2(255 BYTE) NOT NULL,
  LAST_UPDATE_DATE DATE               DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_HTH_API_PASSWORD_CODE PRIMARY KEY (ID),
  CONSTRAINT CK_HTH_API_PWD_CODE_STATUS CHECK (STATUS IN
    (''PENDING'', ''ACTIVE'', ''USED'', ''EXPIRED'', ''INVALID''))
)';
  END IF;
END;
/

-- Indexes for the lookup paths used by the service and adapters.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM ALL_INDEXES
   WHERE OWNER = 'HTH_BEA' AND INDEX_NAME = 'IX_HTH_API_PWD_CODE_TXN';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
CREATE INDEX HTH_BEA.IX_HTH_API_PWD_CODE_TXN
   ON HTH_BEA.HTH_API_PASSWORD_CODE (TRANSACTION_ID)';
  END IF;
  SELECT COUNT(1) INTO v_count FROM ALL_INDEXES
   WHERE OWNER = 'HTH_BEA' AND INDEX_NAME = 'IX_HTH_API_PWD_CODE_OWN';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
CREATE INDEX HTH_BEA.IX_HTH_API_PWD_CODE_OWN
   ON HTH_BEA.HTH_API_PASSWORD_CODE (PARTY_ID, USER_NAME, STATUS)';
  END IF;
END;
/

-- Table and column comments (bank documentation convention).
COMMENT ON TABLE HTH_BEA.HTH_API_PASSWORD_CODE IS
  'One-time HTH API password setup code generated by a maker; usable only after the original user-maintenance flow is approved.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.ID IS
  'Surrogate UUID primary key.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.PARTY_ID IS
  'Corporate party (CDC number) owning the HTH user; known at maker time.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.USER_NAME IS
  'Username snapshot; the OBDX user may not exist until the paired user creation is approved.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.TRANSACTION_ID IS
  'OBDX transaction id of the user-maintenance request that activated the code (DIGX_AP_TRANSACTION.TXN_ID).';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.CODE_CIPHER IS
  'AES-256-GCM ciphertext (Base64) of the numeric setup code; reversible for masked reveal and verification.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.STATUS IS
  'PENDING generated, ACTIVE usable after approval, USED first-time setup done, EXPIRED past expiry, INVALID superseded or locked.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.ATTEMPT_COUNT IS
  'Failed first-time setup verification attempts for this code.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.EXPIRY_TIME IS
  'Approval time plus HTH_API_PWD_CODE_EXPIRY_HOURS; written when the original flow is approved.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.USED_TIME IS
  'Timestamp of the successful first-time password setup.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.OBJECT_STATUS IS
  'A=active, I=inactive (soft delete).';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.CREATED_BY IS
  'Operator who generated the code (GENERATED_BY in the requirement audit list).';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.CREATION_DATE IS
  'Code generation time (GENERATED_TIME in the requirement audit list).';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.LAST_UPDATED_BY IS
  'Operator or system user of the last status change.';
COMMENT ON COLUMN HTH_BEA.HTH_API_PASSWORD_CODE.LAST_UPDATE_DATE IS
  'Timestamp of the last status change.';

COMMIT;
